// Massachusetts Cities and Towns Seed Data
// All 351 municipalities with county information

export interface MaLocationSeed {
  name: string;
  slug: string;
  county: string;
  isCity: "yes" | "no";
  zipCodes?: string[];
  population?: number;
}

// Helper to create slug
const toSlug = (name: string): string => {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/(^-|-$)/g, "");
};

// Major Massachusetts Cities (population-sorted top cities)
export const majorCities: MaLocationSeed[] = [
  { name: "Boston", slug: "boston-ma", county: "Suffolk", isCity: "yes", population: 675647, zipCodes: ["02101", "02102", "02103", "02108", "02109", "02110", "02111", "02112", "02113", "02114", "02115", "02116", "02117", "02118", "02119", "02120", "02121", "02122", "02123", "02124", "02125", "02126", "02127", "02128", "02129", "02130", "02131", "02132", "02133", "02134", "02135", "02136", "02137", "02163", "02196", "02199", "02201", "02203", "02204", "02205", "02206", "02210", "02211", "02212", "02215", "02217", "02222", "02241", "02266", "02283", "02284", "02293", "02297", "02298"] },
  { name: "Worcester", slug: "worcester-ma", county: "Worcester", isCity: "yes", population: 206518, zipCodes: ["01601", "01602", "01603", "01604", "01605", "01606", "01607", "01608", "01609", "01610", "01613", "01614", "01615", "01653", "01654", "01655"] },
  { name: "Springfield", slug: "springfield-ma", county: "Hampden", isCity: "yes", population: 155929, zipCodes: ["01101", "01102", "01103", "01104", "01105", "01107", "01108", "01109", "01111", "01115", "01118", "01119", "01128", "01129", "01138", "01139", "01144", "01151", "01152", "01199"] },
  { name: "Lowell", slug: "lowell-ma", county: "Middlesex", isCity: "yes", population: 115554, zipCodes: ["01850", "01851", "01852", "01853", "01854"] },
  { name: "Cambridge", slug: "cambridge-ma", county: "Middlesex", isCity: "yes", population: 118403, zipCodes: ["02138", "02139", "02140", "02141", "02142", "02238"] },
  { name: "New Bedford", slug: "new-bedford-ma", county: "Bristol", isCity: "yes", population: 101079, zipCodes: ["02740", "02741", "02742", "02744", "02745", "02746"] },
  { name: "Brockton", slug: "brockton-ma", county: "Plymouth", isCity: "yes", population: 105643, zipCodes: ["02301", "02302", "02303", "02304", "02305"] },
  { name: "Quincy", slug: "quincy-ma", county: "Norfolk", isCity: "yes", population: 101636, zipCodes: ["02169", "02170", "02171", "02269"] },
  { name: "Lynn", slug: "lynn-ma", county: "Essex", isCity: "yes", population: 101253, zipCodes: ["01901", "01902", "01903", "01904", "01905", "01910"] },
  { name: "Fall River", slug: "fall-river-ma", county: "Bristol", isCity: "yes", population: 93885, zipCodes: ["02720", "02721", "02722", "02723", "02724"] },
  { name: "Newton", slug: "newton-ma", county: "Middlesex", isCity: "yes", population: 88923, zipCodes: ["02458", "02459", "02460", "02461", "02462", "02464", "02465", "02466", "02467", "02468", "02494", "02495"] },
  { name: "Lawrence", slug: "lawrence-ma", county: "Essex", isCity: "yes", population: 89143, zipCodes: ["01840", "01841", "01842", "01843"] },
  { name: "Somerville", slug: "somerville-ma", county: "Middlesex", isCity: "yes", population: 81360, zipCodes: ["02143", "02144", "02145"] },
  { name: "Framingham", slug: "framingham-ma", county: "Middlesex", isCity: "yes", population: 72032, zipCodes: ["01701", "01702", "01703", "01704", "01705"] },
  { name: "Haverhill", slug: "haverhill-ma", county: "Essex", isCity: "yes", population: 67787, zipCodes: ["01830", "01831", "01832", "01835"] },
  { name: "Waltham", slug: "waltham-ma", county: "Middlesex", isCity: "yes", population: 62227, zipCodes: ["02451", "02452", "02453", "02454", "02455"] },
  { name: "Malden", slug: "malden-ma", county: "Middlesex", isCity: "yes", population: 66263, zipCodes: ["02148"] },
  { name: "Brookline", slug: "brookline-ma", county: "Norfolk", isCity: "no", population: 63191, zipCodes: ["02445", "02446", "02467"] },
  { name: "Plymouth", slug: "plymouth-ma", county: "Plymouth", isCity: "no", population: 61217, zipCodes: ["02360", "02361", "02362"] },
  { name: "Medford", slug: "medford-ma", county: "Middlesex", isCity: "yes", population: 59867, zipCodes: ["02153", "02155", "02156"] },
  { name: "Taunton", slug: "taunton-ma", county: "Bristol", isCity: "yes", population: 59587, zipCodes: ["02780", "02783"] },
  { name: "Weymouth", slug: "weymouth-ma", county: "Norfolk", isCity: "no", population: 57746, zipCodes: ["02188", "02189", "02190", "02191"] },
  { name: "Revere", slug: "revere-ma", county: "Suffolk", isCity: "yes", population: 62186, zipCodes: ["02151"] },
  { name: "Peabody", slug: "peabody-ma", county: "Essex", isCity: "yes", population: 54200, zipCodes: ["01960", "01961"] },
  { name: "Methuen", slug: "methuen-ma", county: "Essex", isCity: "yes", population: 52024, zipCodes: ["01844"] },
  { name: "Barnstable", slug: "barnstable-ma", county: "Barnstable", isCity: "yes", population: 44641, zipCodes: ["02630", "02601", "02632", "02635", "02637", "02647", "02648", "02668", "02672", "02675"] },
  { name: "Pittsfield", slug: "pittsfield-ma", county: "Berkshire", isCity: "yes", population: 42514, zipCodes: ["01201", "01202", "01203"] },
  { name: "Attleboro", slug: "attleboro-ma", county: "Bristol", isCity: "yes", population: 46457, zipCodes: ["02703"] },
  { name: "Arlington", slug: "arlington-ma", county: "Middlesex", isCity: "no", population: 46308, zipCodes: ["02474", "02475", "02476"] },
  { name: "Everett", slug: "everett-ma", county: "Middlesex", isCity: "yes", population: 49938, zipCodes: ["02149"] },
];

// Complete list of all Massachusetts municipalities
export const allMaLocations: MaLocationSeed[] = [
  // A
  { name: "Abington", slug: "abington-ma", county: "Plymouth", isCity: "no" },
  { name: "Acton", slug: "acton-ma", county: "Middlesex", isCity: "no" },
  { name: "Acushnet", slug: "acushnet-ma", county: "Bristol", isCity: "no" },
  { name: "Adams", slug: "adams-ma", county: "Berkshire", isCity: "no" },
  { name: "Agawam", slug: "agawam-ma", county: "Hampden", isCity: "yes" },
  { name: "Alford", slug: "alford-ma", county: "Berkshire", isCity: "no" },
  { name: "Amesbury", slug: "amesbury-ma", county: "Essex", isCity: "yes" },
  { name: "Amherst", slug: "amherst-ma", county: "Hampshire", isCity: "no" },
  { name: "Andover", slug: "andover-ma", county: "Essex", isCity: "no" },
  { name: "Aquinnah", slug: "aquinnah-ma", county: "Dukes", isCity: "no" },
  { name: "Arlington", slug: "arlington-ma", county: "Middlesex", isCity: "no" },
  { name: "Ashburnham", slug: "ashburnham-ma", county: "Worcester", isCity: "no" },
  { name: "Ashby", slug: "ashby-ma", county: "Middlesex", isCity: "no" },
  { name: "Ashfield", slug: "ashfield-ma", county: "Franklin", isCity: "no" },
  { name: "Ashland", slug: "ashland-ma", county: "Middlesex", isCity: "no" },
  { name: "Athol", slug: "athol-ma", county: "Worcester", isCity: "no" },
  { name: "Attleboro", slug: "attleboro-ma", county: "Bristol", isCity: "yes" },
  { name: "Auburn", slug: "auburn-ma", county: "Worcester", isCity: "no" },
  { name: "Avon", slug: "avon-ma", county: "Norfolk", isCity: "no" },
  { name: "Ayer", slug: "ayer-ma", county: "Middlesex", isCity: "no" },
  // B
  { name: "Barnstable", slug: "barnstable-ma", county: "Barnstable", isCity: "yes" },
  { name: "Barre", slug: "barre-ma", county: "Worcester", isCity: "no" },
  { name: "Becket", slug: "becket-ma", county: "Berkshire", isCity: "no" },
  { name: "Bedford", slug: "bedford-ma", county: "Middlesex", isCity: "no" },
  { name: "Belchertown", slug: "belchertown-ma", county: "Hampshire", isCity: "no" },
  { name: "Bellingham", slug: "bellingham-ma", county: "Norfolk", isCity: "no" },
  { name: "Belmont", slug: "belmont-ma", county: "Middlesex", isCity: "no" },
  { name: "Berkley", slug: "berkley-ma", county: "Bristol", isCity: "no" },
  { name: "Berlin", slug: "berlin-ma", county: "Worcester", isCity: "no" },
  { name: "Bernardston", slug: "bernardston-ma", county: "Franklin", isCity: "no" },
  { name: "Beverly", slug: "beverly-ma", county: "Essex", isCity: "yes" },
  { name: "Billerica", slug: "billerica-ma", county: "Middlesex", isCity: "no" },
  { name: "Blackstone", slug: "blackstone-ma", county: "Worcester", isCity: "no" },
  { name: "Blandford", slug: "blandford-ma", county: "Hampden", isCity: "no" },
  { name: "Bolton", slug: "bolton-ma", county: "Worcester", isCity: "no" },
  { name: "Boston", slug: "boston-ma", county: "Suffolk", isCity: "yes" },
  { name: "Bourne", slug: "bourne-ma", county: "Barnstable", isCity: "no" },
  { name: "Boxborough", slug: "boxborough-ma", county: "Middlesex", isCity: "no" },
  { name: "Boxford", slug: "boxford-ma", county: "Essex", isCity: "no" },
  { name: "Boylston", slug: "boylston-ma", county: "Worcester", isCity: "no" },
  { name: "Braintree", slug: "braintree-ma", county: "Norfolk", isCity: "no" },
  { name: "Brewster", slug: "brewster-ma", county: "Barnstable", isCity: "no" },
  { name: "Bridgewater", slug: "bridgewater-ma", county: "Plymouth", isCity: "no" },
  { name: "Brimfield", slug: "brimfield-ma", county: "Hampden", isCity: "no" },
  { name: "Brockton", slug: "brockton-ma", county: "Plymouth", isCity: "yes" },
  { name: "Brookfield", slug: "brookfield-ma", county: "Worcester", isCity: "no" },
  { name: "Brookline", slug: "brookline-ma", county: "Norfolk", isCity: "no" },
  { name: "Buckland", slug: "buckland-ma", county: "Franklin", isCity: "no" },
  { name: "Burlington", slug: "burlington-ma", county: "Middlesex", isCity: "no" },
  // C
  { name: "Cambridge", slug: "cambridge-ma", county: "Middlesex", isCity: "yes" },
  { name: "Canton", slug: "canton-ma", county: "Norfolk", isCity: "no" },
  { name: "Carlisle", slug: "carlisle-ma", county: "Middlesex", isCity: "no" },
  { name: "Carver", slug: "carver-ma", county: "Plymouth", isCity: "no" },
  { name: "Charlemont", slug: "charlemont-ma", county: "Franklin", isCity: "no" },
  { name: "Charlton", slug: "charlton-ma", county: "Worcester", isCity: "no" },
  { name: "Chatham", slug: "chatham-ma", county: "Barnstable", isCity: "no" },
  { name: "Chelmsford", slug: "chelmsford-ma", county: "Middlesex", isCity: "no" },
  { name: "Chelsea", slug: "chelsea-ma", county: "Suffolk", isCity: "yes" },
  { name: "Cheshire", slug: "cheshire-ma", county: "Berkshire", isCity: "no" },
  { name: "Chester", slug: "chester-ma", county: "Hampden", isCity: "no" },
  { name: "Chesterfield", slug: "chesterfield-ma", county: "Hampshire", isCity: "no" },
  { name: "Chicopee", slug: "chicopee-ma", county: "Hampden", isCity: "yes" },
  { name: "Chilmark", slug: "chilmark-ma", county: "Dukes", isCity: "no" },
  { name: "Clarksburg", slug: "clarksburg-ma", county: "Berkshire", isCity: "no" },
  { name: "Clinton", slug: "clinton-ma", county: "Worcester", isCity: "no" },
  { name: "Cohasset", slug: "cohasset-ma", county: "Norfolk", isCity: "no" },
  { name: "Colrain", slug: "colrain-ma", county: "Franklin", isCity: "no" },
  { name: "Concord", slug: "concord-ma", county: "Middlesex", isCity: "no" },
  { name: "Conway", slug: "conway-ma", county: "Franklin", isCity: "no" },
  { name: "Cummington", slug: "cummington-ma", county: "Hampshire", isCity: "no" },
  // D
  { name: "Dalton", slug: "dalton-ma", county: "Berkshire", isCity: "no" },
  { name: "Danvers", slug: "danvers-ma", county: "Essex", isCity: "no" },
  { name: "Dartmouth", slug: "dartmouth-ma", county: "Bristol", isCity: "no" },
  { name: "Dedham", slug: "dedham-ma", county: "Norfolk", isCity: "no" },
  { name: "Deerfield", slug: "deerfield-ma", county: "Franklin", isCity: "no" },
  { name: "Dennis", slug: "dennis-ma", county: "Barnstable", isCity: "no" },
  { name: "Dighton", slug: "dighton-ma", county: "Bristol", isCity: "no" },
  { name: "Douglas", slug: "douglas-ma", county: "Worcester", isCity: "no" },
  { name: "Dover", slug: "dover-ma", county: "Norfolk", isCity: "no" },
  { name: "Dracut", slug: "dracut-ma", county: "Middlesex", isCity: "no" },
  { name: "Dudley", slug: "dudley-ma", county: "Worcester", isCity: "no" },
  { name: "Dunstable", slug: "dunstable-ma", county: "Middlesex", isCity: "no" },
  { name: "Duxbury", slug: "duxbury-ma", county: "Plymouth", isCity: "no" },
  // E
  { name: "East Bridgewater", slug: "east-bridgewater-ma", county: "Plymouth", isCity: "no" },
  { name: "East Brookfield", slug: "east-brookfield-ma", county: "Worcester", isCity: "no" },
  { name: "East Longmeadow", slug: "east-longmeadow-ma", county: "Hampden", isCity: "no" },
  { name: "Eastham", slug: "eastham-ma", county: "Barnstable", isCity: "no" },
  { name: "Easthampton", slug: "easthampton-ma", county: "Hampshire", isCity: "yes" },
  { name: "Easton", slug: "easton-ma", county: "Bristol", isCity: "no" },
  { name: "Edgartown", slug: "edgartown-ma", county: "Dukes", isCity: "no" },
  { name: "Egremont", slug: "egremont-ma", county: "Berkshire", isCity: "no" },
  { name: "Erving", slug: "erving-ma", county: "Franklin", isCity: "no" },
  { name: "Essex", slug: "essex-ma", county: "Essex", isCity: "no" },
  { name: "Everett", slug: "everett-ma", county: "Middlesex", isCity: "yes" },
  // F
  { name: "Fairhaven", slug: "fairhaven-ma", county: "Bristol", isCity: "no" },
  { name: "Fall River", slug: "fall-river-ma", county: "Bristol", isCity: "yes" },
  { name: "Falmouth", slug: "falmouth-ma", county: "Barnstable", isCity: "no" },
  { name: "Fitchburg", slug: "fitchburg-ma", county: "Worcester", isCity: "yes" },
  { name: "Florida", slug: "florida-ma", county: "Berkshire", isCity: "no" },
  { name: "Foxborough", slug: "foxborough-ma", county: "Norfolk", isCity: "no" },
  { name: "Framingham", slug: "framingham-ma", county: "Middlesex", isCity: "yes" },
  { name: "Franklin", slug: "franklin-ma", county: "Norfolk", isCity: "no" },
  { name: "Freetown", slug: "freetown-ma", county: "Bristol", isCity: "no" },
  // G
  { name: "Gardner", slug: "gardner-ma", county: "Worcester", isCity: "yes" },
  { name: "Georgetown", slug: "georgetown-ma", county: "Essex", isCity: "no" },
  { name: "Gill", slug: "gill-ma", county: "Franklin", isCity: "no" },
  { name: "Gloucester", slug: "gloucester-ma", county: "Essex", isCity: "yes" },
  { name: "Goshen", slug: "goshen-ma", county: "Hampshire", isCity: "no" },
  { name: "Gosnold", slug: "gosnold-ma", county: "Dukes", isCity: "no" },
  { name: "Grafton", slug: "grafton-ma", county: "Worcester", isCity: "no" },
  { name: "Granby", slug: "granby-ma", county: "Hampshire", isCity: "no" },
  { name: "Granville", slug: "granville-ma", county: "Hampden", isCity: "no" },
  { name: "Great Barrington", slug: "great-barrington-ma", county: "Berkshire", isCity: "no" },
  { name: "Greenfield", slug: "greenfield-ma", county: "Franklin", isCity: "yes" },
  { name: "Groton", slug: "groton-ma", county: "Middlesex", isCity: "no" },
  { name: "Groveland", slug: "groveland-ma", county: "Essex", isCity: "no" },
  // H
  { name: "Hadley", slug: "hadley-ma", county: "Hampshire", isCity: "no" },
  { name: "Halifax", slug: "halifax-ma", county: "Plymouth", isCity: "no" },
  { name: "Hamilton", slug: "hamilton-ma", county: "Essex", isCity: "no" },
  { name: "Hampden", slug: "hampden-ma", county: "Hampden", isCity: "no" },
  { name: "Hancock", slug: "hancock-ma", county: "Berkshire", isCity: "no" },
  { name: "Hanover", slug: "hanover-ma", county: "Plymouth", isCity: "no" },
  { name: "Hanson", slug: "hanson-ma", county: "Plymouth", isCity: "no" },
  { name: "Hardwick", slug: "hardwick-ma", county: "Worcester", isCity: "no" },
  { name: "Harvard", slug: "harvard-ma", county: "Worcester", isCity: "no" },
  { name: "Harwich", slug: "harwich-ma", county: "Barnstable", isCity: "no" },
  { name: "Hatfield", slug: "hatfield-ma", county: "Hampshire", isCity: "no" },
  { name: "Haverhill", slug: "haverhill-ma", county: "Essex", isCity: "yes" },
  { name: "Hawley", slug: "hawley-ma", county: "Franklin", isCity: "no" },
  { name: "Heath", slug: "heath-ma", county: "Franklin", isCity: "no" },
  { name: "Hingham", slug: "hingham-ma", county: "Plymouth", isCity: "no" },
  { name: "Hinsdale", slug: "hinsdale-ma", county: "Berkshire", isCity: "no" },
  { name: "Holbrook", slug: "holbrook-ma", county: "Norfolk", isCity: "no" },
  { name: "Holden", slug: "holden-ma", county: "Worcester", isCity: "no" },
  { name: "Holland", slug: "holland-ma", county: "Hampden", isCity: "no" },
  { name: "Holliston", slug: "holliston-ma", county: "Middlesex", isCity: "no" },
  { name: "Holyoke", slug: "holyoke-ma", county: "Hampden", isCity: "yes" },
  { name: "Hopedale", slug: "hopedale-ma", county: "Worcester", isCity: "no" },
  { name: "Hopkinton", slug: "hopkinton-ma", county: "Middlesex", isCity: "no" },
  { name: "Hubbardston", slug: "hubbardston-ma", county: "Worcester", isCity: "no" },
  { name: "Hudson", slug: "hudson-ma", county: "Middlesex", isCity: "no" },
  { name: "Hull", slug: "hull-ma", county: "Plymouth", isCity: "no" },
  // I
  { name: "Ipswich", slug: "ipswich-ma", county: "Essex", isCity: "no" },
  // K
  { name: "Kingston", slug: "kingston-ma", county: "Plymouth", isCity: "no" },
  // L
  { name: "Lakeville", slug: "lakeville-ma", county: "Plymouth", isCity: "no" },
  { name: "Lancaster", slug: "lancaster-ma", county: "Worcester", isCity: "no" },
  { name: "Lanesborough", slug: "lanesborough-ma", county: "Berkshire", isCity: "no" },
  { name: "Lawrence", slug: "lawrence-ma", county: "Essex", isCity: "yes" },
  { name: "Lee", slug: "lee-ma", county: "Berkshire", isCity: "no" },
  { name: "Leicester", slug: "leicester-ma", county: "Worcester", isCity: "no" },
  { name: "Lenox", slug: "lenox-ma", county: "Berkshire", isCity: "no" },
  { name: "Leominster", slug: "leominster-ma", county: "Worcester", isCity: "yes" },
  { name: "Leverett", slug: "leverett-ma", county: "Franklin", isCity: "no" },
  { name: "Lexington", slug: "lexington-ma", county: "Middlesex", isCity: "no" },
  { name: "Leyden", slug: "leyden-ma", county: "Franklin", isCity: "no" },
  { name: "Lincoln", slug: "lincoln-ma", county: "Middlesex", isCity: "no" },
  { name: "Littleton", slug: "littleton-ma", county: "Middlesex", isCity: "no" },
  { name: "Longmeadow", slug: "longmeadow-ma", county: "Hampden", isCity: "no" },
  { name: "Lowell", slug: "lowell-ma", county: "Middlesex", isCity: "yes" },
  { name: "Ludlow", slug: "ludlow-ma", county: "Hampden", isCity: "no" },
  { name: "Lunenburg", slug: "lunenburg-ma", county: "Worcester", isCity: "no" },
  { name: "Lynn", slug: "lynn-ma", county: "Essex", isCity: "yes" },
  { name: "Lynnfield", slug: "lynnfield-ma", county: "Essex", isCity: "no" },
  // M
  { name: "Malden", slug: "malden-ma", county: "Middlesex", isCity: "yes" },
  { name: "Manchester-by-the-Sea", slug: "manchester-by-the-sea-ma", county: "Essex", isCity: "no" },
  { name: "Mansfield", slug: "mansfield-ma", county: "Bristol", isCity: "no" },
  { name: "Marblehead", slug: "marblehead-ma", county: "Essex", isCity: "no" },
  { name: "Marion", slug: "marion-ma", county: "Plymouth", isCity: "no" },
  { name: "Marlborough", slug: "marlborough-ma", county: "Middlesex", isCity: "yes" },
  { name: "Marshfield", slug: "marshfield-ma", county: "Plymouth", isCity: "no" },
  { name: "Mashpee", slug: "mashpee-ma", county: "Barnstable", isCity: "no" },
  { name: "Mattapoisett", slug: "mattapoisett-ma", county: "Plymouth", isCity: "no" },
  { name: "Maynard", slug: "maynard-ma", county: "Middlesex", isCity: "no" },
  { name: "Medfield", slug: "medfield-ma", county: "Norfolk", isCity: "no" },
  { name: "Medford", slug: "medford-ma", county: "Middlesex", isCity: "yes" },
  { name: "Medway", slug: "medway-ma", county: "Norfolk", isCity: "no" },
  { name: "Melrose", slug: "melrose-ma", county: "Middlesex", isCity: "yes" },
  { name: "Mendon", slug: "mendon-ma", county: "Worcester", isCity: "no" },
  { name: "Merrimac", slug: "merrimac-ma", county: "Essex", isCity: "no" },
  { name: "Methuen", slug: "methuen-ma", county: "Essex", isCity: "yes" },
  { name: "Middleborough", slug: "middleborough-ma", county: "Plymouth", isCity: "no" },
  { name: "Middlefield", slug: "middlefield-ma", county: "Hampshire", isCity: "no" },
  { name: "Middleton", slug: "middleton-ma", county: "Essex", isCity: "no" },
  { name: "Milford", slug: "milford-ma", county: "Worcester", isCity: "no" },
  { name: "Millbury", slug: "millbury-ma", county: "Worcester", isCity: "no" },
  { name: "Millis", slug: "millis-ma", county: "Norfolk", isCity: "no" },
  { name: "Millville", slug: "millville-ma", county: "Worcester", isCity: "no" },
  { name: "Milton", slug: "milton-ma", county: "Norfolk", isCity: "no" },
  { name: "Monroe", slug: "monroe-ma", county: "Franklin", isCity: "no" },
  { name: "Monson", slug: "monson-ma", county: "Hampden", isCity: "no" },
  { name: "Montague", slug: "montague-ma", county: "Franklin", isCity: "no" },
  { name: "Monterey", slug: "monterey-ma", county: "Berkshire", isCity: "no" },
  { name: "Montgomery", slug: "montgomery-ma", county: "Hampden", isCity: "no" },
  { name: "Mount Washington", slug: "mount-washington-ma", county: "Berkshire", isCity: "no" },
  // N
  { name: "Nahant", slug: "nahant-ma", county: "Essex", isCity: "no" },
  { name: "Nantucket", slug: "nantucket-ma", county: "Nantucket", isCity: "no" },
  { name: "Natick", slug: "natick-ma", county: "Middlesex", isCity: "no" },
  { name: "Needham", slug: "needham-ma", county: "Norfolk", isCity: "no" },
  { name: "New Ashford", slug: "new-ashford-ma", county: "Berkshire", isCity: "no" },
  { name: "New Bedford", slug: "new-bedford-ma", county: "Bristol", isCity: "yes" },
  { name: "New Braintree", slug: "new-braintree-ma", county: "Worcester", isCity: "no" },
  { name: "New Marlborough", slug: "new-marlborough-ma", county: "Berkshire", isCity: "no" },
  { name: "New Salem", slug: "new-salem-ma", county: "Franklin", isCity: "no" },
  { name: "Newbury", slug: "newbury-ma", county: "Essex", isCity: "no" },
  { name: "Newburyport", slug: "newburyport-ma", county: "Essex", isCity: "yes" },
  { name: "Newton", slug: "newton-ma", county: "Middlesex", isCity: "yes" },
  { name: "Norfolk", slug: "norfolk-ma", county: "Norfolk", isCity: "no" },
  { name: "North Adams", slug: "north-adams-ma", county: "Berkshire", isCity: "yes" },
  { name: "North Andover", slug: "north-andover-ma", county: "Essex", isCity: "no" },
  { name: "North Attleborough", slug: "north-attleborough-ma", county: "Bristol", isCity: "no" },
  { name: "North Brookfield", slug: "north-brookfield-ma", county: "Worcester", isCity: "no" },
  { name: "North Reading", slug: "north-reading-ma", county: "Middlesex", isCity: "no" },
  { name: "Northampton", slug: "northampton-ma", county: "Hampshire", isCity: "yes" },
  { name: "Northborough", slug: "northborough-ma", county: "Worcester", isCity: "no" },
  { name: "Northbridge", slug: "northbridge-ma", county: "Worcester", isCity: "no" },
  { name: "Northfield", slug: "northfield-ma", county: "Franklin", isCity: "no" },
  { name: "Norton", slug: "norton-ma", county: "Bristol", isCity: "no" },
  { name: "Norwell", slug: "norwell-ma", county: "Plymouth", isCity: "no" },
  { name: "Norwood", slug: "norwood-ma", county: "Norfolk", isCity: "no" },
  // O
  { name: "Oak Bluffs", slug: "oak-bluffs-ma", county: "Dukes", isCity: "no" },
  { name: "Oakham", slug: "oakham-ma", county: "Worcester", isCity: "no" },
  { name: "Orange", slug: "orange-ma", county: "Franklin", isCity: "no" },
  { name: "Orleans", slug: "orleans-ma", county: "Barnstable", isCity: "no" },
  { name: "Otis", slug: "otis-ma", county: "Berkshire", isCity: "no" },
  { name: "Oxford", slug: "oxford-ma", county: "Worcester", isCity: "no" },
  // P
  { name: "Palmer", slug: "palmer-ma", county: "Hampden", isCity: "no" },
  { name: "Paxton", slug: "paxton-ma", county: "Worcester", isCity: "no" },
  { name: "Peabody", slug: "peabody-ma", county: "Essex", isCity: "yes" },
  { name: "Pelham", slug: "pelham-ma", county: "Hampshire", isCity: "no" },
  { name: "Pembroke", slug: "pembroke-ma", county: "Plymouth", isCity: "no" },
  { name: "Pepperell", slug: "pepperell-ma", county: "Middlesex", isCity: "no" },
  { name: "Peru", slug: "peru-ma", county: "Berkshire", isCity: "no" },
  { name: "Petersham", slug: "petersham-ma", county: "Worcester", isCity: "no" },
  { name: "Phillipston", slug: "phillipston-ma", county: "Worcester", isCity: "no" },
  { name: "Pittsfield", slug: "pittsfield-ma", county: "Berkshire", isCity: "yes" },
  { name: "Plainfield", slug: "plainfield-ma", county: "Hampshire", isCity: "no" },
  { name: "Plainville", slug: "plainville-ma", county: "Norfolk", isCity: "no" },
  { name: "Plymouth", slug: "plymouth-ma", county: "Plymouth", isCity: "no" },
  { name: "Plympton", slug: "plympton-ma", county: "Plymouth", isCity: "no" },
  { name: "Princeton", slug: "princeton-ma", county: "Worcester", isCity: "no" },
  { name: "Provincetown", slug: "provincetown-ma", county: "Barnstable", isCity: "no" },
  // Q
  { name: "Quincy", slug: "quincy-ma", county: "Norfolk", isCity: "yes" },
  // R
  { name: "Randolph", slug: "randolph-ma", county: "Norfolk", isCity: "no" },
  { name: "Raynham", slug: "raynham-ma", county: "Bristol", isCity: "no" },
  { name: "Reading", slug: "reading-ma", county: "Middlesex", isCity: "no" },
  { name: "Rehoboth", slug: "rehoboth-ma", county: "Bristol", isCity: "no" },
  { name: "Revere", slug: "revere-ma", county: "Suffolk", isCity: "yes" },
  { name: "Richmond", slug: "richmond-ma", county: "Berkshire", isCity: "no" },
  { name: "Rochester", slug: "rochester-ma", county: "Plymouth", isCity: "no" },
  { name: "Rockland", slug: "rockland-ma", county: "Plymouth", isCity: "no" },
  { name: "Rockport", slug: "rockport-ma", county: "Essex", isCity: "no" },
  { name: "Rowe", slug: "rowe-ma", county: "Franklin", isCity: "no" },
  { name: "Rowley", slug: "rowley-ma", county: "Essex", isCity: "no" },
  { name: "Royalston", slug: "royalston-ma", county: "Worcester", isCity: "no" },
  { name: "Russell", slug: "russell-ma", county: "Hampden", isCity: "no" },
  { name: "Rutland", slug: "rutland-ma", county: "Worcester", isCity: "no" },
  // S
  { name: "Salem", slug: "salem-ma", county: "Essex", isCity: "yes" },
  { name: "Salisbury", slug: "salisbury-ma", county: "Essex", isCity: "no" },
  { name: "Sandisfield", slug: "sandisfield-ma", county: "Berkshire", isCity: "no" },
  { name: "Sandwich", slug: "sandwich-ma", county: "Barnstable", isCity: "no" },
  { name: "Saugus", slug: "saugus-ma", county: "Essex", isCity: "no" },
  { name: "Savoy", slug: "savoy-ma", county: "Berkshire", isCity: "no" },
  { name: "Scituate", slug: "scituate-ma", county: "Plymouth", isCity: "no" },
  { name: "Seekonk", slug: "seekonk-ma", county: "Bristol", isCity: "no" },
  { name: "Sharon", slug: "sharon-ma", county: "Norfolk", isCity: "no" },
  { name: "Sheffield", slug: "sheffield-ma", county: "Berkshire", isCity: "no" },
  { name: "Shelburne", slug: "shelburne-ma", county: "Franklin", isCity: "no" },
  { name: "Sherborn", slug: "sherborn-ma", county: "Middlesex", isCity: "no" },
  { name: "Shirley", slug: "shirley-ma", county: "Middlesex", isCity: "no" },
  { name: "Shrewsbury", slug: "shrewsbury-ma", county: "Worcester", isCity: "no" },
  { name: "Shutesbury", slug: "shutesbury-ma", county: "Franklin", isCity: "no" },
  { name: "Somerset", slug: "somerset-ma", county: "Bristol", isCity: "no" },
  { name: "Somerville", slug: "somerville-ma", county: "Middlesex", isCity: "yes" },
  { name: "South Hadley", slug: "south-hadley-ma", county: "Hampshire", isCity: "no" },
  { name: "Southampton", slug: "southampton-ma", county: "Hampshire", isCity: "no" },
  { name: "Southborough", slug: "southborough-ma", county: "Worcester", isCity: "no" },
  { name: "Southbridge", slug: "southbridge-ma", county: "Worcester", isCity: "no" },
  { name: "Southwick", slug: "southwick-ma", county: "Hampden", isCity: "no" },
  { name: "Spencer", slug: "spencer-ma", county: "Worcester", isCity: "no" },
  { name: "Springfield", slug: "springfield-ma", county: "Hampden", isCity: "yes" },
  { name: "Sterling", slug: "sterling-ma", county: "Worcester", isCity: "no" },
  { name: "Stockbridge", slug: "stockbridge-ma", county: "Berkshire", isCity: "no" },
  { name: "Stoneham", slug: "stoneham-ma", county: "Middlesex", isCity: "no" },
  { name: "Stoughton", slug: "stoughton-ma", county: "Norfolk", isCity: "no" },
  { name: "Stow", slug: "stow-ma", county: "Middlesex", isCity: "no" },
  { name: "Sturbridge", slug: "sturbridge-ma", county: "Worcester", isCity: "no" },
  { name: "Sudbury", slug: "sudbury-ma", county: "Middlesex", isCity: "no" },
  { name: "Sunderland", slug: "sunderland-ma", county: "Franklin", isCity: "no" },
  { name: "Sutton", slug: "sutton-ma", county: "Worcester", isCity: "no" },
  { name: "Swampscott", slug: "swampscott-ma", county: "Essex", isCity: "no" },
  { name: "Swansea", slug: "swansea-ma", county: "Bristol", isCity: "no" },
  // T
  { name: "Taunton", slug: "taunton-ma", county: "Bristol", isCity: "yes" },
  { name: "Templeton", slug: "templeton-ma", county: "Worcester", isCity: "no" },
  { name: "Tewksbury", slug: "tewksbury-ma", county: "Middlesex", isCity: "no" },
  { name: "Tisbury", slug: "tisbury-ma", county: "Dukes", isCity: "no" },
  { name: "Tolland", slug: "tolland-ma", county: "Hampden", isCity: "no" },
  { name: "Topsfield", slug: "topsfield-ma", county: "Essex", isCity: "no" },
  { name: "Townsend", slug: "townsend-ma", county: "Middlesex", isCity: "no" },
  { name: "Truro", slug: "truro-ma", county: "Barnstable", isCity: "no" },
  { name: "Tyngsborough", slug: "tyngsborough-ma", county: "Middlesex", isCity: "no" },
  { name: "Tyringham", slug: "tyringham-ma", county: "Berkshire", isCity: "no" },
  // U
  { name: "Upton", slug: "upton-ma", county: "Worcester", isCity: "no" },
  { name: "Uxbridge", slug: "uxbridge-ma", county: "Worcester", isCity: "no" },
  // W
  { name: "Wakefield", slug: "wakefield-ma", county: "Middlesex", isCity: "no" },
  { name: "Wales", slug: "wales-ma", county: "Hampden", isCity: "no" },
  { name: "Walpole", slug: "walpole-ma", county: "Norfolk", isCity: "no" },
  { name: "Waltham", slug: "waltham-ma", county: "Middlesex", isCity: "yes" },
  { name: "Ware", slug: "ware-ma", county: "Hampshire", isCity: "no" },
  { name: "Wareham", slug: "wareham-ma", county: "Plymouth", isCity: "no" },
  { name: "Warren", slug: "warren-ma", county: "Worcester", isCity: "no" },
  { name: "Warwick", slug: "warwick-ma", county: "Franklin", isCity: "no" },
  { name: "Washington", slug: "washington-ma", county: "Berkshire", isCity: "no" },
  { name: "Watertown", slug: "watertown-ma", county: "Middlesex", isCity: "no" },
  { name: "Wayland", slug: "wayland-ma", county: "Middlesex", isCity: "no" },
  { name: "Webster", slug: "webster-ma", county: "Worcester", isCity: "no" },
  { name: "Wellesley", slug: "wellesley-ma", county: "Norfolk", isCity: "no" },
  { name: "Wellfleet", slug: "wellfleet-ma", county: "Barnstable", isCity: "no" },
  { name: "Wendell", slug: "wendell-ma", county: "Franklin", isCity: "no" },
  { name: "Wenham", slug: "wenham-ma", county: "Essex", isCity: "no" },
  { name: "West Boylston", slug: "west-boylston-ma", county: "Worcester", isCity: "no" },
  { name: "West Bridgewater", slug: "west-bridgewater-ma", county: "Plymouth", isCity: "no" },
  { name: "West Brookfield", slug: "west-brookfield-ma", county: "Worcester", isCity: "no" },
  { name: "West Newbury", slug: "west-newbury-ma", county: "Essex", isCity: "no" },
  { name: "West Springfield", slug: "west-springfield-ma", county: "Hampden", isCity: "no" },
  { name: "West Stockbridge", slug: "west-stockbridge-ma", county: "Berkshire", isCity: "no" },
  { name: "West Tisbury", slug: "west-tisbury-ma", county: "Dukes", isCity: "no" },
  { name: "Westborough", slug: "westborough-ma", county: "Worcester", isCity: "no" },
  { name: "Westfield", slug: "westfield-ma", county: "Hampden", isCity: "yes" },
  { name: "Westford", slug: "westford-ma", county: "Middlesex", isCity: "no" },
  { name: "Westhampton", slug: "westhampton-ma", county: "Hampshire", isCity: "no" },
  { name: "Westminster", slug: "westminster-ma", county: "Worcester", isCity: "no" },
  { name: "Weston", slug: "weston-ma", county: "Middlesex", isCity: "no" },
  { name: "Westport", slug: "westport-ma", county: "Bristol", isCity: "no" },
  { name: "Westwood", slug: "westwood-ma", county: "Norfolk", isCity: "no" },
  { name: "Weymouth", slug: "weymouth-ma", county: "Norfolk", isCity: "no" },
  { name: "Whately", slug: "whately-ma", county: "Franklin", isCity: "no" },
  { name: "Whitman", slug: "whitman-ma", county: "Plymouth", isCity: "no" },
  { name: "Wilbraham", slug: "wilbraham-ma", county: "Hampden", isCity: "no" },
  { name: "Williamsburg", slug: "williamsburg-ma", county: "Hampshire", isCity: "no" },
  { name: "Williamstown", slug: "williamstown-ma", county: "Berkshire", isCity: "no" },
  { name: "Wilmington", slug: "wilmington-ma", county: "Middlesex", isCity: "no" },
  { name: "Winchendon", slug: "winchendon-ma", county: "Worcester", isCity: "no" },
  { name: "Winchester", slug: "winchester-ma", county: "Middlesex", isCity: "no" },
  { name: "Windsor", slug: "windsor-ma", county: "Berkshire", isCity: "no" },
  { name: "Winthrop", slug: "winthrop-ma", county: "Suffolk", isCity: "no" },
  { name: "Woburn", slug: "woburn-ma", county: "Middlesex", isCity: "yes" },
  { name: "Worcester", slug: "worcester-ma", county: "Worcester", isCity: "yes" },
  { name: "Worthington", slug: "worthington-ma", county: "Hampshire", isCity: "no" },
  { name: "Wrentham", slug: "wrentham-ma", county: "Norfolk", isCity: "no" },
  // Y
  { name: "Yarmouth", slug: "yarmouth-ma", county: "Barnstable", isCity: "no" },
];

// Service types for filtering
export const defaultServiceTypes = [
  // Care Type Services
  { name: "Home Care", slug: "home-care", category: "care-type", description: "Professional in-home care services", sortOrder: 1 },
  { name: "Memory Care", slug: "memory-care", category: "care-type", description: "Specialized care for Alzheimer's and dementia", sortOrder: 2 },
  { name: "Assisted Living", slug: "assisted-living", category: "care-type", description: "Residential care with daily living assistance", sortOrder: 3 },
  { name: "Nursing Homes", slug: "nursing-homes", category: "care-type", description: "Skilled nursing and long-term care facilities", sortOrder: 4 },
  
  // Service Filters
  { name: "Dementia/Alzheimer's Support", slug: "dementia-support", category: "service", description: "Specialized memory care support", sortOrder: 10 },
  { name: "24-Hour Care", slug: "24-hour-care", category: "service", description: "Round-the-clock care services", sortOrder: 11 },
  { name: "Live-In Care", slug: "live-in-care", category: "service", description: "Caregiver resides in the home", sortOrder: 12 },
  { name: "Companion Care", slug: "companion-care", category: "service", description: "Social engagement and companionship", sortOrder: 13 },
  { name: "Skilled Nursing", slug: "skilled-nursing", category: "service", description: "Medical care by licensed nurses", sortOrder: 14 },
  { name: "Respite Care", slug: "respite-care", category: "service", description: "Temporary relief for family caregivers", sortOrder: 15 },
  { name: "Personal Care", slug: "personal-care", category: "service", description: "Assistance with daily living activities", sortOrder: 16 },
  { name: "Homemaking", slug: "homemaking", category: "service", description: "Light housekeeping and meal prep", sortOrder: 17 },
  { name: "Transportation", slug: "transportation", category: "service", description: "Escort to appointments and errands", sortOrder: 18 },
  { name: "Medication Reminders", slug: "medication-reminders", category: "service", description: "Help managing medications", sortOrder: 19 },
  
  // Administrative Filters
  { name: "Accepts Insurance", slug: "accepts-insurance", category: "administrative", description: "Accepts various insurance plans", sortOrder: 20 },
  { name: "Private Pay", slug: "private-pay", category: "administrative", description: "Private payment options available", sortOrder: 21 },
  { name: "Medicaid Accepted", slug: "medicaid-accepted", category: "administrative", description: "Accepts Medicaid coverage", sortOrder: 22 },
  { name: "Medicare Accepted", slug: "medicare-accepted", category: "administrative", description: "Accepts Medicare coverage", sortOrder: 23 },
];

// Default FAQs template for each care type
export const defaultFaqsByCarreType = {
  "home-care": [
    { question: "What home care services are available in {city}?", answer: "Private In-Home Caregiver offers comprehensive home care services in {city}, including personal care assistance, companion care, homemaking services, medication reminders, and transportation to appointments." },
    { question: "How much does home care cost in {city}, Massachusetts?", answer: "Home care costs in {city} vary based on the level of care needed and hours required. Contact us for a free consultation and personalized care assessment to discuss your specific needs and budget." },
    { question: "Are your {city} caregivers background checked?", answer: "Yes, all our caregivers serving {city} undergo comprehensive background checks, including criminal history, reference verification, and credential validation to ensure your loved one's safety." },
    { question: "Can I schedule a home care consultation in {city}?", answer: "Absolutely! We offer free in-home consultations throughout {city} and {county} County. Our care coordinator will assess your needs and create a customized care plan." },
    { question: "Do you provide 24-hour home care in {city}?", answer: "Yes, we provide 24-hour home care services in {city}, including live-in care and around-the-clock shift coverage to meet your family's needs." },
  ],
  "memory-care": [
    { question: "What memory care services do you offer in {city}?", answer: "In {city}, we provide specialized memory care including Alzheimer's and dementia support, cognitive stimulation activities, safety supervision, and personalized care plans designed for memory impairment." },
    { question: "How do you train caregivers for memory care in {city}?", answer: "Our {city} memory care specialists receive specialized training in dementia care techniques, communication strategies, behavior management, and creating safe, engaging environments." },
    { question: "Can you help with early-stage dementia in {city}?", answer: "Yes, we support all stages of dementia in {city}, from early cognitive changes to advanced memory care, adapting our approach as needs evolve." },
    { question: "Do you offer respite care for dementia caregivers in {city}?", answer: "Absolutely! We understand caregiver burnout. Our {city} team provides respite care so family caregivers can rest while their loved one receives quality memory care." },
    { question: "What makes your memory care different in {city}?", answer: "Our {city} memory care focuses on person-centered approaches, maintaining dignity, engaging activities, and consistent caregiver matching to build trust and comfort." },
  ],
  "assisted-living": [
    { question: "What assisted living options are available in {city}?", answer: "We help families in {city} find quality assisted living communities that match their needs, budget, and location preferences throughout {county} County." },
    { question: "How do I choose an assisted living facility in {city}?", answer: "Our {city} care advisors provide free consultations to help you evaluate assisted living options based on care needs, amenities, location, and cost considerations." },
    { question: "What's the cost of assisted living in {city}, MA?", answer: "Assisted living costs in {city} vary by community and level of care. Contact us for a free assessment and guidance on finding options within your budget." },
    { question: "Can you help transition from home care to assisted living in {city}?", answer: "Yes, we support families through the transition process, helping find the right {city} community and coordinating care during the move." },
    { question: "Do assisted living facilities in {city} accept Medicaid?", answer: "Some {city} assisted living communities accept Medicaid through state programs. We can help identify facilities that match your financial situation." },
  ],
  "nursing-homes": [
    { question: "What nursing home services are available in {city}?", answer: "Nursing homes in {city} provide skilled nursing care, rehabilitation services, long-term care, and specialized programs for various medical conditions." },
    { question: "How do I find a quality nursing home in {city}?", answer: "We help families evaluate nursing homes in {city} based on quality ratings, staff-to-patient ratios, specialized care programs, and Medicare/Medicaid certification." },
    { question: "What's the difference between nursing homes and assisted living in {city}?", answer: "Nursing homes in {city} provide 24-hour skilled nursing care for complex medical needs, while assisted living focuses on daily living assistance with less intensive medical care." },
    { question: "Does Medicare cover nursing home care in {city}?", answer: "Medicare covers short-term skilled nursing care in {city} following a hospital stay. For long-term care, Medicaid or private pay options may apply." },
    { question: "Can you help with nursing home placement in {city}?", answer: "Yes, our {city} care advisors assist families with nursing home placement, helping navigate the selection process and admission requirements." },
  ],
};

// Generate content templates for each care type
export const generateCareTypeContent = (cityName: string, county: string, careType: string) => {
  const careTypeLabels: Record<string, string> = {
    "home-care": "Home Care",
    "memory-care": "Memory Care",
    "assisted-living": "Assisted Living",
    "nursing-homes": "Nursing Homes",
  };
  
  const label = careTypeLabels[careType] || careType;
  
  return {
    metaTitle: `${label} Services in ${cityName}, MA | Private In-Home Caregiver`,
    metaDescription: `Find trusted ${label.toLowerCase()} services in ${cityName}, Massachusetts. Private In-Home Caregiver offers compassionate, professional care for seniors and families in ${county} County.`,
    heroTitle: `${label} in ${cityName}, Massachusetts`,
    heroSubtitle: `Compassionate, professional ${label.toLowerCase()} services for your loved ones in ${cityName} and throughout ${county} County`,
    overviewContent: `Private In-Home Caregiver provides exceptional ${label.toLowerCase()} services in ${cityName}, MA. Our experienced caregivers are dedicated to helping seniors and individuals with care needs maintain their independence and quality of life. Whether you need assistance for a few hours a week or around-the-clock care, we're here to help families in ${cityName} and the greater ${county} County area.`,
    whyChooseUsContent: `Choosing Private In-Home Caregiver for ${label.toLowerCase()} in ${cityName} means partnering with a team that truly cares. Our caregivers are carefully screened, thoroughly trained, and matched to each client's unique needs and personality. We've been serving families across Massachusetts with dedication and compassion, building lasting relationships based on trust and exceptional care.`,
    servicesHighlights: [
      "Personalized care plans tailored to individual needs",
      "Carefully screened and trained caregivers",
      "Flexible scheduling including 24-hour care",
      "Regular care coordination and family communication",
      "Local expertise in " + cityName + " and " + county + " County",
    ],
    keywords: [
      `${label.toLowerCase()} ${cityName}`,
      `${cityName} ${label.toLowerCase()} services`,
      `senior care ${cityName} MA`,
      `${county} County ${label.toLowerCase()}`,
      `Massachusetts ${label.toLowerCase()}`,
    ],
  };
};
