function slugify(text: string): string {
  return text
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/(^-|-$)/g, '');
}

export const hospitalSeedData = [
  {
    name: "Massachusetts General Hospital",
    slug: slugify("massachusetts-general-hospital-boston"),
    facilityType: "hospital",
    address: "55 Fruit Street",
    city: "Boston",
    state: "MA",
    zipCode: "02114",
    county: "Suffolk",
    phone: "(617) 726-2000",
    website: "https://www.massgeneral.org",
    description: "Massachusetts General Hospital (Mass General or MGH) is the original and largest teaching hospital of Harvard Medical School. Founded in 1811, it is the third-oldest general hospital in the United States and is consistently ranked among the best hospitals in the nation. The hospital is a Level I Trauma Center and offers comprehensive services including cardiac care, oncology, neurology, and organ transplantation.",
    shortDescription: "Harvard-affiliated academic medical center and Level I Trauma Center, consistently ranked among America's best hospitals.",
    services: ["Emergency Services", "Level I Trauma Center", "Cardiac Surgery", "Cancer Treatment", "Neurosurgery", "Organ Transplant", "Pediatrics", "Psychiatric Services", "Rehabilitation", "Women's Health"],
    specializations: ["Trauma Center", "Cardiac Care", "Oncology", "Neurology", "Transplant Surgery"],
    amenities: ["Parking Garage", "Cafeteria", "Chapel", "Gift Shop", "ATM", "Pharmacy", "Interpreter Services", "WiFi"],
    acceptsMedicare: "yes",
    acceptsMedicaid: "yes",
    totalBeds: 999,
    overallRating: "4.8",
    
    status: "published",
    featured: "yes",
    sortOrder: 1
  },
  {
    name: "Brigham and Women's Hospital",
    slug: slugify("brigham-and-womens-hospital-boston"),
    facilityType: "hospital",
    address: "75 Francis Street",
    city: "Boston",
    state: "MA",
    zipCode: "02115",
    county: "Suffolk",
    phone: "(617) 732-5500",
    website: "https://www.brighamandwomens.org",
    description: "Brigham and Women's Hospital is a teaching affiliate of Harvard Medical School and a founding member of Mass General Brigham. It is internationally renowned for excellence in patient care, groundbreaking biomedical research, and training the next generation of leaders in medicine. The hospital is particularly known for its expertise in cardiovascular disease, cancer, and women's health.",
    shortDescription: "Harvard-affiliated academic medical center known for cardiac care, oncology, and women's health services.",
    services: ["Emergency Services", "Cardiac Surgery", "Cancer Treatment", "Women's Health", "Organ Transplant", "Neurosurgery", "Orthopedics", "Rehabilitation"],
    specializations: ["Cardiac Care", "Oncology", "Women's Health", "Transplant Surgery"],
    amenities: ["Parking", "Cafeteria", "Chapel", "Gift Shop", "Pharmacy", "WiFi"],
    acceptsMedicare: "yes",
    acceptsMedicaid: "yes",
    totalBeds: 793,
    overallRating: "4.7",
    
    status: "published",
    featured: "yes",
    sortOrder: 2
  },
  {
    name: "Beth Israel Deaconess Medical Center",
    slug: slugify("beth-israel-deaconess-medical-center-boston"),
    facilityType: "hospital",
    address: "330 Brookline Avenue",
    city: "Boston",
    state: "MA",
    zipCode: "02215",
    county: "Suffolk",
    phone: "(617) 667-7000",
    website: "https://www.bidmc.org",
    description: "Beth Israel Deaconess Medical Center (BIDMC) is a teaching hospital of Harvard Medical School and a research partner of the Dana-Farber/Harvard Cancer Center. The hospital offers comprehensive medical, surgical, obstetric, and psychiatric services and is nationally recognized for its expertise in cardiac care, gastroenterology, and oncology.",
    shortDescription: "Harvard-affiliated teaching hospital with expertise in cardiac care, gastroenterology, and cancer treatment.",
    services: ["Emergency Services", "Cardiac Surgery", "Cancer Treatment", "Gastroenterology", "Orthopedics", "Obstetrics", "Psychiatric Services"],
    specializations: ["Cardiac Care", "Gastroenterology", "Oncology"],
    amenities: ["Parking", "Cafeteria", "Chapel", "Pharmacy", "WiFi"],
    acceptsMedicare: "yes",
    acceptsMedicaid: "yes",
    totalBeds: 673,
    overallRating: "4.6",
    
    status: "published",
    sortOrder: 3
  },
  {
    name: "Boston Medical Center",
    slug: slugify("boston-medical-center-boston"),
    facilityType: "hospital",
    address: "1 Boston Medical Center Place",
    city: "Boston",
    state: "MA",
    zipCode: "02118",
    county: "Suffolk",
    phone: "(617) 638-8000",
    website: "https://www.bmc.org",
    description: "Boston Medical Center is the largest safety-net hospital and busiest trauma and emergency services center in New England. As the primary teaching affiliate of Boston University Chobanian & Avedisian School of Medicine, BMC combines excellence in clinical care with groundbreaking research and training. The hospital is committed to providing exceptional care without exception.",
    shortDescription: "New England's largest safety-net hospital and Level I Trauma Center, providing exceptional care to all.",
    services: ["Emergency Services", "Level I Trauma Center", "Pediatrics", "Cancer Treatment", "Cardiac Care", "Obstetrics", "Psychiatric Services"],
    specializations: ["Trauma Center", "Pediatrics", "Safety-Net Care"],
    amenities: ["Parking", "Cafeteria", "Chapel", "Pharmacy", "Interpreter Services", "WiFi"],
    acceptsMedicare: "yes",
    acceptsMedicaid: "yes",
    totalBeds: 514,
    overallRating: "4.5",
    
    status: "published",
    sortOrder: 4
  },
  {
    name: "Boston Children's Hospital",
    slug: slugify("boston-childrens-hospital-boston"),
    facilityType: "hospital",
    address: "300 Longwood Avenue",
    city: "Boston",
    state: "MA",
    zipCode: "02115",
    county: "Suffolk",
    phone: "(617) 355-6000",
    website: "https://www.childrenshospital.org",
    description: "Boston Children's Hospital is the primary pediatric teaching hospital of Harvard Medical School and is consistently ranked as the #1 children's hospital in the nation. Founded in 1869, it is one of the largest pediatric medical centers in the United States, offering the full range of health care services for children from birth through age 21.",
    shortDescription: "America's #1 ranked children's hospital, providing comprehensive pediatric care and groundbreaking research.",
    services: ["Pediatric Emergency", "Pediatric Surgery", "Pediatric Oncology", "Cardiac Surgery", "Neurosurgery", "Orthopedics", "Transplant Services"],
    specializations: ["Pediatric Specialties", "Pediatric Oncology", "Pediatric Cardiology", "Pediatric Neurology"],
    amenities: ["Parking", "Cafeteria", "Family Lounges", "Gift Shop", "Pharmacy", "WiFi", "Play Areas"],
    acceptsMedicare: "yes",
    acceptsMedicaid: "yes",
    totalBeds: 485,
    overallRating: "4.9",
    
    status: "published",
    featured: "yes",
    sortOrder: 5
  },
  {
    name: "Tufts Medical Center",
    slug: slugify("tufts-medical-center-boston"),
    facilityType: "hospital",
    address: "800 Washington Street",
    city: "Boston",
    state: "MA",
    zipCode: "02111",
    county: "Suffolk",
    phone: "(617) 636-5000",
    website: "https://www.tuftsmedicalcenter.org",
    description: "Tufts Medical Center is the principal teaching hospital for Tufts University School of Medicine. Located in downtown Boston, it provides comprehensive adult and pediatric care with particular expertise in cardiac care, cancer treatment, and the Floating Hospital for Children.",
    shortDescription: "Downtown Boston academic medical center with the renowned Floating Hospital for Children.",
    services: ["Emergency Services", "Cardiac Surgery", "Cancer Treatment", "Pediatrics", "Orthopedics", "Neurology"],
    specializations: ["Cardiac Care", "Oncology", "Pediatrics"],
    amenities: ["Parking", "Cafeteria", "Chapel", "Pharmacy", "WiFi"],
    acceptsMedicare: "yes",
    acceptsMedicaid: "yes",
    totalBeds: 415,
    overallRating: "4.4",
    
    status: "published",
    sortOrder: 6
  },
  {
    name: "Dana-Farber Cancer Institute",
    slug: slugify("dana-farber-cancer-institute-boston"),
    facilityType: "hospital",
    address: "450 Brookline Avenue",
    city: "Boston",
    state: "MA",
    zipCode: "02215",
    county: "Suffolk",
    phone: "(617) 632-3000",
    website: "https://www.dana-farber.org",
    description: "Dana-Farber Cancer Institute is one of the world's leading centers for cancer research and treatment. As a teaching affiliate of Harvard Medical School, Dana-Farber provides expert, compassionate care to adults and children with cancer while advancing the understanding, diagnosis, treatment, cure, and prevention of cancer.",
    shortDescription: "World-renowned cancer research and treatment center, a Harvard Medical School teaching affiliate.",
    services: ["Cancer Treatment", "Chemotherapy", "Radiation Therapy", "Clinical Trials", "Pediatric Oncology", "Genetic Testing"],
    specializations: ["Oncology", "Cancer Research", "Pediatric Oncology"],
    amenities: ["Parking", "Cafeteria", "Support Services", "Pharmacy", "WiFi"],
    acceptsMedicare: "yes",
    acceptsMedicaid: "yes",
    totalBeds: 30,
    overallRating: "4.9",
    
    status: "published",
    featured: "yes",
    sortOrder: 7
  },
  {
    name: "New England Baptist Hospital",
    slug: slugify("new-england-baptist-hospital-boston"),
    facilityType: "hospital",
    address: "125 Parker Hill Avenue",
    city: "Boston",
    state: "MA",
    zipCode: "02120",
    county: "Suffolk",
    phone: "(617) 754-5800",
    website: "https://www.nebh.org",
    description: "New England Baptist Hospital is internationally recognized as a leader in orthopedic surgery and care. The hospital provides comprehensive orthopedic services including joint replacement, sports medicine, spine surgery, and rehabilitation.",
    shortDescription: "Internationally recognized orthopedic specialty hospital with expertise in joint replacement and sports medicine.",
    services: ["Orthopedic Surgery", "Joint Replacement", "Sports Medicine", "Spine Surgery", "Physical Therapy", "Rehabilitation"],
    specializations: ["Orthopedics", "Joint Replacement", "Sports Medicine"],
    amenities: ["Parking", "Cafeteria", "Pharmacy", "WiFi"],
    acceptsMedicare: "yes",
    acceptsMedicaid: "yes",
    totalBeds: 118,
    overallRating: "4.7",
    
    status: "published",
    sortOrder: 8
  },
  {
    name: "Spaulding Rehabilitation Hospital",
    slug: slugify("spaulding-rehabilitation-hospital-charlestown"),
    facilityType: "hospital",
    address: "300 First Avenue",
    city: "Charlestown",
    state: "MA",
    zipCode: "02129",
    county: "Suffolk",
    phone: "(617) 573-7000",
    website: "https://www.spauldingrehab.org",
    description: "Spaulding Rehabilitation Hospital is the official teaching hospital of Harvard Medical School for physical medicine and rehabilitation. Consistently ranked among the best rehabilitation hospitals in the nation, Spaulding provides comprehensive inpatient and outpatient rehabilitation services.",
    shortDescription: "Harvard-affiliated rehabilitation hospital, nationally ranked for physical medicine and rehabilitation.",
    services: ["Inpatient Rehabilitation", "Outpatient Rehabilitation", "Brain Injury Program", "Spinal Cord Injury Program", "Stroke Rehabilitation", "Orthopedic Rehabilitation"],
    specializations: ["Rehabilitation", "Brain Injury", "Spinal Cord Injury"],
    amenities: ["Parking", "Cafeteria", "Therapy Gym", "WiFi"],
    acceptsMedicare: "yes",
    acceptsMedicaid: "yes",
    totalBeds: 132,
    overallRating: "4.8",
    
    status: "published",
    sortOrder: 9
  },
  {
    name: "Mount Auburn Hospital",
    slug: slugify("mount-auburn-hospital-cambridge"),
    facilityType: "hospital",
    address: "330 Mount Auburn Street",
    city: "Cambridge",
    state: "MA",
    zipCode: "02138",
    county: "Middlesex",
    phone: "(617) 492-3500",
    website: "https://www.mountauburnhospital.org",
    description: "Mount Auburn Hospital is a Harvard Medical School teaching hospital providing comprehensive medical care to the Cambridge community and surrounding areas. The hospital offers a full range of inpatient and outpatient services with a focus on personalized, patient-centered care.",
    shortDescription: "Harvard-affiliated community hospital serving Cambridge with comprehensive medical services.",
    services: ["Emergency Services", "Surgery", "Cardiac Care", "Obstetrics", "Orthopedics", "Cancer Services"],
    specializations: ["Community Medicine", "Primary Care"],
    amenities: ["Parking", "Cafeteria", "Chapel", "Pharmacy", "WiFi"],
    acceptsMedicare: "yes",
    acceptsMedicaid: "yes",
    totalBeds: 210,
    overallRating: "4.5",
    
    status: "published",
    sortOrder: 10
  },
  {
    name: "Cambridge Health Alliance - Cambridge Hospital",
    slug: slugify("cambridge-health-alliance-cambridge-hospital"),
    facilityType: "hospital",
    address: "1493 Cambridge Street",
    city: "Cambridge",
    state: "MA",
    zipCode: "02139",
    county: "Middlesex",
    phone: "(617) 665-1000",
    description: "Cambridge Health Alliance is an academic community health system committed to providing high-quality, culturally competent care to a diverse population. As a teaching affiliate of Harvard Medical School, the hospital combines excellent clinical care with training and research.",
    shortDescription: "Academic community health system providing culturally competent care to diverse populations.",
    services: ["Emergency Services", "Primary Care", "Surgery", "Obstetrics", "Psychiatric Services", "Community Health"],
    specializations: ["Community Health", "Cultural Competence"],
    amenities: ["Parking", "Cafeteria", "Interpreter Services", "WiFi"],
    acceptsMedicare: "yes",
    acceptsMedicaid: "yes",
    totalBeds: 119,
    overallRating: "4.3",
    
    status: "published",
    sortOrder: 11
  },
  {
    name: "Lahey Hospital & Medical Center",
    slug: slugify("lahey-hospital-medical-center-burlington"),
    facilityType: "hospital",
    address: "41 Mall Road",
    city: "Burlington",
    state: "MA",
    zipCode: "01805",
    county: "Middlesex",
    phone: "(781) 744-5100",
    website: "https://www.lahey.org",
    description: "Lahey Hospital & Medical Center is a physician-led, nonprofit teaching hospital that is part of Beth Israel Lahey Health. The hospital is known for its expertise in complex medical and surgical care, particularly in cardiac surgery, oncology, and gastrointestinal disorders.",
    shortDescription: "Physician-led teaching hospital known for complex medical and surgical care excellence.",
    services: ["Emergency Services", "Cardiac Surgery", "Cancer Treatment", "Gastroenterology", "Neurosurgery", "Orthopedics"],
    specializations: ["Cardiac Care", "Oncology", "Gastroenterology"],
    amenities: ["Parking", "Cafeteria", "Chapel", "Pharmacy", "WiFi"],
    acceptsMedicare: "yes",
    acceptsMedicaid: "yes",
    totalBeds: 345,
    overallRating: "4.6",
    
    status: "published",
    featured: "yes",
    sortOrder: 12
  },
  {
    name: "Newton-Wellesley Hospital",
    slug: slugify("newton-wellesley-hospital-newton"),
    facilityType: "hospital",
    address: "2014 Washington Street",
    city: "Newton",
    state: "MA",
    zipCode: "02462",
    county: "Middlesex",
    phone: "(617) 243-6000",
    website: "https://www.nwh.org",
    description: "Newton-Wellesley Hospital is a community hospital affiliated with Mass General Brigham. The hospital provides comprehensive medical services including emergency care, surgery, cardiac services, and one of the busiest maternity programs in the state.",
    shortDescription: "Mass General Brigham community hospital with one of Massachusetts' busiest maternity programs.",
    services: ["Emergency Services", "Surgery", "Cardiac Care", "Maternity Services", "Orthopedics", "Cancer Services"],
    specializations: ["Maternity Care", "Community Medicine"],
    amenities: ["Parking", "Cafeteria", "Chapel", "Gift Shop", "Pharmacy", "WiFi"],
    acceptsMedicare: "yes",
    acceptsMedicaid: "yes",
    totalBeds: 273,
    overallRating: "4.5",
    
    status: "published",
    sortOrder: 13
  },
  {
    name: "Melrose-Wakefield Hospital",
    slug: slugify("melrose-wakefield-hospital-melrose"),
    facilityType: "hospital",
    address: "585 Lebanon Street",
    city: "Melrose",
    state: "MA",
    zipCode: "02176",
    county: "Middlesex",
    phone: "(781) 979-3000",
    description: "Melrose-Wakefield Hospital, part of MelroseWakefield Healthcare and Tufts Medicine, is a full-service community hospital providing comprehensive medical care to the communities north of Boston.",
    shortDescription: "Full-service community hospital serving communities north of Boston.",
    services: ["Emergency Services", "Surgery", "Cardiac Care", "Orthopedics", "Women's Health"],
    specializations: ["Community Medicine"],
    amenities: ["Parking", "Cafeteria", "Pharmacy", "WiFi"],
    acceptsMedicare: "yes",
    acceptsMedicaid: "yes",
    totalBeds: 161,
    overallRating: "4.3",
    
    status: "published",
    sortOrder: 14
  },
  {
    name: "Lowell General Hospital",
    slug: slugify("lowell-general-hospital-lowell"),
    facilityType: "hospital",
    address: "295 Varnum Avenue",
    city: "Lowell",
    state: "MA",
    zipCode: "01854",
    county: "Middlesex",
    phone: "(978) 937-6000",
    website: "https://www.lowellgeneral.org",
    description: "Lowell General Hospital is a community hospital providing comprehensive medical services to the Greater Lowell area. The hospital offers a wide range of services including emergency care, surgical services, cancer treatment, and cardiac care.",
    shortDescription: "Community hospital serving Greater Lowell with comprehensive medical services.",
    services: ["Emergency Services", "Surgery", "Cancer Treatment", "Cardiac Care", "Orthopedics", "Women's Health"],
    specializations: ["Community Medicine"],
    amenities: ["Parking", "Cafeteria", "Chapel", "Pharmacy", "WiFi"],
    acceptsMedicare: "yes",
    acceptsMedicaid: "yes",
    totalBeds: 217,
    overallRating: "4.4",
    
    status: "published",
    sortOrder: 15
  },
  {
    name: "Emerson Hospital",
    slug: slugify("emerson-hospital-concord"),
    facilityType: "hospital",
    address: "133 Old Road to Nine Acre Corner",
    city: "Concord",
    state: "MA",
    zipCode: "01742",
    county: "Middlesex",
    phone: "(978) 369-1400",
    website: "https://www.emersonhospital.org",
    description: "Emerson Hospital is a 179-bed community hospital serving the residents of Concord and surrounding communities. The hospital provides comprehensive medical services with a focus on patient-centered care and community wellness.",
    shortDescription: "Community hospital in historic Concord focused on patient-centered care.",
    services: ["Emergency Services", "Surgery", "Cardiac Care", "Orthopedics", "Women's Health", "Rehabilitation"],
    specializations: ["Community Medicine"],
    amenities: ["Parking", "Cafeteria", "Chapel", "Pharmacy", "WiFi"],
    acceptsMedicare: "yes",
    acceptsMedicaid: "yes",
    totalBeds: 179,
    overallRating: "4.5",
    
    status: "published",
    sortOrder: 16
  },
  {
    name: "MetroWest Medical Center - Framingham",
    slug: slugify("metrowest-medical-center-framingham"),
    facilityType: "hospital",
    address: "115 Lincoln Street",
    city: "Framingham",
    state: "MA",
    zipCode: "01702",
    county: "Middlesex",
    phone: "(508) 383-1000",
    description: "MetroWest Medical Center in Framingham is a full-service community hospital providing comprehensive medical care to the MetroWest region. The hospital offers emergency services, surgical care, and a range of specialty services.",
    shortDescription: "Full-service community hospital serving the MetroWest region.",
    services: ["Emergency Services", "Surgery", "Cardiac Care", "Orthopedics", "Women's Health"],
    specializations: ["Community Medicine"],
    amenities: ["Parking", "Cafeteria", "Pharmacy", "WiFi"],
    acceptsMedicare: "yes",
    acceptsMedicaid: "yes",
    totalBeds: 155,
    overallRating: "4.2",
    
    status: "published",
    sortOrder: 17
  },
  {
    name: "Marlborough Hospital",
    slug: slugify("marlborough-hospital-marlborough"),
    facilityType: "hospital",
    address: "157 Union Street",
    city: "Marlborough",
    state: "MA",
    zipCode: "01752",
    county: "Middlesex",
    phone: "(508) 481-5000",
    description: "Marlborough Hospital is a community hospital providing comprehensive medical services to Marlborough and surrounding communities. Part of UMass Memorial Health, the hospital offers emergency care, surgical services, and specialty care.",
    shortDescription: "UMass Memorial community hospital serving Marlborough and surrounding areas.",
    services: ["Emergency Services", "Surgery", "Cardiac Care", "Orthopedics"],
    specializations: ["Community Medicine"],
    amenities: ["Parking", "Cafeteria", "Pharmacy", "WiFi"],
    acceptsMedicare: "yes",
    acceptsMedicaid: "yes",
    totalBeds: 67,
    overallRating: "4.3",
    
    status: "published",
    sortOrder: 18
  },
  {
    name: "UMass Memorial Medical Center - University Campus",
    slug: slugify("umass-memorial-medical-center-university-campus-worcester"),
    facilityType: "hospital",
    address: "55 Lake Avenue North",
    city: "Worcester",
    state: "MA",
    zipCode: "01655",
    county: "Worcester",
    phone: "(508) 334-1000",
    website: "https://www.umassmemorial.org",
    description: "UMass Memorial Medical Center is the clinical partner of UMass Chan Medical School and Central New England's only Level I Trauma Center. The University Campus is home to many of the medical center's specialty services and research programs.",
    shortDescription: "Central New England's only Level I Trauma Center and UMass Chan Medical School teaching hospital.",
    services: ["Emergency Services", "Level I Trauma Center", "Cardiac Surgery", "Cancer Treatment", "Neurosurgery", "Transplant Services"],
    specializations: ["Trauma Center", "Cardiac Care", "Academic Medicine"],
    amenities: ["Parking", "Cafeteria", "Chapel", "Pharmacy", "WiFi"],
    acceptsMedicare: "yes",
    acceptsMedicaid: "yes",
    totalBeds: 781,
    overallRating: "4.5",
    
    status: "published",
    featured: "yes",
    sortOrder: 19
  },
  {
    name: "UMass Memorial Medical Center - Memorial Campus",
    slug: slugify("umass-memorial-medical-center-memorial-campus-worcester"),
    facilityType: "hospital",
    address: "119 Belmont Street",
    city: "Worcester",
    state: "MA",
    zipCode: "01605",
    county: "Worcester",
    phone: "(508) 334-1000",
    description: "The Memorial Campus of UMass Memorial Medical Center provides comprehensive medical services including emergency care, maternity services, and specialty care. The campus features the region's only dedicated children's medical center.",
    shortDescription: "UMass Memorial campus featuring the region's only dedicated children's medical center.",
    services: ["Emergency Services", "Surgery", "Maternity Services", "Pediatrics", "Orthopedics"],
    specializations: ["Pediatrics", "Maternity Care"],
    amenities: ["Parking", "Cafeteria", "Chapel", "Pharmacy", "WiFi"],
    acceptsMedicare: "yes",
    acceptsMedicaid: "yes",
    totalBeds: 321,
    overallRating: "4.4",
    
    status: "published",
    sortOrder: 20
  },
  {
    name: "Saint Vincent Hospital",
    slug: slugify("saint-vincent-hospital-worcester"),
    facilityType: "hospital",
    address: "123 Summer Street",
    city: "Worcester",
    state: "MA",
    zipCode: "01608",
    county: "Worcester",
    phone: "(508) 363-5000",
    description: "Saint Vincent Hospital is a community hospital in Worcester providing comprehensive medical services. The hospital offers emergency care, surgical services, cardiac care, and a range of specialty services.",
    shortDescription: "Worcester community hospital providing comprehensive medical services.",
    services: ["Emergency Services", "Surgery", "Cardiac Care", "Orthopedics", "Cancer Services"],
    specializations: ["Community Medicine"],
    amenities: ["Parking", "Cafeteria", "Chapel", "Pharmacy", "WiFi"],
    acceptsMedicare: "yes",
    acceptsMedicaid: "yes",
    totalBeds: 321,
    overallRating: "4.2",
    
    status: "published",
    sortOrder: 21
  },
  {
    name: "Harrington Hospital",
    slug: slugify("harrington-hospital-southbridge"),
    facilityType: "hospital",
    address: "100 South Street",
    city: "Southbridge",
    state: "MA",
    zipCode: "01550",
    county: "Worcester",
    phone: "(508) 765-9771",
    description: "Harrington Hospital is a community hospital serving South Central Massachusetts. Part of UMass Memorial Health, the hospital provides emergency services, surgical care, and comprehensive medical services.",
    shortDescription: "UMass Memorial community hospital serving South Central Massachusetts.",
    services: ["Emergency Services", "Surgery", "Orthopedics", "Primary Care"],
    specializations: ["Community Medicine"],
    amenities: ["Parking", "Cafeteria", "Pharmacy", "WiFi"],
    acceptsMedicare: "yes",
    acceptsMedicaid: "yes",
    totalBeds: 114,
    overallRating: "4.1",
    
    status: "published",
    sortOrder: 22
  },
  {
    name: "Heywood Hospital",
    slug: slugify("heywood-hospital-gardner"),
    facilityType: "hospital",
    address: "242 Green Street",
    city: "Gardner",
    state: "MA",
    zipCode: "01440",
    county: "Worcester",
    phone: "(978) 632-3420",
    description: "Heywood Hospital is a community hospital serving North Central Massachusetts. The hospital provides comprehensive medical services including emergency care, surgical services, and specialty care.",
    shortDescription: "Community hospital serving North Central Massachusetts.",
    services: ["Emergency Services", "Surgery", "Orthopedics", "Women's Health"],
    specializations: ["Community Medicine"],
    amenities: ["Parking", "Cafeteria", "Pharmacy", "WiFi"],
    acceptsMedicare: "yes",
    acceptsMedicaid: "yes",
    totalBeds: 134,
    overallRating: "4.2",
    
    status: "published",
    sortOrder: 23
  },
  {
    name: "HealthAlliance-Clinton Hospital",
    slug: slugify("healthalliance-clinton-hospital-leominster"),
    facilityType: "hospital",
    address: "60 Hospital Road",
    city: "Leominster",
    state: "MA",
    zipCode: "01453",
    county: "Worcester",
    phone: "(978) 466-2000",
    description: "HealthAlliance-Clinton Hospital, part of UMass Memorial Health, is a community hospital serving the Leominster and Clinton areas. The hospital offers emergency services, surgical care, and comprehensive medical services.",
    shortDescription: "UMass Memorial community hospital serving Leominster and Clinton.",
    services: ["Emergency Services", "Surgery", "Cardiac Care", "Orthopedics"],
    specializations: ["Community Medicine"],
    amenities: ["Parking", "Cafeteria", "Pharmacy", "WiFi"],
    acceptsMedicare: "yes",
    acceptsMedicaid: "yes",
    totalBeds: 126,
    overallRating: "4.3",
    
    status: "published",
    sortOrder: 24
  },
  {
    name: "Athol Hospital",
    slug: slugify("athol-hospital-athol"),
    facilityType: "hospital",
    address: "2033 Main Street",
    city: "Athol",
    state: "MA",
    zipCode: "01331",
    county: "Worcester",
    phone: "(978) 249-3511",
    description: "Athol Hospital is a Critical Access Hospital serving the rural communities of North Central Massachusetts. As part of Heywood Healthcare, the hospital provides essential emergency and medical services to the region.",
    shortDescription: "Critical Access Hospital serving rural North Central Massachusetts.",
    services: ["Emergency Services", "Primary Care", "Diagnostic Imaging", "Laboratory Services"],
    specializations: ["Critical Access Care", "Rural Medicine"],
    amenities: ["Parking", "Cafeteria", "WiFi"],
    acceptsMedicare: "yes",
    acceptsMedicaid: "yes",
    totalBeds: 25,
    overallRating: "4.1",
    
    status: "published",
    sortOrder: 25
  },
  {
    name: "Milford Regional Medical Center",
    slug: slugify("milford-regional-medical-center-milford"),
    facilityType: "hospital",
    address: "14 Prospect Street",
    city: "Milford",
    state: "MA",
    zipCode: "01757",
    county: "Worcester",
    phone: "(508) 473-1190",
    description: "Milford Regional Medical Center is an independent, community-owned hospital providing comprehensive medical services to the Milford area. The hospital offers emergency care, surgical services, and a range of specialty services.",
    shortDescription: "Independent community hospital serving the Milford area.",
    services: ["Emergency Services", "Surgery", "Cancer Treatment", "Cardiac Care", "Orthopedics"],
    specializations: ["Community Medicine"],
    amenities: ["Parking", "Cafeteria", "Chapel", "Pharmacy", "WiFi"],
    acceptsMedicare: "yes",
    acceptsMedicaid: "yes",
    totalBeds: 148,
    overallRating: "4.4",
    
    status: "published",
    sortOrder: 26
  },
  {
    name: "Baystate Medical Center",
    slug: slugify("baystate-medical-center-springfield"),
    facilityType: "hospital",
    address: "759 Chestnut Street",
    city: "Springfield",
    state: "MA",
    zipCode: "01199",
    county: "Hampden",
    phone: "(413) 794-0000",
    website: "https://www.baystatehealth.org",
    description: "Baystate Medical Center is the largest hospital in Western Massachusetts and a Level I Trauma Center. As the teaching hospital for UMass Chan Medical School-Baystate, it provides comprehensive medical services including cardiac surgery, cancer treatment, and pediatric care.",
    shortDescription: "Western Massachusetts' largest hospital and only Level I Trauma Center.",
    services: ["Emergency Services", "Level I Trauma Center", "Cardiac Surgery", "Cancer Treatment", "Pediatrics", "Neurosurgery"],
    specializations: ["Trauma Center", "Cardiac Care", "Pediatrics"],
    amenities: ["Parking", "Cafeteria", "Chapel", "Gift Shop", "Pharmacy", "WiFi"],
    acceptsMedicare: "yes",
    acceptsMedicaid: "yes",
    totalBeds: 716,
    overallRating: "4.5",
    
    status: "published",
    featured: "yes",
    sortOrder: 27
  },
  {
    name: "Mercy Medical Center",
    slug: slugify("mercy-medical-center-springfield"),
    facilityType: "hospital",
    address: "271 Carew Street",
    city: "Springfield",
    state: "MA",
    zipCode: "01104",
    county: "Hampden",
    phone: "(413) 748-9000",
    description: "Mercy Medical Center is a faith-based community hospital in Springfield. Part of Trinity Health Of New England, the hospital provides comprehensive medical services with a focus on compassionate, patient-centered care.",
    shortDescription: "Faith-based community hospital providing compassionate care in Springfield.",
    services: ["Emergency Services", "Surgery", "Cardiac Care", "Orthopedics", "Women's Health"],
    specializations: ["Community Medicine"],
    amenities: ["Parking", "Cafeteria", "Chapel", "Pharmacy", "WiFi"],
    acceptsMedicare: "yes",
    acceptsMedicaid: "yes",
    totalBeds: 336,
    overallRating: "4.3",
    
    status: "published",
    sortOrder: 28
  },
  {
    name: "Holyoke Medical Center",
    slug: slugify("holyoke-medical-center-holyoke"),
    facilityType: "hospital",
    address: "575 Beech Street",
    city: "Holyoke",
    state: "MA",
    zipCode: "01040",
    county: "Hampden",
    phone: "(413) 534-2500",
    description: "Holyoke Medical Center is a community hospital providing comprehensive medical services to Holyoke and surrounding communities. The hospital offers emergency services, surgical care, and specialty medical services.",
    shortDescription: "Community hospital serving Holyoke and surrounding communities.",
    services: ["Emergency Services", "Surgery", "Cardiac Care", "Orthopedics"],
    specializations: ["Community Medicine"],
    amenities: ["Parking", "Cafeteria", "Chapel", "Pharmacy", "WiFi"],
    acceptsMedicare: "yes",
    acceptsMedicaid: "yes",
    totalBeds: 198,
    overallRating: "4.1",
    
    status: "published",
    sortOrder: 29
  },
  {
    name: "Baystate Noble Hospital",
    slug: slugify("baystate-noble-hospital-westfield"),
    facilityType: "hospital",
    address: "115 West Silver Street",
    city: "Westfield",
    state: "MA",
    zipCode: "01085",
    county: "Hampden",
    phone: "(413) 568-2811",
    description: "Baystate Noble Hospital is a community hospital serving Westfield and surrounding communities. Part of Baystate Health, the hospital provides emergency care, surgical services, and comprehensive medical care.",
    shortDescription: "Baystate Health community hospital serving Westfield.",
    services: ["Emergency Services", "Surgery", "Orthopedics", "Primary Care"],
    specializations: ["Community Medicine"],
    amenities: ["Parking", "Cafeteria", "Pharmacy", "WiFi"],
    acceptsMedicare: "yes",
    acceptsMedicaid: "yes",
    totalBeds: 97,
    overallRating: "4.2",
    
    status: "published",
    sortOrder: 30
  },
  {
    name: "Baystate Wing Hospital",
    slug: slugify("baystate-wing-hospital-palmer"),
    facilityType: "hospital",
    address: "40 Wright Street",
    city: "Palmer",
    state: "MA",
    zipCode: "01069",
    county: "Hampden",
    phone: "(413) 283-7651",
    description: "Baystate Wing Hospital is a Critical Access Hospital serving the Palmer area. Part of Baystate Health, the hospital provides essential emergency and medical services to rural communities in the region.",
    shortDescription: "Baystate Health Critical Access Hospital serving Palmer and rural communities.",
    services: ["Emergency Services", "Primary Care", "Diagnostic Imaging", "Laboratory Services"],
    specializations: ["Critical Access Care", "Rural Medicine"],
    amenities: ["Parking", "Cafeteria", "WiFi"],
    acceptsMedicare: "yes",
    acceptsMedicaid: "yes",
    totalBeds: 74,
    overallRating: "4.0",
    
    status: "published",
    sortOrder: 31
  },
  {
    name: "Cooley Dickinson Hospital",
    slug: slugify("cooley-dickinson-hospital-northampton"),
    facilityType: "hospital",
    address: "30 Locust Street",
    city: "Northampton",
    state: "MA",
    zipCode: "01060",
    county: "Hampshire",
    phone: "(413) 582-2000",
    website: "https://www.cooleydickinson.org",
    description: "Cooley Dickinson Hospital is a community hospital serving the Pioneer Valley. Part of Mass General Brigham, the hospital provides comprehensive medical services with a focus on patient-centered care and community wellness.",
    shortDescription: "Mass General Brigham community hospital serving the Pioneer Valley.",
    services: ["Emergency Services", "Surgery", "Cardiac Care", "Orthopedics", "Women's Health", "Behavioral Health"],
    specializations: ["Community Medicine"],
    amenities: ["Parking", "Cafeteria", "Chapel", "Pharmacy", "WiFi"],
    acceptsMedicare: "yes",
    acceptsMedicaid: "yes",
    totalBeds: 140,
    overallRating: "4.4",
    
    status: "published",
    sortOrder: 32
  },
  {
    name: "Baystate Franklin Medical Center",
    slug: slugify("baystate-franklin-medical-center-greenfield"),
    facilityType: "hospital",
    address: "164 High Street",
    city: "Greenfield",
    state: "MA",
    zipCode: "01301",
    county: "Franklin",
    phone: "(413) 773-0211",
    description: "Baystate Franklin Medical Center is a community hospital serving Franklin County. Part of Baystate Health, the hospital provides emergency care, surgical services, and comprehensive medical care to the region.",
    shortDescription: "Baystate Health community hospital serving Franklin County.",
    services: ["Emergency Services", "Surgery", "Orthopedics", "Women's Health", "Behavioral Health"],
    specializations: ["Community Medicine"],
    amenities: ["Parking", "Cafeteria", "Chapel", "Pharmacy", "WiFi"],
    acceptsMedicare: "yes",
    acceptsMedicaid: "yes",
    totalBeds: 90,
    overallRating: "4.3",
    
    status: "published",
    sortOrder: 33
  },
  {
    name: "Berkshire Medical Center",
    slug: slugify("berkshire-medical-center-pittsfield"),
    facilityType: "hospital",
    address: "725 North Street",
    city: "Pittsfield",
    state: "MA",
    zipCode: "01201",
    county: "Berkshire",
    phone: "(413) 447-2000",
    website: "https://www.berkshirehealthsystems.org",
    description: "Berkshire Medical Center is the region's leading healthcare provider, offering a comprehensive range of specialty and primary care services. The hospital serves as the primary medical center for Berkshire County.",
    shortDescription: "Berkshire County's leading healthcare provider with comprehensive specialty services.",
    services: ["Emergency Services", "Surgery", "Cardiac Care", "Cancer Treatment", "Orthopedics", "Women's Health"],
    specializations: ["Cardiac Care", "Regional Medical Center"],
    amenities: ["Parking", "Cafeteria", "Chapel", "Gift Shop", "Pharmacy", "WiFi"],
    acceptsMedicare: "yes",
    acceptsMedicaid: "yes",
    totalBeds: 298,
    overallRating: "4.4",
    
    status: "published",
    featured: "yes",
    sortOrder: 34
  },
  {
    name: "Fairview Hospital",
    slug: slugify("fairview-hospital-great-barrington"),
    facilityType: "hospital",
    address: "29 Lewis Avenue",
    city: "Great Barrington",
    state: "MA",
    zipCode: "01230",
    county: "Berkshire",
    phone: "(413) 528-0790",
    description: "Fairview Hospital is a Critical Access Hospital serving South Berkshire County. Part of Berkshire Health Systems, the hospital provides essential emergency and medical services to the rural communities of the southern Berkshires.",
    shortDescription: "Critical Access Hospital serving South Berkshire County.",
    services: ["Emergency Services", "Primary Care", "Diagnostic Imaging", "Laboratory Services"],
    specializations: ["Critical Access Care", "Rural Medicine"],
    amenities: ["Parking", "Cafeteria", "WiFi"],
    acceptsMedicare: "yes",
    acceptsMedicaid: "yes",
    totalBeds: 25,
    overallRating: "4.2",
    
    status: "published",
    sortOrder: 35
  },
  {
    name: "North Adams Regional Hospital",
    slug: slugify("north-adams-regional-hospital-north-adams"),
    facilityType: "hospital",
    address: "71 Hospital Avenue",
    city: "North Adams",
    state: "MA",
    zipCode: "01247",
    county: "Berkshire",
    phone: "(413) 664-5000",
    description: "North Adams Regional Hospital is a community hospital serving North Berkshire County. The hospital provides emergency care and essential medical services to the northern Berkshires region.",
    shortDescription: "Community hospital serving North Berkshire County.",
    services: ["Emergency Services", "Primary Care", "Diagnostic Imaging"],
    specializations: ["Community Medicine"],
    amenities: ["Parking", "Cafeteria", "WiFi"],
    acceptsMedicare: "yes",
    acceptsMedicaid: "yes",
    totalBeds: 61,
    overallRating: "4.0",
    
    status: "published",
    sortOrder: 36
  },
  {
    name: "Anna Jaques Hospital",
    slug: slugify("anna-jaques-hospital-newburyport"),
    facilityType: "hospital",
    address: "25 Highland Avenue",
    city: "Newburyport",
    state: "MA",
    zipCode: "01950",
    county: "Essex",
    phone: "(978) 463-1000",
    description: "Anna Jaques Hospital is a community hospital serving Newburyport and the Merrimack Valley region. Part of Beth Israel Lahey Health, the hospital provides comprehensive medical services with a focus on patient-centered care.",
    shortDescription: "Beth Israel Lahey Health community hospital serving the Merrimack Valley.",
    services: ["Emergency Services", "Surgery", "Orthopedics", "Women's Health", "Cardiac Care"],
    specializations: ["Community Medicine"],
    amenities: ["Parking", "Cafeteria", "Chapel", "Pharmacy", "WiFi"],
    acceptsMedicare: "yes",
    acceptsMedicaid: "yes",
    totalBeds: 123,
    overallRating: "4.4",
    
    status: "published",
    sortOrder: 37
  },
  {
    name: "Beverly Hospital",
    slug: slugify("beverly-hospital-beverly"),
    facilityType: "hospital",
    address: "85 Herrick Street",
    city: "Beverly",
    state: "MA",
    zipCode: "01915",
    county: "Essex",
    phone: "(978) 922-3000",
    description: "Beverly Hospital is a community hospital serving Beverly and the North Shore. Part of Beth Israel Lahey Health, the hospital provides comprehensive medical services including emergency care, surgical services, and maternity care.",
    shortDescription: "Beth Israel Lahey Health community hospital serving the North Shore.",
    services: ["Emergency Services", "Surgery", "Maternity Services", "Orthopedics", "Cardiac Care"],
    specializations: ["Community Medicine", "Maternity Care"],
    amenities: ["Parking", "Cafeteria", "Chapel", "Pharmacy", "WiFi"],
    acceptsMedicare: "yes",
    acceptsMedicaid: "yes",
    totalBeds: 304,
    overallRating: "4.3",
    
    status: "published",
    sortOrder: 38
  },
  {
    name: "Lawrence General Hospital",
    slug: slugify("lawrence-general-hospital-lawrence"),
    facilityType: "hospital",
    address: "1 General Street",
    city: "Lawrence",
    state: "MA",
    zipCode: "01842",
    county: "Essex",
    phone: "(978) 683-4000",
    description: "Lawrence General Hospital is a community hospital serving Lawrence and the Merrimack Valley. The hospital provides comprehensive medical services including emergency care, surgical services, and specialty care.",
    shortDescription: "Community hospital serving Lawrence and the Merrimack Valley.",
    services: ["Emergency Services", "Surgery", "Cardiac Care", "Orthopedics", "Women's Health"],
    specializations: ["Community Medicine"],
    amenities: ["Parking", "Cafeteria", "Chapel", "Pharmacy", "Interpreter Services", "WiFi"],
    acceptsMedicare: "yes",
    acceptsMedicaid: "yes",
    totalBeds: 189,
    overallRating: "4.2",
    
    status: "published",
    sortOrder: 39
  },
  {
    name: "Holy Family Hospital - Methuen",
    slug: slugify("holy-family-hospital-methuen"),
    facilityType: "hospital",
    address: "70 East Street",
    city: "Methuen",
    state: "MA",
    zipCode: "01844",
    county: "Essex",
    phone: "(978) 687-0151",
    description: "Holy Family Hospital in Methuen is a community hospital serving the Merrimack Valley. Part of Steward Health Care, the hospital provides comprehensive medical services with a focus on family-centered care.",
    shortDescription: "Steward Health Care community hospital serving the Merrimack Valley.",
    services: ["Emergency Services", "Surgery", "Cardiac Care", "Orthopedics", "Maternity Services"],
    specializations: ["Community Medicine"],
    amenities: ["Parking", "Cafeteria", "Chapel", "Pharmacy", "WiFi"],
    acceptsMedicare: "yes",
    acceptsMedicaid: "yes",
    totalBeds: 273,
    overallRating: "4.1",
    
    status: "published",
    sortOrder: 40
  },
  {
    name: "Holy Family Hospital - Haverhill",
    slug: slugify("holy-family-hospital-haverhill"),
    facilityType: "hospital",
    address: "140 Lincoln Avenue",
    city: "Haverhill",
    state: "MA",
    zipCode: "01830",
    county: "Essex",
    phone: "(978) 374-2000",
    description: "Holy Family Hospital in Haverhill is a community hospital serving Haverhill and the greater Merrimack Valley. The hospital provides emergency care and essential medical services.",
    shortDescription: "Community hospital serving Haverhill and the Merrimack Valley.",
    services: ["Emergency Services", "Surgery", "Orthopedics", "Primary Care"],
    specializations: ["Community Medicine"],
    amenities: ["Parking", "Cafeteria", "Chapel", "WiFi"],
    acceptsMedicare: "yes",
    acceptsMedicaid: "yes",
    totalBeds: 92,
    overallRating: "4.0",
    
    status: "published",
    sortOrder: 41
  },
  {
    name: "Salem Hospital",
    slug: slugify("salem-hospital-salem"),
    facilityType: "hospital",
    address: "81 Highland Avenue",
    city: "Salem",
    state: "MA",
    zipCode: "01970",
    county: "Essex",
    phone: "(978) 741-1200",
    description: "Salem Hospital is a community hospital serving Salem and the North Shore. Part of Mass General Brigham, the hospital provides comprehensive medical services including emergency care, surgical services, and cancer treatment.",
    shortDescription: "Mass General Brigham community hospital serving the North Shore.",
    services: ["Emergency Services", "Surgery", "Cancer Treatment", "Cardiac Care", "Orthopedics"],
    specializations: ["Community Medicine"],
    amenities: ["Parking", "Cafeteria", "Chapel", "Pharmacy", "WiFi"],
    acceptsMedicare: "yes",
    acceptsMedicaid: "yes",
    totalBeds: 395,
    overallRating: "4.3",
    
    status: "published",
    sortOrder: 42
  },
  {
    name: "Addison Gilbert Hospital",
    slug: slugify("addison-gilbert-hospital-gloucester"),
    facilityType: "hospital",
    address: "298 Washington Street",
    city: "Gloucester",
    state: "MA",
    zipCode: "01930",
    county: "Essex",
    phone: "(978) 283-4000",
    description: "Addison Gilbert Hospital is a community hospital serving Gloucester and Cape Ann. Part of Beth Israel Lahey Health, the hospital provides emergency care and essential medical services to the coastal communities.",
    shortDescription: "Beth Israel Lahey Health community hospital serving Cape Ann.",
    services: ["Emergency Services", "Surgery", "Orthopedics", "Primary Care"],
    specializations: ["Community Medicine", "Coastal Community Care"],
    amenities: ["Parking", "Cafeteria", "WiFi"],
    acceptsMedicare: "yes",
    acceptsMedicaid: "yes",
    totalBeds: 26,
    overallRating: "4.2",
    
    status: "published",
    sortOrder: 43
  },
  {
    name: "South Shore Hospital",
    slug: slugify("south-shore-hospital-weymouth"),
    facilityType: "hospital",
    address: "55 Fogg Road",
    city: "Weymouth",
    state: "MA",
    zipCode: "02190",
    county: "Norfolk",
    phone: "(781) 624-8000",
    website: "https://www.southshorehospital.org",
    description: "South Shore Hospital is the South Shore's largest healthcare provider, offering comprehensive medical services including cardiac care, cancer treatment, maternity services, and one of the region's busiest emergency departments.",
    shortDescription: "South Shore's largest healthcare provider with comprehensive specialty services.",
    services: ["Emergency Services", "Surgery", "Cardiac Care", "Cancer Treatment", "Maternity Services", "Women's Health"],
    specializations: ["Cardiac Care", "Women's Health", "Maternity Care"],
    amenities: ["Parking", "Cafeteria", "Chapel", "Gift Shop", "Pharmacy", "WiFi"],
    acceptsMedicare: "yes",
    acceptsMedicaid: "yes",
    totalBeds: 378,
    overallRating: "4.5",
    
    status: "published",
    featured: "yes",
    sortOrder: 44
  },
  {
    name: "Quincy Medical Center",
    slug: slugify("quincy-medical-center-quincy"),
    facilityType: "hospital",
    address: "114 Whitwell Street",
    city: "Quincy",
    state: "MA",
    zipCode: "02169",
    county: "Norfolk",
    phone: "(617) 773-6100",
    description: "Quincy Medical Center is a community hospital serving Quincy and the South Shore. The hospital provides emergency care and essential medical services to the community.",
    shortDescription: "Community hospital serving Quincy and the South Shore.",
    services: ["Emergency Services", "Surgery", "Orthopedics", "Primary Care"],
    specializations: ["Community Medicine"],
    amenities: ["Parking", "Cafeteria", "Pharmacy", "WiFi"],
    acceptsMedicare: "yes",
    acceptsMedicaid: "yes",
    totalBeds: 196,
    overallRating: "4.1",
    
    status: "published",
    sortOrder: 45
  },
  {
    name: "Milton Hospital",
    slug: slugify("milton-hospital-milton"),
    facilityType: "hospital",
    address: "199 Reedsdale Road",
    city: "Milton",
    state: "MA",
    zipCode: "02186",
    county: "Norfolk",
    phone: "(617) 696-4600",
    description: "Milton Hospital is a community hospital serving Milton and surrounding communities. Part of Beth Israel Lahey Health, the hospital provides comprehensive medical services with a focus on personalized care.",
    shortDescription: "Beth Israel Lahey Health community hospital serving Milton.",
    services: ["Emergency Services", "Surgery", "Orthopedics", "Primary Care"],
    specializations: ["Community Medicine"],
    amenities: ["Parking", "Cafeteria", "Pharmacy", "WiFi"],
    acceptsMedicare: "yes",
    acceptsMedicaid: "yes",
    totalBeds: 88,
    overallRating: "4.3",
    
    status: "published",
    sortOrder: 46
  },
  {
    name: "Norwood Hospital",
    slug: slugify("norwood-hospital-norwood"),
    facilityType: "hospital",
    address: "800 Washington Street",
    city: "Norwood",
    state: "MA",
    zipCode: "02062",
    county: "Norfolk",
    phone: "(781) 769-4000",
    description: "Norwood Hospital is a community hospital serving Norwood and surrounding communities. The hospital provides emergency care, surgical services, and comprehensive medical care.",
    shortDescription: "Community hospital serving Norwood and surrounding communities.",
    services: ["Emergency Services", "Surgery", "Cardiac Care", "Orthopedics"],
    specializations: ["Community Medicine"],
    amenities: ["Parking", "Cafeteria", "Chapel", "Pharmacy", "WiFi"],
    acceptsMedicare: "yes",
    acceptsMedicaid: "yes",
    totalBeds: 263,
    overallRating: "4.2",
    
    status: "published",
    sortOrder: 47
  },
  {
    name: "Brockton Hospital",
    slug: slugify("brockton-hospital-brockton"),
    facilityType: "hospital",
    address: "680 Centre Street",
    city: "Brockton",
    state: "MA",
    zipCode: "02302",
    county: "Plymouth",
    phone: "(508) 941-7000",
    description: "Brockton Hospital is a community hospital serving Brockton and the South Shore. The hospital provides comprehensive medical services including emergency care, surgical services, and specialty care.",
    shortDescription: "Community hospital serving Brockton and the South Shore.",
    services: ["Emergency Services", "Surgery", "Cardiac Care", "Orthopedics", "Women's Health"],
    specializations: ["Community Medicine"],
    amenities: ["Parking", "Cafeteria", "Chapel", "Pharmacy", "WiFi"],
    acceptsMedicare: "yes",
    acceptsMedicaid: "yes",
    totalBeds: 216,
    overallRating: "4.1",
    
    status: "published",
    sortOrder: 48
  },
  {
    name: "Good Samaritan Medical Center",
    slug: slugify("good-samaritan-medical-center-brockton"),
    facilityType: "hospital",
    address: "235 North Pearl Street",
    city: "Brockton",
    state: "MA",
    zipCode: "02301",
    county: "Plymouth",
    phone: "(508) 427-3000",
    description: "Good Samaritan Medical Center is a community hospital serving Brockton and surrounding areas. Part of Steward Health Care, the hospital provides comprehensive medical services with a focus on patient-centered care.",
    shortDescription: "Steward Health Care community hospital serving Brockton.",
    services: ["Emergency Services", "Surgery", "Cardiac Care", "Orthopedics", "Women's Health"],
    specializations: ["Community Medicine"],
    amenities: ["Parking", "Cafeteria", "Chapel", "Pharmacy", "WiFi"],
    acceptsMedicare: "yes",
    acceptsMedicaid: "yes",
    totalBeds: 286,
    overallRating: "4.2",
    
    status: "published",
    sortOrder: 49
  },
  {
    name: "Beth Israel Deaconess Hospital - Plymouth",
    slug: slugify("beth-israel-deaconess-hospital-plymouth"),
    facilityType: "hospital",
    address: "275 Sandwich Street",
    city: "Plymouth",
    state: "MA",
    zipCode: "02360",
    county: "Plymouth",
    phone: "(508) 746-2000",
    description: "Beth Israel Deaconess Hospital-Plymouth is a community hospital serving Plymouth and the South Shore. Part of Beth Israel Lahey Health, the hospital provides comprehensive medical services including emergency care and surgical services.",
    shortDescription: "Beth Israel Lahey Health community hospital serving historic Plymouth.",
    services: ["Emergency Services", "Surgery", "Cardiac Care", "Orthopedics", "Women's Health"],
    specializations: ["Community Medicine"],
    amenities: ["Parking", "Cafeteria", "Chapel", "Pharmacy", "WiFi"],
    acceptsMedicare: "yes",
    acceptsMedicaid: "yes",
    totalBeds: 170,
    overallRating: "4.4",
    
    status: "published",
    sortOrder: 50
  },
  {
    name: "Charlton Memorial Hospital",
    slug: slugify("charlton-memorial-hospital-fall-river"),
    facilityType: "hospital",
    address: "363 Highland Avenue",
    city: "Fall River",
    state: "MA",
    zipCode: "02720",
    county: "Bristol",
    phone: "(508) 679-3131",
    description: "Charlton Memorial Hospital is a community hospital serving Fall River and the surrounding area. Part of Southcoast Health, the hospital provides comprehensive medical services including emergency care and surgical services.",
    shortDescription: "Southcoast Health community hospital serving Fall River.",
    services: ["Emergency Services", "Surgery", "Cardiac Care", "Orthopedics", "Cancer Services"],
    specializations: ["Community Medicine"],
    amenities: ["Parking", "Cafeteria", "Chapel", "Pharmacy", "WiFi"],
    acceptsMedicare: "yes",
    acceptsMedicaid: "yes",
    totalBeds: 338,
    overallRating: "4.2",
    
    status: "published",
    sortOrder: 51
  },
  {
    name: "Saint Anne's Hospital",
    slug: slugify("saint-annes-hospital-fall-river"),
    facilityType: "hospital",
    address: "795 Middle Street",
    city: "Fall River",
    state: "MA",
    zipCode: "02721",
    county: "Bristol",
    phone: "(508) 674-5600",
    description: "Saint Anne's Hospital is a community hospital serving Fall River and southeastern Massachusetts. Part of Steward Health Care, the hospital provides comprehensive medical services with a faith-based approach to care.",
    shortDescription: "Steward Health Care community hospital serving Fall River.",
    services: ["Emergency Services", "Surgery", "Cardiac Care", "Orthopedics", "Women's Health"],
    specializations: ["Community Medicine"],
    amenities: ["Parking", "Cafeteria", "Chapel", "Pharmacy", "WiFi"],
    acceptsMedicare: "yes",
    acceptsMedicaid: "yes",
    totalBeds: 160,
    overallRating: "4.1",
    
    status: "published",
    sortOrder: 52
  },
  {
    name: "St. Luke's Hospital",
    slug: slugify("st-lukes-hospital-new-bedford"),
    facilityType: "hospital",
    address: "101 Page Street",
    city: "New Bedford",
    state: "MA",
    zipCode: "02740",
    county: "Bristol",
    phone: "(508) 997-1515",
    description: "St. Luke's Hospital is a community hospital serving New Bedford and the South Coast. Part of Southcoast Health, the hospital provides comprehensive medical services including emergency care, surgical services, and specialty care.",
    shortDescription: "Southcoast Health community hospital serving New Bedford.",
    services: ["Emergency Services", "Surgery", "Cardiac Care", "Orthopedics", "Cancer Services"],
    specializations: ["Community Medicine"],
    amenities: ["Parking", "Cafeteria", "Chapel", "Pharmacy", "WiFi"],
    acceptsMedicare: "yes",
    acceptsMedicaid: "yes",
    totalBeds: 246,
    overallRating: "4.2",
    
    status: "published",
    sortOrder: 53
  },
  {
    name: "Tobey Hospital",
    slug: slugify("tobey-hospital-wareham"),
    facilityType: "hospital",
    address: "43 High Street",
    city: "Wareham",
    state: "MA",
    zipCode: "02571",
    county: "Plymouth",
    phone: "(508) 295-0880",
    description: "Tobey Hospital is a community hospital serving Wareham and the Upper Cape. Part of Southcoast Health, the hospital provides emergency care and essential medical services.",
    shortDescription: "Southcoast Health community hospital serving the Upper Cape.",
    services: ["Emergency Services", "Surgery", "Orthopedics", "Primary Care"],
    specializations: ["Community Medicine"],
    amenities: ["Parking", "Cafeteria", "Pharmacy", "WiFi"],
    acceptsMedicare: "yes",
    acceptsMedicaid: "yes",
    totalBeds: 43,
    overallRating: "4.1",
    
    status: "published",
    sortOrder: 54
  },
  {
    name: "Morton Hospital",
    slug: slugify("morton-hospital-taunton"),
    facilityType: "hospital",
    address: "88 Washington Street",
    city: "Taunton",
    state: "MA",
    zipCode: "02780",
    county: "Bristol",
    phone: "(508) 828-7000",
    description: "Morton Hospital is a community hospital serving Taunton and the greater southeastern Massachusetts area. Part of Steward Health Care, the hospital provides comprehensive medical services.",
    shortDescription: "Steward Health Care community hospital serving Taunton.",
    services: ["Emergency Services", "Surgery", "Cardiac Care", "Orthopedics"],
    specializations: ["Community Medicine"],
    amenities: ["Parking", "Cafeteria", "Chapel", "Pharmacy", "WiFi"],
    acceptsMedicare: "yes",
    acceptsMedicaid: "yes",
    totalBeds: 153,
    overallRating: "4.0",
    
    status: "published",
    sortOrder: 55
  },
  {
    name: "Sturdy Memorial Hospital",
    slug: slugify("sturdy-memorial-hospital-attleboro"),
    facilityType: "hospital",
    address: "211 Park Street",
    city: "Attleboro",
    state: "MA",
    zipCode: "02703",
    county: "Bristol",
    phone: "(508) 222-5200",
    description: "Sturdy Memorial Hospital is an independent, community-owned hospital serving Attleboro and southeastern Massachusetts. The hospital provides comprehensive medical services with a focus on patient-centered care.",
    shortDescription: "Independent community hospital serving Attleboro.",
    services: ["Emergency Services", "Surgery", "Cardiac Care", "Orthopedics", "Women's Health"],
    specializations: ["Community Medicine"],
    amenities: ["Parking", "Cafeteria", "Chapel", "Pharmacy", "WiFi"],
    acceptsMedicare: "yes",
    acceptsMedicaid: "yes",
    totalBeds: 132,
    overallRating: "4.3",
    
    status: "published",
    sortOrder: 56
  },
  {
    name: "Cape Cod Hospital",
    slug: slugify("cape-cod-hospital-hyannis"),
    facilityType: "hospital",
    address: "27 Park Street",
    city: "Hyannis",
    state: "MA",
    zipCode: "02601",
    county: "Barnstable",
    phone: "(508) 771-1800",
    website: "https://www.capecodhealth.org",
    description: "Cape Cod Hospital is the primary acute care hospital on Cape Cod, providing comprehensive medical services to residents and visitors. The hospital offers emergency care, surgical services, cardiac care, and specialty services.",
    shortDescription: "Cape Cod's primary acute care hospital serving residents and visitors.",
    services: ["Emergency Services", "Surgery", "Cardiac Care", "Cancer Treatment", "Orthopedics", "Maternity Services"],
    specializations: ["Regional Medical Center", "Seasonal Care"],
    amenities: ["Parking", "Cafeteria", "Chapel", "Gift Shop", "Pharmacy", "WiFi"],
    acceptsMedicare: "yes",
    acceptsMedicaid: "yes",
    totalBeds: 259,
    overallRating: "4.4",
    
    status: "published",
    featured: "yes",
    sortOrder: 57
  },
  {
    name: "Falmouth Hospital",
    slug: slugify("falmouth-hospital-falmouth"),
    facilityType: "hospital",
    address: "100 Ter Heun Drive",
    city: "Falmouth",
    state: "MA",
    zipCode: "02540",
    county: "Barnstable",
    phone: "(508) 548-5300",
    description: "Falmouth Hospital is a community hospital serving Falmouth and the Upper Cape. Part of Cape Cod Healthcare, the hospital provides emergency care, surgical services, and essential medical care.",
    shortDescription: "Cape Cod Healthcare community hospital serving the Upper Cape.",
    services: ["Emergency Services", "Surgery", "Orthopedics", "Primary Care"],
    specializations: ["Community Medicine"],
    amenities: ["Parking", "Cafeteria", "Chapel", "Pharmacy", "WiFi"],
    acceptsMedicare: "yes",
    acceptsMedicaid: "yes",
    totalBeds: 95,
    overallRating: "4.3",
    
    status: "published",
    sortOrder: 58
  },
  {
    name: "Martha's Vineyard Hospital",
    slug: slugify("marthas-vineyard-hospital-oak-bluffs"),
    facilityType: "hospital",
    address: "1 Hospital Road",
    city: "Oak Bluffs",
    state: "MA",
    zipCode: "02557",
    county: "Dukes",
    phone: "(508) 693-0410",
    description: "Martha's Vineyard Hospital is a Critical Access Hospital serving the island of Martha's Vineyard. The hospital provides essential emergency and medical services year-round to residents and visitors.",
    shortDescription: "Critical Access Hospital serving Martha's Vineyard island community.",
    services: ["Emergency Services", "Primary Care", "Diagnostic Imaging", "Laboratory Services"],
    specializations: ["Critical Access Care", "Island Medicine"],
    amenities: ["Parking", "Cafeteria", "WiFi"],
    acceptsMedicare: "yes",
    acceptsMedicaid: "yes",
    totalBeds: 25,
    overallRating: "4.3",
    
    status: "published",
    sortOrder: 59
  },
  {
    name: "Nantucket Cottage Hospital",
    slug: slugify("nantucket-cottage-hospital-nantucket"),
    facilityType: "hospital",
    address: "57 Prospect Street",
    city: "Nantucket",
    state: "MA",
    zipCode: "02554",
    county: "Nantucket",
    phone: "(508) 825-8100",
    description: "Nantucket Cottage Hospital is a Critical Access Hospital serving the island of Nantucket. Part of Mass General Brigham, the hospital provides essential emergency and medical services to the island community year-round.",
    shortDescription: "Mass General Brigham Critical Access Hospital serving Nantucket island.",
    services: ["Emergency Services", "Primary Care", "Diagnostic Imaging", "Laboratory Services"],
    specializations: ["Critical Access Care", "Island Medicine"],
    amenities: ["Parking", "Cafeteria", "WiFi"],
    acceptsMedicare: "yes",
    acceptsMedicaid: "yes",
    totalBeds: 19,
    overallRating: "4.4",
    
    status: "published",
    sortOrder: 60
  }
];
