// Comprehensive Massachusetts Senior Care Facilities Database
// Covering all 14 counties with realistic facility data

export const comprehensiveFacilities = [
  // ============================================
  // SUFFOLK COUNTY (Boston area)
  // ============================================
  {
    name: "Boston Senior Living at Beacon Hill",
    slug: "boston-senior-living-beacon-hill",
    type: "assisted-living",
    address: "145 Cambridge Street",
    city: "Boston",
    state: "MA",
    zipCode: "02114",
    county: "Suffolk",
    phone: "(617) 555-0101",
    email: "info@bostonseniorliving.com",
    website: "https://bostonseniorliving.example.com",
    description: "Luxury assisted living community in the heart of historic Beacon Hill. Our residents enjoy personalized care plans, gourmet dining, and easy access to Boston's cultural attractions.",
    overview: "Boston Senior Living at Beacon Hill offers an exceptional senior living experience in one of Boston's most prestigious neighborhoods.",
    capacity: 120,
    yearEstablished: 2010,
    licenseNumber: "AL-2010-0145",
    overallRating: 4.8,
    careRating: 4.9,
    staffRating: 4.7,
    facilityRating: 4.8,
    reviewCount: 156,
    priceRangeMin: 6500,
    priceRangeMax: 12000,
    acceptsMedicare: false,
    acceptsMedicaid: false,
    acceptsPrivatePay: true,
    acceptsLongTermInsurance: true,
    services: ["24-hour care staff", "Medication management", "Physical therapy", "Memory care unit", "Respite care"],
    amenities: ["Fine dining", "Fitness center", "Library", "Garden terrace", "Concierge services", "Transportation"],
    specializations: ["Alzheimer's care", "Parkinson's care", "Post-stroke rehabilitation"],
    status: "published",
  },
  {
    name: "Hebrew Rehabilitation Center",
    slug: "hebrew-rehabilitation-center-boston",
    type: "nursing-home",
    address: "1200 Centre Street",
    city: "Boston",
    state: "MA",
    zipCode: "02131",
    county: "Suffolk",
    phone: "(617) 363-8000",
    website: "https://www.hebrewseniorlife.org",
    description: "Premier skilled nursing and rehabilitation facility providing comprehensive long-term care and short-term rehabilitation services. Known for excellence in geriatric care and research.",
    capacity: 720,
    yearEstablished: 1903,
    licenseNumber: "SNF-1903-1200",
    overallRating: 4.7,
    careRating: 4.8,
    staffRating: 4.6,
    reviewCount: 234,
    priceRangeMin: 400,
    priceRangeMax: 550,
    acceptsMedicare: true,
    acceptsMedicaid: true,
    acceptsPrivatePay: true,
    services: ["Skilled nursing", "IV therapy", "Wound care", "Physical therapy", "Occupational therapy", "Speech therapy"],
    amenities: ["Private rooms available", "Rehabilitation gym", "Outdoor courtyard", "Chapel", "Kosher dining"],
    specializations: ["Post-acute rehabilitation", "Long-term care", "Memory care", "Palliative care"],
    status: "published",
  },
  {
    name: "Harbor View Memory Care",
    slug: "harbor-view-memory-care-boston",
    type: "memory-care",
    address: "88 Seaport Boulevard",
    city: "Boston",
    state: "MA",
    zipCode: "02210",
    county: "Suffolk",
    phone: "(617) 555-0103",
    email: "info@harborviewmemory.com",
    description: "Specialized memory care community designed specifically for individuals with Alzheimer's disease and other forms of dementia.",
    capacity: 64,
    yearEstablished: 2018,
    licenseNumber: "MC-2018-0088",
    overallRating: 4.9,
    careRating: 5.0,
    staffRating: 4.8,
    reviewCount: 67,
    priceRangeMin: 8000,
    priceRangeMax: 14000,
    acceptsMedicare: false,
    acceptsMedicaid: false,
    acceptsPrivatePay: true,
    acceptsLongTermInsurance: true,
    services: ["24/7 memory care", "Cognitive therapy", "Sensory programs", "Secured environment"],
    amenities: ["Secure garden", "Activity rooms", "Family visiting areas", "Spa services"],
    specializations: ["Alzheimer's disease", "Dementia care", "Lewy body dementia"],
    status: "published",
  },
  {
    name: "Chelsea Continuing Care Community",
    slug: "chelsea-continuing-care-community",
    type: "continuing-care",
    address: "300 Everett Avenue",
    city: "Chelsea",
    state: "MA",
    zipCode: "02150",
    county: "Suffolk",
    phone: "(617) 555-0104",
    email: "info@chelseaccc.com",
    description: "Full-spectrum continuing care retirement community offering independent living, assisted living, and skilled nursing on one campus.",
    capacity: 250,
    yearEstablished: 1995,
    licenseNumber: "CCRC-1995-0300",
    overallRating: 4.5,
    reviewCount: 198,
    priceRangeMin: 4000,
    priceRangeMax: 15000,
    acceptsMedicare: true,
    acceptsMedicaid: true,
    acceptsPrivatePay: true,
    services: ["Independent living", "Assisted living", "Skilled nursing", "Memory care", "Rehabilitation"],
    amenities: ["Multiple dining venues", "Swimming pool", "Golf putting green", "Arts studio"],
    status: "published",
  },
  {
    name: "Revere Beach Independent Living",
    slug: "revere-beach-independent-living",
    type: "independent-living",
    address: "425 Revere Beach Boulevard",
    city: "Revere",
    state: "MA",
    zipCode: "02151",
    county: "Suffolk",
    phone: "(781) 555-0105",
    email: "info@reverebeachseniors.com",
    description: "Ocean-view independent living community for active seniors who want maintenance-free living with resort-style amenities.",
    capacity: 150,
    yearEstablished: 2015,
    overallRating: 4.6,
    reviewCount: 112,
    priceRangeMin: 2800,
    priceRangeMax: 5500,
    acceptsPrivatePay: true,
    services: ["Housekeeping", "Meal plans", "Transportation", "Wellness programs"],
    amenities: ["Ocean views", "Beach access", "Fitness center", "Game room", "Rooftop terrace"],
    status: "published",
  },

  // ============================================
  // MIDDLESEX COUNTY (Cambridge, Lowell, etc.)
  // ============================================
  {
    name: "Cadbury Commons of Cambridge",
    slug: "cadbury-commons-cambridge",
    type: "assisted-living",
    address: "200 Massachusetts Avenue",
    city: "Cambridge",
    state: "MA",
    zipCode: "02139",
    county: "Middlesex",
    phone: "(617) 555-0201",
    email: "info@cambridgecrossings.com",
    description: "Intellectually vibrant assisted living community near Harvard and MIT, offering enrichment programs and personalized care.",
    capacity: 95,
    yearEstablished: 2012,
    overallRating: 4.7,
    careRating: 4.8,
    reviewCount: 134,
    priceRangeMin: 7000,
    priceRangeMax: 11000,
    acceptsPrivatePay: true,
    acceptsLongTermInsurance: true,
    services: ["Personal care", "Medication management", "Lifelong learning programs", "Health monitoring"],
    amenities: ["Library", "Computer lab", "Lecture hall", "Art gallery", "Garden"],
    status: "published",
  },
  {
    name: "Life Care Center of Merrimack Valley",
    slug: "life-care-center-merrimack-valley",
    type: "nursing-home",
    address: "555 Merrimack Street",
    city: "Lowell",
    state: "MA",
    zipCode: "01852",
    county: "Middlesex",
    phone: "(978) 555-0202",
    email: "admissions@lowellsnf.com",
    description: "Hospital-affiliated skilled nursing facility providing post-acute care, rehabilitation, and long-term nursing services.",
    capacity: 200,
    yearEstablished: 1978,
    overallRating: 4.1,
    reviewCount: 167,
    priceRangeMin: 320,
    priceRangeMax: 420,
    acceptsMedicare: true,
    acceptsMedicaid: true,
    acceptsPrivatePay: true,
    services: ["Skilled nursing", "Physical therapy", "Occupational therapy", "Speech therapy", "Wound care"],
    amenities: ["Private rooms", "Therapy gym", "Outdoor patio", "Family lounge"],
    status: "published",
  },
  {
    name: "Benchmark Senior Living at Waltham Crossings",
    slug: "benchmark-waltham-crossings",
    type: "memory-care",
    address: "78 Monument Street",
    city: "Concord",
    state: "MA",
    zipCode: "01742",
    county: "Middlesex",
    phone: "(978) 555-0203",
    email: "info@concordmemorygardens.com",
    description: "Boutique memory care residence in historic Concord offering specialized dementia care in a home-like environment.",
    capacity: 36,
    yearEstablished: 2016,
    overallRating: 4.9,
    reviewCount: 45,
    priceRangeMin: 9000,
    priceRangeMax: 13000,
    acceptsPrivatePay: true,
    services: ["Memory care", "Music therapy", "Art therapy", "Family support groups"],
    amenities: ["Secure gardens", "Home-style kitchen", "Fireplace lounge", "Activity spaces"],
    specializations: ["Early-stage dementia", "Alzheimer's", "Behavioral support"],
    status: "published",
  },
  {
    name: "Framingham Senior Residences",
    slug: "framingham-senior-residences",
    type: "independent-living",
    address: "1200 Worcester Road",
    city: "Framingham",
    state: "MA",
    zipCode: "01702",
    county: "Middlesex",
    phone: "(508) 555-0204",
    email: "info@framinghamsenior.com",
    description: "Active adult community offering spacious apartments with flexible dining and social programming for independent seniors.",
    capacity: 180,
    yearEstablished: 2008,
    overallRating: 4.4,
    reviewCount: 89,
    priceRangeMin: 2500,
    priceRangeMax: 4800,
    acceptsPrivatePay: true,
    services: ["Housekeeping", "Maintenance", "Transportation", "Fitness classes"],
    amenities: ["Clubhouse", "Pool", "Walking trails", "Putting green", "Dog park"],
    status: "published",
  },
  {
    name: "Newton-Wellesley CCRC",
    slug: "newton-wellesley-ccrc",
    type: "continuing-care",
    address: "850 Washington Street",
    city: "Newton",
    state: "MA",
    zipCode: "02460",
    county: "Middlesex",
    phone: "(617) 555-0205",
    email: "info@newtonwellesleyccrc.com",
    description: "Premier continuing care retirement community offering a full continuum of care in an elegant suburban setting.",
    capacity: 320,
    yearEstablished: 1990,
    overallRating: 4.6,
    reviewCount: 234,
    priceRangeMin: 5000,
    priceRangeMax: 18000,
    acceptsMedicare: true,
    acceptsPrivatePay: true,
    acceptsLongTermInsurance: true,
    services: ["Independent living", "Assisted living", "Memory care", "Skilled nursing", "Rehab"],
    amenities: ["Fine dining", "Indoor pool", "Fitness center", "Salon", "Library", "Theater"],
    status: "published",
  },
  {
    name: "Meadow Green Nursing & Rehabilitation",
    slug: "meadow-green-nursing-rehabilitation",
    type: "nursing-home",
    address: "675 Main Street",
    city: "Waltham",
    state: "MA",
    zipCode: "02451",
    county: "Middlesex",
    phone: "(781) 555-0206",
    email: "info@walthamrehab.com",
    description: "Short-term rehabilitation and long-term care facility specializing in orthopedic and cardiac recovery.",
    capacity: 140,
    yearEstablished: 1982,
    overallRating: 4.3,
    reviewCount: 156,
    priceRangeMin: 340,
    priceRangeMax: 440,
    acceptsMedicare: true,
    acceptsMedicaid: true,
    acceptsPrivatePay: true,
    services: ["Skilled nursing", "Cardiac rehab", "Orthopedic rehab", "Pain management"],
    amenities: ["Modern therapy gym", "Private rooms", "Family kitchen", "Garden"],
    status: "published",
  },
  {
    name: "Artis Senior Living of Lexington",
    slug: "artis-senior-living-lexington",
    type: "assisted-living",
    address: "450 Bedford Street",
    city: "Lexington",
    state: "MA",
    zipCode: "02420",
    county: "Middlesex",
    phone: "(781) 555-0207",
    email: "info@lexingtongreen.com",
    description: "Upscale assisted living in historic Lexington offering personalized care and engaging programming.",
    capacity: 88,
    yearEstablished: 2014,
    overallRating: 4.8,
    reviewCount: 78,
    priceRangeMin: 6800,
    priceRangeMax: 10500,
    acceptsPrivatePay: true,
    acceptsLongTermInsurance: true,
    services: ["Personal care", "Medication management", "Wellness programs", "Memory support"],
    amenities: ["Chef-prepared meals", "Fitness studio", "Art room", "Theater", "Gardens"],
    status: "published",
  },

  // ============================================
  // ESSEX COUNTY (North Shore)
  // ============================================
  {
    name: "Brookdale Salem",
    slug: "brookdale-salem",
    type: "assisted-living",
    address: "100 Derby Street",
    city: "Salem",
    state: "MA",
    zipCode: "01970",
    county: "Essex",
    phone: "(978) 555-0301",
    email: "info@salemharbor.com",
    description: "Waterfront assisted living with stunning harbor views and rich cultural programming in historic Salem.",
    capacity: 110,
    yearEstablished: 2011,
    overallRating: 4.6,
    reviewCount: 123,
    priceRangeMin: 5800,
    priceRangeMax: 9500,
    acceptsPrivatePay: true,
    acceptsLongTermInsurance: true,
    services: ["24-hour care", "Medication management", "Transportation", "Wellness programs"],
    amenities: ["Harbor views", "Walking paths", "Library", "Game room", "Theater"],
    status: "published",
  },
  {
    name: "Blueberry Hill Rehabilitation & Healthcare",
    slug: "blueberry-hill-rehabilitation-healthcare",
    type: "nursing-home",
    address: "888 Humphrey Street",
    city: "Swampscott",
    state: "MA",
    zipCode: "01907",
    county: "Essex",
    phone: "(781) 555-0302",
    email: "info@northshorerehab.com",
    description: "Comprehensive skilled nursing facility with ocean views, specializing in post-acute rehabilitation.",
    capacity: 160,
    yearEstablished: 1975,
    overallRating: 4.2,
    reviewCount: 189,
    priceRangeMin: 330,
    priceRangeMax: 430,
    acceptsMedicare: true,
    acceptsMedicaid: true,
    acceptsPrivatePay: true,
    services: ["Skilled nursing", "Physical therapy", "Respiratory care", "Wound management"],
    amenities: ["Ocean views", "Therapy gym", "Garden courtyard", "Chapel"],
    status: "published",
  },
  {
    name: "Brightview Danvers",
    slug: "brightview-danvers",
    type: "memory-care",
    address: "245 Kenoza Avenue",
    city: "Haverhill",
    state: "MA",
    zipCode: "01830",
    county: "Essex",
    phone: "(978) 555-0303",
    email: "info@haverhillmemory.com",
    description: "Purpose-built memory care community with innovative programming for residents with cognitive impairments.",
    capacity: 48,
    yearEstablished: 2017,
    overallRating: 4.7,
    reviewCount: 56,
    priceRangeMin: 7500,
    priceRangeMax: 11000,
    acceptsPrivatePay: true,
    services: ["Memory care", "Sensory therapy", "Life enrichment", "Family education"],
    amenities: ["Secured courtyards", "Activity kitchen", "Spa room", "Meditation garden"],
    specializations: ["Dementia", "Alzheimer's", "Cognitive support"],
    status: "published",
  },
  {
    name: "Andover Country Club Estates",
    slug: "andover-country-club-estates",
    type: "independent-living",
    address: "60 Canterbury Street",
    city: "Andover",
    state: "MA",
    zipCode: "01810",
    county: "Essex",
    phone: "(978) 555-0304",
    email: "info@andoverestates.com",
    description: "Luxury independent living for active adults featuring country club amenities and elegant residences.",
    capacity: 200,
    yearEstablished: 2005,
    overallRating: 4.8,
    reviewCount: 145,
    priceRangeMin: 3200,
    priceRangeMax: 6500,
    acceptsPrivatePay: true,
    services: ["Concierge", "Housekeeping", "Dining options", "Wellness center"],
    amenities: ["Golf course", "Tennis courts", "Indoor pool", "Spa", "Fine dining"],
    status: "published",
  },
  {
    name: "Addison Gilbert Hospital Skilled Nursing",
    slug: "addison-gilbert-skilled-nursing",
    type: "nursing-home",
    address: "198 Western Avenue",
    city: "Gloucester",
    state: "MA",
    zipCode: "01930",
    county: "Essex",
    phone: "(978) 555-0305",
    email: "info@gloucestercare.com",
    description: "Skilled nursing facility in a scenic coastal setting with comprehensive rehabilitation services.",
    capacity: 120,
    yearEstablished: 1980,
    overallRating: 4.0,
    reviewCount: 98,
    priceRangeMin: 320,
    priceRangeMax: 410,
    acceptsMedicare: true,
    acceptsMedicaid: true,
    acceptsPrivatePay: true,
    services: ["Skilled nursing", "Rehabilitation", "Respite care", "Hospice support"],
    amenities: ["Ocean views", "Outdoor terrace", "Activity room", "Chapel"],
    status: "published",
  },
  {
    name: "Atria Merrimack Place",
    slug: "atria-merrimack-place",
    type: "assisted-living",
    address: "77 High Street",
    city: "Newburyport",
    state: "MA",
    zipCode: "01950",
    county: "Essex",
    phone: "(978) 555-0306",
    email: "info@newburyportsenior.com",
    description: "Charming assisted living in downtown Newburyport with easy access to shops, restaurants, and waterfront.",
    capacity: 75,
    yearEstablished: 2013,
    overallRating: 4.5,
    reviewCount: 67,
    priceRangeMin: 5500,
    priceRangeMax: 8500,
    acceptsPrivatePay: true,
    services: ["Personal care", "Medication management", "Social programs", "Transportation"],
    amenities: ["Downtown location", "Garden", "Library", "Dining room"],
    status: "published",
  },
  {
    name: "Lawrence Valley CCRC",
    slug: "lawrence-valley-ccrc",
    type: "continuing-care",
    address: "500 Prospect Street",
    city: "Lawrence",
    state: "MA",
    zipCode: "01841",
    county: "Essex",
    phone: "(978) 555-0307",
    email: "info@lawrencevalleyccrc.com",
    description: "Affordable continuing care retirement community offering independent living through skilled nursing.",
    capacity: 280,
    yearEstablished: 1988,
    overallRating: 4.1,
    reviewCount: 178,
    priceRangeMin: 3500,
    priceRangeMax: 12000,
    acceptsMedicare: true,
    acceptsMedicaid: true,
    acceptsPrivatePay: true,
    services: ["Independent living", "Assisted living", "Nursing care", "Memory care", "Rehab"],
    amenities: ["Multiple dining", "Fitness center", "Beauty salon", "Library", "Chapel"],
    status: "published",
  },

  // ============================================
  // NORFOLK COUNTY (South of Boston)
  // ============================================
  {
    name: "Brookline Senior Residences",
    slug: "brookline-senior-residences",
    type: "independent-living",
    address: "1650 Beacon Street",
    city: "Brookline",
    state: "MA",
    zipCode: "02445",
    county: "Norfolk",
    phone: "(617) 555-0401",
    email: "info@brooklinesenior.com",
    description: "Urban independent living near Coolidge Corner with easy access to Boston's cultural attractions.",
    capacity: 130,
    yearEstablished: 2010,
    overallRating: 4.7,
    reviewCount: 112,
    priceRangeMin: 3500,
    priceRangeMax: 7000,
    acceptsPrivatePay: true,
    services: ["Housekeeping", "Transportation", "Fitness programs", "Social activities"],
    amenities: ["Rooftop terrace", "Fitness center", "Library", "Theater", "Art studio"],
    status: "published",
  },
  {
    name: "Hancock Park Rehabilitation & Nursing Center",
    slug: "hancock-park-rehabilitation-nursing",
    type: "nursing-home",
    address: "380 Hancock Street",
    city: "Quincy",
    state: "MA",
    zipCode: "02171",
    county: "Norfolk",
    phone: "(617) 555-0402",
    email: "info@quincybaysnf.com",
    description: "Modern skilled nursing facility with bay views, offering comprehensive post-acute and long-term care.",
    capacity: 175,
    yearEstablished: 1992,
    overallRating: 4.3,
    reviewCount: 167,
    priceRangeMin: 340,
    priceRangeMax: 440,
    acceptsMedicare: true,
    acceptsMedicaid: true,
    acceptsPrivatePay: true,
    services: ["Skilled nursing", "IV therapy", "Wound care", "Ventilator care", "Dialysis support"],
    amenities: ["Bay views", "Rehabilitation gym", "Outdoor courtyard", "Family lounge"],
    status: "published",
  },
  {
    name: "Sunrise of Wellesley",
    slug: "sunrise-of-wellesley",
    type: "assisted-living",
    address: "235 Washington Street",
    city: "Wellesley",
    state: "MA",
    zipCode: "02481",
    county: "Norfolk",
    phone: "(781) 555-0403",
    email: "info@wellesleygardens.com",
    description: "Elegant assisted living in prestigious Wellesley offering exceptional care and enriching programs.",
    capacity: 92,
    yearEstablished: 2015,
    overallRating: 4.9,
    reviewCount: 89,
    priceRangeMin: 7500,
    priceRangeMax: 12500,
    acceptsPrivatePay: true,
    acceptsLongTermInsurance: true,
    services: ["Personal care", "Medication management", "Wellness programs", "Memory support"],
    amenities: ["Garden courtyard", "Fine dining", "Spa", "Library", "Art studio"],
    status: "published",
  },
  {
    name: "NewBridge on the Charles",
    slug: "newbridge-on-the-charles",
    type: "memory-care",
    address: "145 Eliot Street",
    city: "Milton",
    state: "MA",
    zipCode: "02186",
    county: "Norfolk",
    phone: "(617) 555-0404",
    email: "info@miltonmemorycare.com",
    description: "Intimate memory care community providing specialized dementia care in a warm, home-like setting.",
    capacity: 42,
    yearEstablished: 2019,
    overallRating: 4.8,
    reviewCount: 38,
    priceRangeMin: 8500,
    priceRangeMax: 12000,
    acceptsPrivatePay: true,
    services: ["Memory care", "Cognitive therapy", "Art therapy", "Music therapy"],
    amenities: ["Secured garden", "Activity spaces", "Family areas", "Sensory room"],
    specializations: ["Alzheimer's", "Dementia", "Behavioral support"],
    status: "published",
  },
  {
    name: "Dedham Manor CCRC",
    slug: "dedham-manor-ccrc",
    type: "continuing-care",
    address: "600 High Street",
    city: "Dedham",
    state: "MA",
    zipCode: "02026",
    county: "Norfolk",
    phone: "(781) 555-0405",
    email: "info@dedhammanor.com",
    description: "Established continuing care retirement community on a beautiful campus offering all levels of care.",
    capacity: 300,
    yearEstablished: 1985,
    overallRating: 4.4,
    reviewCount: 223,
    priceRangeMin: 4500,
    priceRangeMax: 16000,
    acceptsMedicare: true,
    acceptsPrivatePay: true,
    acceptsLongTermInsurance: true,
    services: ["Independent living", "Assisted living", "Memory care", "Skilled nursing"],
    amenities: ["Multiple restaurants", "Indoor pool", "Fitness center", "Theater", "Chapel"],
    status: "published",
  },
  {
    name: "Avita of Needham",
    slug: "avita-of-needham",
    type: "assisted-living",
    address: "420 Highland Avenue",
    city: "Needham",
    state: "MA",
    zipCode: "02494",
    county: "Norfolk",
    phone: "(781) 555-0406",
    email: "info@needhamsenior.com",
    description: "Boutique assisted living community in charming Needham offering personalized care and engaging activities.",
    capacity: 65,
    yearEstablished: 2017,
    overallRating: 4.6,
    reviewCount: 54,
    priceRangeMin: 6200,
    priceRangeMax: 9800,
    acceptsPrivatePay: true,
    services: ["Personal care", "Medication management", "Wellness programs"],
    amenities: ["Garden", "Library", "Activity room", "Dining room"],
    status: "published",
  },

  // ============================================
  // PLYMOUTH COUNTY (South Shore)
  // ============================================
  {
    name: "Plymouth Bay Retirement Community",
    slug: "plymouth-bay-retirement-community",
    type: "continuing-care",
    address: "125 Sandwich Street",
    city: "Plymouth",
    state: "MA",
    zipCode: "02360",
    county: "Plymouth",
    phone: "(508) 555-0501",
    email: "info@plymouthbaycc.com",
    description: "Historic waterfront CCRC in America's Hometown offering comprehensive senior living options.",
    capacity: 275,
    yearEstablished: 1992,
    overallRating: 4.5,
    reviewCount: 198,
    priceRangeMin: 4000,
    priceRangeMax: 14000,
    acceptsMedicare: true,
    acceptsPrivatePay: true,
    services: ["Independent living", "Assisted living", "Skilled nursing", "Memory care"],
    amenities: ["Waterfront views", "Marina", "Fine dining", "Fitness center", "Library"],
    status: "published",
  },
  {
    name: "Colony House Nursing & Rehabilitation Center",
    slug: "colony-house-nursing-rehabilitation",
    type: "nursing-home",
    address: "555 Belmont Street",
    city: "Brockton",
    state: "MA",
    zipCode: "02301",
    county: "Plymouth",
    phone: "(508) 555-0502",
    email: "admissions@brocktonhc.com",
    description: "Full-service skilled nursing facility providing rehabilitation, long-term care, and specialized programs.",
    capacity: 190,
    yearEstablished: 1978,
    overallRating: 4.0,
    reviewCount: 156,
    priceRangeMin: 310,
    priceRangeMax: 400,
    acceptsMedicare: true,
    acceptsMedicaid: true,
    acceptsPrivatePay: true,
    services: ["Skilled nursing", "Physical therapy", "Occupational therapy", "Wound care"],
    amenities: ["Therapy gym", "Outdoor courtyard", "Chapel", "Activity rooms"],
    status: "published",
  },
  {
    name: "Allerton House at The Village at Duxbury",
    slug: "allerton-house-village-at-duxbury",
    type: "assisted-living",
    address: "200 Tremont Street",
    city: "Duxbury",
    state: "MA",
    zipCode: "02332",
    county: "Plymouth",
    phone: "(781) 555-0503",
    email: "info@duxburyshores.com",
    description: "Upscale coastal assisted living community offering personalized care with ocean views.",
    capacity: 85,
    yearEstablished: 2016,
    overallRating: 4.7,
    reviewCount: 72,
    priceRangeMin: 6500,
    priceRangeMax: 10500,
    acceptsPrivatePay: true,
    acceptsLongTermInsurance: true,
    services: ["Personal care", "Medication management", "Wellness programs", "Transportation"],
    amenities: ["Ocean views", "Walking paths", "Fine dining", "Fitness center", "Spa"],
    status: "published",
  },
  {
    name: "Sunrise of Cohasset",
    slug: "sunrise-of-cohasset",
    type: "memory-care",
    address: "78 Ocean Street",
    city: "Marshfield",
    state: "MA",
    zipCode: "02050",
    county: "Plymouth",
    phone: "(781) 555-0504",
    email: "info@marshfieldmemory.com",
    description: "Specialized memory care residence in a peaceful South Shore setting with innovative programming.",
    capacity: 40,
    yearEstablished: 2018,
    overallRating: 4.8,
    reviewCount: 45,
    priceRangeMin: 7800,
    priceRangeMax: 11500,
    acceptsPrivatePay: true,
    services: ["Memory care", "Cognitive programs", "Art therapy", "Music therapy"],
    amenities: ["Secured gardens", "Activity rooms", "Sensory spaces", "Family areas"],
    specializations: ["Alzheimer's", "Dementia care"],
    status: "published",
  },
  {
    name: "Hingham Harbor Independent Living",
    slug: "hingham-harbor-independent-living",
    type: "independent-living",
    address: "350 Main Street",
    city: "Hingham",
    state: "MA",
    zipCode: "02043",
    county: "Plymouth",
    phone: "(781) 555-0505",
    email: "info@hinghamharbor.com",
    description: "Premier independent living near Hingham Harbor with easy access to Boston via ferry.",
    capacity: 145,
    yearEstablished: 2012,
    overallRating: 4.6,
    reviewCount: 98,
    priceRangeMin: 3200,
    priceRangeMax: 6000,
    acceptsPrivatePay: true,
    services: ["Housekeeping", "Transportation", "Dining options", "Fitness programs"],
    amenities: ["Harbor views", "Walking trails", "Fitness center", "Library", "Game room"],
    status: "published",
  },

  // ============================================
  // BRISTOL COUNTY (Fall River, New Bedford)
  // ============================================
  {
    name: "Charlton Memorial Hospital Extended Care",
    slug: "charlton-memorial-extended-care",
    type: "nursing-home",
    address: "450 Prospect Street",
    city: "Fall River",
    state: "MA",
    zipCode: "02720",
    county: "Bristol",
    phone: "(508) 555-0601",
    email: "info@fallriversenior.com",
    description: "Comprehensive skilled nursing and rehabilitation facility serving the Greater Fall River area.",
    capacity: 170,
    yearEstablished: 1972,
    overallRating: 4.1,
    reviewCount: 145,
    priceRangeMin: 300,
    priceRangeMax: 390,
    acceptsMedicare: true,
    acceptsMedicaid: true,
    acceptsPrivatePay: true,
    services: ["Skilled nursing", "Rehabilitation", "Long-term care", "Respite care"],
    amenities: ["Therapy gym", "Outdoor courtyard", "Activity room", "Chapel"],
    status: "published",
  },
  {
    name: "Atria Fairhaven",
    slug: "atria-fairhaven",
    type: "assisted-living",
    address: "225 Union Street",
    city: "New Bedford",
    state: "MA",
    zipCode: "02740",
    county: "Bristol",
    phone: "(508) 555-0602",
    email: "info@newbedfordal.com",
    description: "Waterfront assisted living in historic New Bedford offering culturally sensitive care.",
    capacity: 95,
    yearEstablished: 2014,
    overallRating: 4.4,
    reviewCount: 87,
    priceRangeMin: 5200,
    priceRangeMax: 8500,
    acceptsPrivatePay: true,
    acceptsMedicaid: true,
    services: ["Personal care", "Medication management", "Cultural programs", "Transportation"],
    amenities: ["Harbor views", "Portuguese cuisine", "Library", "Garden", "Activity room"],
    status: "published",
  },
  {
    name: "Brookdale Attleboro",
    slug: "brookdale-attleboro",
    type: "memory-care",
    address: "100 Park Street",
    city: "Attleboro",
    state: "MA",
    zipCode: "02703",
    county: "Bristol",
    phone: "(508) 555-0603",
    email: "info@attleboromemory.com",
    description: "Dedicated memory care community providing specialized dementia care in a secure environment.",
    capacity: 52,
    yearEstablished: 2015,
    overallRating: 4.6,
    reviewCount: 62,
    priceRangeMin: 7000,
    priceRangeMax: 10500,
    acceptsPrivatePay: true,
    services: ["Memory care", "Cognitive therapy", "Sensory programs", "Family support"],
    amenities: ["Secured gardens", "Activity spaces", "Spa services", "Family lounge"],
    specializations: ["Alzheimer's", "Dementia"],
    status: "published",
  },
  {
    name: "Taunton Green Independent Living",
    slug: "taunton-green-independent-living",
    type: "independent-living",
    address: "75 Broadway",
    city: "Taunton",
    state: "MA",
    zipCode: "02780",
    county: "Bristol",
    phone: "(508) 555-0604",
    email: "info@tauntongreen.com",
    description: "Active adult community in downtown Taunton offering affordable independent living options.",
    capacity: 125,
    yearEstablished: 2009,
    overallRating: 4.2,
    reviewCount: 78,
    priceRangeMin: 2200,
    priceRangeMax: 4000,
    acceptsPrivatePay: true,
    services: ["Housekeeping", "Transportation", "Social activities", "Fitness programs"],
    amenities: ["Community room", "Fitness center", "Library", "Garden", "Computer lab"],
    status: "published",
  },
  {
    name: "Rehoboth CCRC",
    slug: "rehoboth-ccrc",
    type: "continuing-care",
    address: "200 Winthrop Street",
    city: "Rehoboth",
    state: "MA",
    zipCode: "02769",
    county: "Bristol",
    phone: "(508) 555-0605",
    email: "info@rehobothccrc.com",
    description: "Rural continuing care retirement community on a scenic campus offering all levels of care.",
    capacity: 240,
    yearEstablished: 1995,
    overallRating: 4.3,
    reviewCount: 167,
    priceRangeMin: 3800,
    priceRangeMax: 13000,
    acceptsMedicare: true,
    acceptsPrivatePay: true,
    services: ["Independent living", "Assisted living", "Memory care", "Skilled nursing"],
    amenities: ["Walking trails", "Farm garden", "Fitness center", "Dining venues", "Chapel"],
    status: "published",
  },

  // ============================================
  // WORCESTER COUNTY (Central MA)
  // ============================================
  {
    name: "Life Care Center of Auburn",
    slug: "life-care-center-auburn",
    type: "nursing-home",
    address: "880 Main Street",
    city: "Worcester",
    state: "MA",
    zipCode: "01610",
    county: "Worcester",
    phone: "(508) 555-0701",
    email: "info@worcestersenior.com",
    description: "Major skilled nursing and rehabilitation center serving Central Massachusetts.",
    capacity: 220,
    yearEstablished: 1968,
    overallRating: 4.2,
    reviewCount: 234,
    priceRangeMin: 310,
    priceRangeMax: 400,
    acceptsMedicare: true,
    acceptsMedicaid: true,
    acceptsPrivatePay: true,
    services: ["Skilled nursing", "Physical therapy", "Occupational therapy", "Wound care", "Ventilator care"],
    amenities: ["Therapy gym", "Outdoor courtyard", "Chapel", "Activity rooms", "Family lounge"],
    status: "published",
  },
  {
    name: "Christopher Heights of Worcester",
    slug: "christopher-heights-worcester",
    type: "assisted-living",
    address: "355 Grafton Street",
    city: "Shrewsbury",
    state: "MA",
    zipCode: "01545",
    county: "Worcester",
    phone: "(508) 555-0702",
    email: "info@shrewsburyal.com",
    description: "Modern assisted living community offering personalized care in a welcoming environment.",
    capacity: 100,
    yearEstablished: 2012,
    overallRating: 4.5,
    reviewCount: 112,
    priceRangeMin: 5500,
    priceRangeMax: 9000,
    acceptsPrivatePay: true,
    acceptsLongTermInsurance: true,
    services: ["Personal care", "Medication management", "Wellness programs", "Memory support"],
    amenities: ["Garden courtyard", "Fitness center", "Library", "Art studio", "Theater"],
    status: "published",
  },
  {
    name: "Benchmark Senior Living at Shrewsbury Crossings",
    slug: "benchmark-shrewsbury-crossings",
    type: "memory-care",
    address: "165 Lancaster Street",
    city: "Leominster",
    state: "MA",
    zipCode: "01453",
    county: "Worcester",
    phone: "(978) 555-0703",
    email: "info@leominstermemory.com",
    description: "Purpose-built memory care community providing specialized dementia care and support.",
    capacity: 48,
    yearEstablished: 2016,
    overallRating: 4.7,
    reviewCount: 58,
    priceRangeMin: 7200,
    priceRangeMax: 10500,
    acceptsPrivatePay: true,
    services: ["Memory care", "Cognitive therapy", "Art therapy", "Family programs"],
    amenities: ["Secured gardens", "Activity rooms", "Sensory spaces", "Family areas"],
    specializations: ["Alzheimer's", "Dementia care", "Behavioral support"],
    status: "published",
  },
  {
    name: "Westborough Senior Village",
    slug: "westborough-senior-village",
    type: "independent-living",
    address: "45 East Main Street",
    city: "Westborough",
    state: "MA",
    zipCode: "01581",
    county: "Worcester",
    phone: "(508) 555-0704",
    email: "info@westboroughsenior.com",
    description: "Active adult community in charming downtown Westborough with resort-style amenities.",
    capacity: 165,
    yearEstablished: 2008,
    overallRating: 4.6,
    reviewCount: 123,
    priceRangeMin: 2800,
    priceRangeMax: 5200,
    acceptsPrivatePay: true,
    services: ["Housekeeping", "Transportation", "Fitness programs", "Social activities"],
    amenities: ["Pool", "Fitness center", "Clubhouse", "Walking trails", "Dog park"],
    status: "published",
  },
  {
    name: "Sturbridge CCRC",
    slug: "sturbridge-ccrc",
    type: "continuing-care",
    address: "380 Main Street",
    city: "Sturbridge",
    state: "MA",
    zipCode: "01566",
    county: "Worcester",
    phone: "(508) 555-0705",
    email: "info@sturbridgeccrc.com",
    description: "Charming New England CCRC near Old Sturbridge Village offering comprehensive senior living.",
    capacity: 280,
    yearEstablished: 1990,
    overallRating: 4.4,
    reviewCount: 189,
    priceRangeMin: 4000,
    priceRangeMax: 14000,
    acceptsMedicare: true,
    acceptsPrivatePay: true,
    services: ["Independent living", "Assisted living", "Memory care", "Skilled nursing"],
    amenities: ["Historic setting", "Gardens", "Multiple dining", "Fitness center", "Library"],
    status: "published",
  },
  {
    name: "HealthAlliance-Clinton Hospital TCU",
    slug: "healthalliance-clinton-hospital-tcu",
    type: "nursing-home",
    address: "75 Whalon Street",
    city: "Fitchburg",
    state: "MA",
    zipCode: "01420",
    county: "Worcester",
    phone: "(978) 555-0706",
    email: "info@fitchburgrehab.com",
    description: "Skilled nursing and rehabilitation center specializing in post-acute care and recovery.",
    capacity: 150,
    yearEstablished: 1975,
    overallRating: 4.0,
    reviewCount: 134,
    priceRangeMin: 300,
    priceRangeMax: 385,
    acceptsMedicare: true,
    acceptsMedicaid: true,
    acceptsPrivatePay: true,
    services: ["Skilled nursing", "Physical therapy", "Occupational therapy", "Speech therapy"],
    amenities: ["Therapy gym", "Outdoor areas", "Chapel", "Activity room"],
    status: "published",
  },

  // ============================================
  // HAMPDEN COUNTY (Springfield area)
  // ============================================
  {
    name: "The Wellington at Springfield",
    slug: "the-wellington-at-springfield",
    type: "assisted-living",
    address: "500 State Street",
    city: "Springfield",
    state: "MA",
    zipCode: "01103",
    county: "Hampden",
    phone: "(413) 555-0801",
    email: "info@springfieldsenior.com",
    description: "Downtown Springfield assisted living offering culturally diverse care and urban amenities.",
    capacity: 115,
    yearEstablished: 2010,
    overallRating: 4.3,
    reviewCount: 98,
    priceRangeMin: 4800,
    priceRangeMax: 7800,
    acceptsPrivatePay: true,
    acceptsMedicaid: true,
    services: ["Personal care", "Medication management", "Transportation", "Cultural programs"],
    amenities: ["Downtown location", "Activity room", "Garden", "Library", "Dining room"],
    status: "published",
  },
  {
    name: "Heritage Hall East",
    slug: "heritage-hall-east-agawam",
    type: "nursing-home",
    address: "280 Maple Street",
    city: "Holyoke",
    state: "MA",
    zipCode: "01040",
    county: "Hampden",
    phone: "(413) 555-0802",
    email: "info@holyokehc.com",
    description: "Full-service skilled nursing facility providing comprehensive care and rehabilitation.",
    capacity: 185,
    yearEstablished: 1970,
    overallRating: 4.1,
    reviewCount: 156,
    priceRangeMin: 295,
    priceRangeMax: 380,
    acceptsMedicare: true,
    acceptsMedicaid: true,
    acceptsPrivatePay: true,
    services: ["Skilled nursing", "Rehabilitation", "Long-term care", "Respite care"],
    amenities: ["Therapy gym", "Courtyard", "Chapel", "Activity rooms"],
    status: "published",
  },
  {
    name: "Armbrook Village",
    slug: "armbrook-village-westfield",
    type: "memory-care",
    address: "88 Longmeadow Street",
    city: "Longmeadow",
    state: "MA",
    zipCode: "01106",
    county: "Hampden",
    phone: "(413) 555-0803",
    email: "info@longmeadowmemory.com",
    description: "Upscale memory care community in prestigious Longmeadow offering specialized dementia care.",
    capacity: 44,
    yearEstablished: 2017,
    overallRating: 4.8,
    reviewCount: 48,
    priceRangeMin: 7500,
    priceRangeMax: 11000,
    acceptsPrivatePay: true,
    services: ["Memory care", "Cognitive therapy", "Music therapy", "Family support"],
    amenities: ["Secured gardens", "Activity spaces", "Spa", "Family areas"],
    specializations: ["Alzheimer's", "Dementia"],
    status: "published",
  },
  {
    name: "Westfield Independent Living",
    slug: "westfield-independent-living",
    type: "independent-living",
    address: "150 Elm Street",
    city: "Westfield",
    state: "MA",
    zipCode: "01085",
    county: "Hampden",
    phone: "(413) 555-0804",
    email: "info@westfieldsenior.com",
    description: "Affordable independent living for active seniors in the heart of Westfield.",
    capacity: 120,
    yearEstablished: 2006,
    overallRating: 4.3,
    reviewCount: 89,
    priceRangeMin: 2000,
    priceRangeMax: 3800,
    acceptsPrivatePay: true,
    services: ["Housekeeping", "Transportation", "Social activities", "Wellness programs"],
    amenities: ["Community room", "Fitness area", "Garden", "Library", "Computer room"],
    status: "published",
  },
  {
    name: "Chicopee CCRC",
    slug: "chicopee-ccrc",
    type: "continuing-care",
    address: "300 Memorial Drive",
    city: "Chicopee",
    state: "MA",
    zipCode: "01020",
    county: "Hampden",
    phone: "(413) 555-0805",
    email: "info@chicopeeccrc.com",
    description: "Comprehensive continuing care retirement community serving the Pioneer Valley.",
    capacity: 260,
    yearEstablished: 1988,
    overallRating: 4.2,
    reviewCount: 178,
    priceRangeMin: 3500,
    priceRangeMax: 12000,
    acceptsMedicare: true,
    acceptsMedicaid: true,
    acceptsPrivatePay: true,
    services: ["Independent living", "Assisted living", "Skilled nursing", "Memory care"],
    amenities: ["Multiple dining", "Pool", "Fitness center", "Library", "Chapel"],
    status: "published",
  },

  // ============================================
  // HAMPSHIRE COUNTY (Northampton, Amherst)
  // ============================================
  {
    name: "Christopher Heights of Northampton",
    slug: "christopher-heights-northampton",
    type: "assisted-living",
    address: "95 Pleasant Street",
    city: "Northampton",
    state: "MA",
    zipCode: "01060",
    county: "Hampshire",
    phone: "(413) 555-0901",
    email: "info@northamptonsenior.com",
    description: "Progressive assisted living in vibrant downtown Northampton near arts and culture.",
    capacity: 78,
    yearEstablished: 2013,
    overallRating: 4.7,
    reviewCount: 67,
    priceRangeMin: 5800,
    priceRangeMax: 9200,
    acceptsPrivatePay: true,
    services: ["Personal care", "Medication management", "Arts programs", "Transportation"],
    amenities: ["Downtown access", "Garden", "Art studio", "Library", "Music room"],
    status: "published",
  },
  {
    name: "Center for Extended Care at Amherst",
    slug: "center-extended-care-amherst",
    type: "nursing-home",
    address: "220 Triangle Street",
    city: "Amherst",
    state: "MA",
    zipCode: "01002",
    county: "Hampshire",
    phone: "(413) 555-0902",
    email: "info@amhersthc.com",
    description: "Skilled nursing facility in the Five College area offering rehabilitation and long-term care.",
    capacity: 135,
    yearEstablished: 1982,
    overallRating: 4.3,
    reviewCount: 112,
    priceRangeMin: 305,
    priceRangeMax: 395,
    acceptsMedicare: true,
    acceptsMedicaid: true,
    acceptsPrivatePay: true,
    services: ["Skilled nursing", "Physical therapy", "Occupational therapy", "Wound care"],
    amenities: ["Therapy gym", "Gardens", "Chapel", "Activity room"],
    status: "published",
  },
  {
    name: "Loomis Lakeside at Reeds Landing",
    slug: "loomis-lakeside-reeds-landing",
    type: "memory-care",
    address: "55 King Street",
    city: "Northampton",
    state: "MA",
    zipCode: "01060",
    county: "Hampshire",
    phone: "(413) 555-0903",
    email: "info@pioneervalleymemory.com",
    description: "Innovative memory care community with arts-based programming in the Pioneer Valley.",
    capacity: 38,
    yearEstablished: 2019,
    overallRating: 4.9,
    reviewCount: 35,
    priceRangeMin: 7800,
    priceRangeMax: 11500,
    acceptsPrivatePay: true,
    services: ["Memory care", "Art therapy", "Music therapy", "Horticultural therapy"],
    amenities: ["Secured gardens", "Art studio", "Sensory spaces", "Family areas"],
    specializations: ["Alzheimer's", "Dementia", "Creative arts therapy"],
    status: "published",
  },
  {
    name: "Hadley Senior Village",
    slug: "hadley-senior-village",
    type: "independent-living",
    address: "280 Russell Street",
    city: "Hadley",
    state: "MA",
    zipCode: "01035",
    county: "Hampshire",
    phone: "(413) 555-0904",
    email: "info@hadleysenior.com",
    description: "Farm-to-table independent living community in the agricultural heart of the Valley.",
    capacity: 110,
    yearEstablished: 2011,
    overallRating: 4.5,
    reviewCount: 78,
    priceRangeMin: 2400,
    priceRangeMax: 4500,
    acceptsPrivatePay: true,
    services: ["Housekeeping", "Transportation", "Farm programs", "Fitness classes"],
    amenities: ["Community garden", "Farm stand", "Walking trails", "Fitness center"],
    status: "published",
  },

  // ============================================
  // FRANKLIN COUNTY (Western MA)
  // ============================================
  {
    name: "Buckley Greenfield Healthcare Center",
    slug: "buckley-greenfield-healthcare",
    type: "assisted-living",
    address: "175 Main Street",
    city: "Greenfield",
    state: "MA",
    zipCode: "01301",
    county: "Franklin",
    phone: "(413) 555-1001",
    email: "info@greenfieldsenior.com",
    description: "Charming assisted living in downtown Greenfield offering personalized care and community connection.",
    capacity: 65,
    yearEstablished: 2014,
    overallRating: 4.5,
    reviewCount: 54,
    priceRangeMin: 5000,
    priceRangeMax: 7800,
    acceptsPrivatePay: true,
    services: ["Personal care", "Medication management", "Transportation", "Social programs"],
    amenities: ["Downtown access", "Garden", "Library", "Activity room"],
    status: "published",
  },
  {
    name: "Franklin County Nursing Home",
    slug: "franklin-county-nursing-home",
    type: "nursing-home",
    address: "250 Federal Street",
    city: "Greenfield",
    state: "MA",
    zipCode: "01301",
    county: "Franklin",
    phone: "(413) 555-1002",
    email: "info@franklincountynursing.com",
    description: "Community-focused skilled nursing facility serving Franklin County families.",
    capacity: 120,
    yearEstablished: 1965,
    overallRating: 4.0,
    reviewCount: 98,
    priceRangeMin: 280,
    priceRangeMax: 360,
    acceptsMedicare: true,
    acceptsMedicaid: true,
    acceptsPrivatePay: true,
    services: ["Skilled nursing", "Rehabilitation", "Long-term care", "Hospice support"],
    amenities: ["Therapy room", "Courtyard", "Chapel", "Activity room"],
    status: "published",
  },
  {
    name: "Deerfield Independent Living",
    slug: "deerfield-independent-living",
    type: "independent-living",
    address: "45 Old Main Street",
    city: "Deerfield",
    state: "MA",
    zipCode: "01342",
    county: "Franklin",
    phone: "(413) 555-1003",
    email: "info@deerfieldsenior.com",
    description: "Historic New England setting for active seniors in charming Old Deerfield.",
    capacity: 75,
    yearEstablished: 2009,
    overallRating: 4.6,
    reviewCount: 45,
    priceRangeMin: 2200,
    priceRangeMax: 4000,
    acceptsPrivatePay: true,
    services: ["Housekeeping", "Transportation", "Cultural programs", "Wellness activities"],
    amenities: ["Historic setting", "Gardens", "Library", "Community room"],
    status: "published",
  },

  // ============================================
  // BERKSHIRE COUNTY (Western MA mountains)
  // ============================================
  {
    name: "Kimball Farms",
    slug: "kimball-farms-pittsfield",
    type: "assisted-living",
    address: "445 North Street",
    city: "Pittsfield",
    state: "MA",
    zipCode: "01201",
    county: "Berkshire",
    phone: "(413) 555-1101",
    email: "info@pittsfieldsenior.com",
    description: "Mountain-view assisted living in the heart of the Berkshires with cultural programming.",
    capacity: 85,
    yearEstablished: 2011,
    overallRating: 4.4,
    reviewCount: 72,
    priceRangeMin: 5200,
    priceRangeMax: 8200,
    acceptsPrivatePay: true,
    services: ["Personal care", "Medication management", "Cultural outings", "Transportation"],
    amenities: ["Mountain views", "Garden", "Art room", "Library", "Theater"],
    status: "published",
  },
  {
    name: "Berkshire Place Skilled Nursing",
    slug: "berkshire-place-skilled-nursing",
    type: "nursing-home",
    address: "88 Wahconah Street",
    city: "Pittsfield",
    state: "MA",
    zipCode: "01201",
    county: "Berkshire",
    phone: "(413) 555-1102",
    email: "info@berkshirehc.com",
    description: "Regional skilled nursing and rehabilitation center serving the Berkshire community.",
    capacity: 155,
    yearEstablished: 1975,
    overallRating: 4.1,
    reviewCount: 134,
    priceRangeMin: 290,
    priceRangeMax: 375,
    acceptsMedicare: true,
    acceptsMedicaid: true,
    acceptsPrivatePay: true,
    services: ["Skilled nursing", "Physical therapy", "Wound care", "Respite care"],
    amenities: ["Therapy gym", "Outdoor terrace", "Chapel", "Activity room"],
    status: "published",
  },
  {
    name: "Sweetwood of Williamstown",
    slug: "sweetwood-of-williamstown",
    type: "memory-care",
    address: "55 Walker Street",
    city: "Lenox",
    state: "MA",
    zipCode: "01240",
    county: "Berkshire",
    phone: "(413) 555-1103",
    email: "info@lenoxmemory.com",
    description: "Boutique memory care in the cultural heart of the Berkshires with music and arts programming.",
    capacity: 32,
    yearEstablished: 2018,
    overallRating: 4.9,
    reviewCount: 28,
    priceRangeMin: 8000,
    priceRangeMax: 12000,
    acceptsPrivatePay: true,
    services: ["Memory care", "Music therapy", "Art therapy", "Cultural programs"],
    amenities: ["Gardens", "Music room", "Art studio", "Family areas"],
    specializations: ["Alzheimer's", "Dementia", "Music therapy"],
    status: "published",
  },
  {
    name: "Great Barrington Independent Living",
    slug: "great-barrington-independent-living",
    type: "independent-living",
    address: "280 Main Street",
    city: "Great Barrington",
    state: "MA",
    zipCode: "01230",
    county: "Berkshire",
    phone: "(413) 555-1104",
    email: "info@gbsenior.com",
    description: "Active adult community in charming Great Barrington near outdoor recreation and culture.",
    capacity: 95,
    yearEstablished: 2010,
    overallRating: 4.5,
    reviewCount: 67,
    priceRangeMin: 2400,
    priceRangeMax: 4500,
    acceptsPrivatePay: true,
    services: ["Housekeeping", "Transportation", "Outdoor programs", "Cultural activities"],
    amenities: ["Mountain views", "Walking trails", "Fitness room", "Library"],
    status: "published",
  },
  {
    name: "Berkshire Hills CCRC",
    slug: "berkshire-hills-ccrc",
    type: "continuing-care",
    address: "500 South Street",
    city: "Pittsfield",
    state: "MA",
    zipCode: "01201",
    county: "Berkshire",
    phone: "(413) 555-1105",
    email: "info@berkshirehillsccrc.com",
    description: "Comprehensive CCRC on a scenic Berkshire campus offering all levels of care.",
    capacity: 220,
    yearEstablished: 1985,
    overallRating: 4.3,
    reviewCount: 156,
    priceRangeMin: 3800,
    priceRangeMax: 13000,
    acceptsMedicare: true,
    acceptsPrivatePay: true,
    services: ["Independent living", "Assisted living", "Memory care", "Skilled nursing"],
    amenities: ["Mountain views", "Gardens", "Pool", "Fitness center", "Dining venues"],
    status: "published",
  },

  // ============================================
  // BARNSTABLE COUNTY (Cape Cod)
  // ============================================
  {
    name: "Atria Woodbriar Place",
    slug: "atria-woodbriar-place",
    type: "assisted-living",
    address: "300 Main Street",
    city: "Hyannis",
    state: "MA",
    zipCode: "02601",
    county: "Barnstable",
    phone: "(508) 555-1201",
    email: "info@capecodsenior.com",
    description: "Coastal assisted living in the heart of Cape Cod offering personalized care with ocean breezes.",
    capacity: 105,
    yearEstablished: 2008,
    overallRating: 4.6,
    reviewCount: 134,
    priceRangeMin: 6000,
    priceRangeMax: 9500,
    acceptsPrivatePay: true,
    acceptsLongTermInsurance: true,
    services: ["Personal care", "Medication management", "Beach outings", "Transportation"],
    amenities: ["Near beaches", "Garden", "Library", "Activity room", "Dining room"],
    status: "published",
  },
  {
    name: "JML Care Center",
    slug: "jml-care-center-falmouth",
    type: "nursing-home",
    address: "175 Ter Heun Drive",
    city: "Falmouth",
    state: "MA",
    zipCode: "02540",
    county: "Barnstable",
    phone: "(508) 555-1202",
    email: "info@falmouthsnf.com",
    description: "Skilled nursing and rehabilitation facility serving Upper Cape communities.",
    capacity: 140,
    yearEstablished: 1980,
    overallRating: 4.2,
    reviewCount: 145,
    priceRangeMin: 320,
    priceRangeMax: 420,
    acceptsMedicare: true,
    acceptsMedicaid: true,
    acceptsPrivatePay: true,
    services: ["Skilled nursing", "Physical therapy", "Occupational therapy", "Wound care"],
    amenities: ["Garden courtyard", "Therapy gym", "Chapel", "Activity room"],
    status: "published",
  },
  {
    name: "Maplewood at Brewster",
    slug: "maplewood-at-brewster",
    type: "memory-care",
    address: "80 Rock Harbor Road",
    city: "Orleans",
    state: "MA",
    zipCode: "02653",
    county: "Barnstable",
    phone: "(508) 555-1203",
    email: "info@orleansmemory.com",
    description: "Seaside memory care community on the Lower Cape offering specialized dementia care.",
    capacity: 42,
    yearEstablished: 2016,
    overallRating: 4.8,
    reviewCount: 52,
    priceRangeMin: 8500,
    priceRangeMax: 12500,
    acceptsPrivatePay: true,
    services: ["Memory care", "Nautical therapy", "Art therapy", "Beach walks"],
    amenities: ["Ocean views", "Secured gardens", "Activity spaces", "Sensory room"],
    specializations: ["Alzheimer's", "Dementia"],
    status: "published",
  },
  {
    name: "Sandwich Independent Living",
    slug: "sandwich-independent-living",
    type: "independent-living",
    address: "125 Route 6A",
    city: "Sandwich",
    state: "MA",
    zipCode: "02563",
    county: "Barnstable",
    phone: "(508) 555-1204",
    email: "info@sandwichsenior.com",
    description: "Historic village setting for active seniors in America's oldest town on Cape Cod.",
    capacity: 130,
    yearEstablished: 2007,
    overallRating: 4.5,
    reviewCount: 98,
    priceRangeMin: 2800,
    priceRangeMax: 5200,
    acceptsPrivatePay: true,
    services: ["Housekeeping", "Transportation", "Beach access", "Cultural programs"],
    amenities: ["Historic setting", "Gardens", "Fitness center", "Library", "Game room"],
    status: "published",
  },
  {
    name: "Brewster CCRC",
    slug: "brewster-ccrc",
    type: "continuing-care",
    address: "2000 Main Street",
    city: "Brewster",
    state: "MA",
    zipCode: "02631",
    county: "Barnstable",
    phone: "(508) 555-1205",
    email: "info@brewsterccrc.com",
    description: "Comprehensive continuing care on a beautiful Cape Cod campus near beaches and nature trails.",
    capacity: 250,
    yearEstablished: 1992,
    overallRating: 4.6,
    reviewCount: 189,
    priceRangeMin: 4500,
    priceRangeMax: 15000,
    acceptsMedicare: true,
    acceptsPrivatePay: true,
    services: ["Independent living", "Assisted living", "Memory care", "Skilled nursing"],
    amenities: ["Nature trails", "Pool", "Fitness center", "Multiple dining", "Library"],
    status: "published",
  },
  {
    name: "Orleans Assisted Living",
    slug: "orleans-assisted-living",
    type: "assisted-living",
    address: "45 Stage Harbor Road",
    city: "Chatham",
    state: "MA",
    zipCode: "02633",
    county: "Barnstable",
    phone: "(508) 555-1206",
    email: "info@chathamshores.com",
    description: "Upscale assisted living in picturesque Chatham with personalized care and coastal charm.",
    capacity: 68,
    yearEstablished: 2015,
    overallRating: 4.9,
    reviewCount: 56,
    priceRangeMin: 7200,
    priceRangeMax: 11500,
    acceptsPrivatePay: true,
    acceptsLongTermInsurance: true,
    services: ["Personal care", "Medication management", "Concierge", "Transportation"],
    amenities: ["Harbor views", "Fine dining", "Garden", "Library", "Spa"],
    status: "published",
  },

  // ============================================
  // DUKES COUNTY (Martha's Vineyard)
  // ============================================
  {
    name: "Martha's Vineyard Senior Living",
    slug: "marthas-vineyard-senior-living",
    type: "assisted-living",
    address: "9 Hospital Road",
    city: "Oak Bluffs",
    state: "MA",
    zipCode: "02557",
    county: "Dukes",
    phone: "(508) 555-1301",
    email: "info@mvsenior.com",
    description: "Island assisted living community offering personalized care year-round on Martha's Vineyard.",
    capacity: 48,
    yearEstablished: 2012,
    overallRating: 4.7,
    reviewCount: 38,
    priceRangeMin: 7500,
    priceRangeMax: 12000,
    acceptsPrivatePay: true,
    services: ["Personal care", "Medication management", "Island transportation", "Wellness programs"],
    amenities: ["Island setting", "Garden", "Ocean views", "Library", "Activity room"],
    status: "published",
  },
  {
    name: "Vineyard Haven Skilled Nursing",
    slug: "vineyard-haven-skilled-nursing",
    type: "nursing-home",
    address: "25 Causeway Road",
    city: "Vineyard Haven",
    state: "MA",
    zipCode: "02568",
    county: "Dukes",
    phone: "(508) 555-1302",
    email: "info@vineyardhavensnf.com",
    description: "Island skilled nursing facility providing comprehensive care for Martha's Vineyard residents.",
    capacity: 60,
    yearEstablished: 1985,
    overallRating: 4.3,
    reviewCount: 45,
    priceRangeMin: 380,
    priceRangeMax: 480,
    acceptsMedicare: true,
    acceptsMedicaid: true,
    acceptsPrivatePay: true,
    services: ["Skilled nursing", "Rehabilitation", "Long-term care", "Respite care"],
    amenities: ["Ocean views", "Therapy room", "Garden", "Chapel"],
    status: "published",
  },

  // ============================================
  // NANTUCKET COUNTY
  // ============================================
  {
    name: "Nantucket Senior Care",
    slug: "nantucket-senior-care",
    type: "assisted-living",
    address: "57 Prospect Street",
    city: "Nantucket",
    state: "MA",
    zipCode: "02554",
    county: "Nantucket",
    phone: "(508) 555-1401",
    email: "info@nantucketsenior.com",
    description: "Historic island setting for assisted living on Nantucket with personalized care services.",
    capacity: 36,
    yearEstablished: 2010,
    overallRating: 4.6,
    reviewCount: 28,
    priceRangeMin: 8500,
    priceRangeMax: 14000,
    acceptsPrivatePay: true,
    services: ["Personal care", "Medication management", "Island activities", "Transportation"],
    amenities: ["Historic setting", "Garden", "Ocean views", "Library"],
    status: "published",
  },
  {
    name: "Our Island Home",
    slug: "our-island-home-nantucket",
    type: "nursing-home",
    address: "4 Sherburne Turnpike",
    city: "Nantucket",
    state: "MA",
    zipCode: "02554",
    county: "Nantucket",
    phone: "(508) 555-1402",
    email: "info@ourislandhome.com",
    description: "Nantucket's municipal skilled nursing facility providing comprehensive care for island residents.",
    capacity: 45,
    yearEstablished: 1910,
    overallRating: 4.4,
    reviewCount: 34,
    priceRangeMin: 400,
    priceRangeMax: 520,
    acceptsMedicare: true,
    acceptsMedicaid: true,
    acceptsPrivatePay: true,
    services: ["Skilled nursing", "Long-term care", "Rehabilitation", "Hospice support"],
    amenities: ["Historic building", "Garden courtyard", "Ocean breezes", "Activity room"],
    status: "published",
  },
];
