// Massachusetts Locations Seed Data
// All 351 municipalities organized by county with real data

export interface MaLocationSeed {
  name: string;
  slug: string;
  county: string;
  region: string;
  zipCodes: string[];
  population: number;
  isCity: "yes" | "no";
}

// Major cities and towns for initial launch - focusing on high-population areas first
export const maLocationSeeds: MaLocationSeed[] = [
  // Suffolk County - Boston Metro
  { name: "Boston", slug: "boston", county: "Suffolk", region: "Greater Boston", zipCodes: ["02101", "02102", "02103", "02104", "02105", "02106", "02107", "02108", "02109", "02110", "02111", "02112", "02113", "02114", "02115", "02116", "02117", "02118", "02119", "02120", "02121", "02122", "02123", "02124", "02125", "02126", "02127", "02128", "02129", "02130", "02131", "02132", "02133", "02134", "02135", "02136", "02137", "02163", "02196", "02199", "02201", "02203", "02204", "02205", "02206", "02210", "02211", "02212", "02215", "02217", "02222", "02241", "02266", "02283", "02284", "02293", "02297", "02298"], population: 675647, isCity: "yes" },
  { name: "Chelsea", slug: "chelsea", county: "Suffolk", region: "Greater Boston", zipCodes: ["02150"], population: 40787, isCity: "yes" },
  { name: "Revere", slug: "revere", county: "Suffolk", region: "Greater Boston", zipCodes: ["02151"], population: 62186, isCity: "yes" },
  { name: "Winthrop", slug: "winthrop", county: "Suffolk", region: "Greater Boston", zipCodes: ["02152"], population: 18544, isCity: "no" },

  // Middlesex County - Major Cities
  { name: "Cambridge", slug: "cambridge", county: "Middlesex", region: "Greater Boston", zipCodes: ["02138", "02139", "02140", "02141", "02142"], population: 118403, isCity: "yes" },
  { name: "Lowell", slug: "lowell", county: "Middlesex", region: "Merrimack Valley", zipCodes: ["01850", "01851", "01852", "01853", "01854"], population: 115554, isCity: "yes" },
  { name: "Newton", slug: "newton", county: "Middlesex", region: "Greater Boston", zipCodes: ["02458", "02459", "02460", "02461", "02462", "02464", "02465", "02466", "02467", "02468"], population: 88923, isCity: "yes" },
  { name: "Somerville", slug: "somerville", county: "Middlesex", region: "Greater Boston", zipCodes: ["02143", "02144", "02145"], population: 81045, isCity: "yes" },
  { name: "Framingham", slug: "framingham", county: "Middlesex", region: "MetroWest", zipCodes: ["01701", "01702", "01703", "01704", "01705"], population: 72362, isCity: "yes" },
  { name: "Waltham", slug: "waltham", county: "Middlesex", region: "Greater Boston", zipCodes: ["02451", "02452", "02453", "02454"], population: 64015, isCity: "yes" },
  { name: "Malden", slug: "malden", county: "Middlesex", region: "Greater Boston", zipCodes: ["02148"], population: 66263, isCity: "yes" },
  { name: "Medford", slug: "medford", county: "Middlesex", region: "Greater Boston", zipCodes: ["02153", "02155", "02156"], population: 59450, isCity: "yes" },
  { name: "Arlington", slug: "arlington", county: "Middlesex", region: "Greater Boston", zipCodes: ["02474", "02476"], population: 46308, isCity: "no" },
  { name: "Woburn", slug: "woburn", county: "Middlesex", region: "Greater Boston", zipCodes: ["01801", "01888"], population: 40512, isCity: "yes" },
  { name: "Billerica", slug: "billerica", county: "Middlesex", region: "Greater Boston", zipCodes: ["01821", "01862"], population: 43920, isCity: "no" },
  { name: "Chelmsford", slug: "chelmsford", county: "Middlesex", region: "Merrimack Valley", zipCodes: ["01824", "01863"], population: 35541, isCity: "no" },
  { name: "Lexington", slug: "lexington", county: "Middlesex", region: "Greater Boston", zipCodes: ["02420", "02421"], population: 34454, isCity: "no" },
  { name: "Burlington", slug: "burlington", county: "Middlesex", region: "Greater Boston", zipCodes: ["01803", "01805"], population: 28819, isCity: "no" },
  { name: "Watertown", slug: "watertown", county: "Middlesex", region: "Greater Boston", zipCodes: ["02471", "02472"], population: 35939, isCity: "no" },
  { name: "Natick", slug: "natick", county: "Middlesex", region: "MetroWest", zipCodes: ["01760", "01761"], population: 36608, isCity: "no" },
  { name: "Reading", slug: "reading", county: "Middlesex", region: "Greater Boston", zipCodes: ["01867"], population: 25500, isCity: "no" },
  { name: "Stoneham", slug: "stoneham", county: "Middlesex", region: "Greater Boston", zipCodes: ["02180"], population: 24126, isCity: "no" },
  { name: "Wakefield", slug: "wakefield", county: "Middlesex", region: "Greater Boston", zipCodes: ["01880"], population: 27045, isCity: "no" },
  { name: "Melrose", slug: "melrose", county: "Middlesex", region: "Greater Boston", zipCodes: ["02176"], population: 28016, isCity: "yes" },
  { name: "Everett", slug: "everett", county: "Middlesex", region: "Greater Boston", zipCodes: ["02149"], population: 49075, isCity: "yes" },
  { name: "Dracut", slug: "dracut", county: "Middlesex", region: "Merrimack Valley", zipCodes: ["01826"], population: 32017, isCity: "no" },
  { name: "Tewksbury", slug: "tewksbury", county: "Middlesex", region: "Merrimack Valley", zipCodes: ["01876"], population: 31702, isCity: "no" },
  { name: "Marlborough", slug: "marlborough", county: "Middlesex", region: "MetroWest", zipCodes: ["01752"], population: 41793, isCity: "yes" },
  { name: "Concord", slug: "concord", county: "Middlesex", region: "MetroWest", zipCodes: ["01742"], population: 19979, isCity: "no" },
  { name: "Bedford", slug: "bedford", county: "Middlesex", region: "Greater Boston", zipCodes: ["01730", "01731"], population: 14961, isCity: "no" },
  { name: "Winchester", slug: "winchester", county: "Middlesex", region: "Greater Boston", zipCodes: ["01890"], population: 22970, isCity: "no" },
  { name: "Belmont", slug: "belmont", county: "Middlesex", region: "Greater Boston", zipCodes: ["02478", "02479"], population: 26330, isCity: "no" },
  { name: "Wilmington", slug: "wilmington", county: "Middlesex", region: "Greater Boston", zipCodes: ["01887"], population: 23390, isCity: "no" },
  { name: "Hudson", slug: "hudson", county: "Middlesex", region: "MetroWest", zipCodes: ["01749"], population: 20390, isCity: "no" },
  { name: "Acton", slug: "acton", county: "Middlesex", region: "MetroWest", zipCodes: ["01720"], population: 24473, isCity: "no" },
  { name: "Holliston", slug: "holliston", county: "Middlesex", region: "MetroWest", zipCodes: ["01746"], population: 15060, isCity: "no" },
  { name: "Hopkinton", slug: "hopkinton", county: "Middlesex", region: "MetroWest", zipCodes: ["01748"], population: 18758, isCity: "no" },
  { name: "Ashland", slug: "ashland", county: "Middlesex", region: "MetroWest", zipCodes: ["01721"], population: 18250, isCity: "no" },
  { name: "Sudbury", slug: "sudbury", county: "Middlesex", region: "MetroWest", zipCodes: ["01776"], population: 19655, isCity: "no" },
  { name: "Westford", slug: "westford", county: "Middlesex", region: "Merrimack Valley", zipCodes: ["01886"], population: 25209, isCity: "no" },
  { name: "Littleton", slug: "littleton", county: "Middlesex", region: "MetroWest", zipCodes: ["01460", "01461"], population: 10339, isCity: "no" },
  { name: "Maynard", slug: "maynard", county: "Middlesex", region: "MetroWest", zipCodes: ["01754"], population: 10915, isCity: "no" },
  { name: "Stow", slug: "stow", county: "Middlesex", region: "MetroWest", zipCodes: ["01775"], population: 7212, isCity: "no" },

  // Essex County
  { name: "Lynn", slug: "lynn", county: "Essex", region: "North Shore", zipCodes: ["01901", "01902", "01903", "01904", "01905"], population: 101253, isCity: "yes" },
  { name: "Lawrence", slug: "lawrence", county: "Essex", region: "Merrimack Valley", zipCodes: ["01840", "01841", "01842", "01843"], population: 89143, isCity: "yes" },
  { name: "Haverhill", slug: "haverhill", county: "Essex", region: "Merrimack Valley", zipCodes: ["01830", "01831", "01832", "01835"], population: 67706, isCity: "yes" },
  { name: "Peabody", slug: "peabody", county: "Essex", region: "North Shore", zipCodes: ["01960"], population: 54481, isCity: "yes" },
  { name: "Salem", slug: "salem", county: "Essex", region: "North Shore", zipCodes: ["01970"], population: 44480, isCity: "yes" },
  { name: "Methuen", slug: "methuen", county: "Essex", region: "Merrimack Valley", zipCodes: ["01844"], population: 50706, isCity: "yes" },
  { name: "Beverly", slug: "beverly", county: "Essex", region: "North Shore", zipCodes: ["01915"], population: 42670, isCity: "yes" },
  { name: "Gloucester", slug: "gloucester", county: "Essex", region: "Cape Ann", zipCodes: ["01930", "01931"], population: 30273, isCity: "yes" },
  { name: "Andover", slug: "andover", county: "Essex", region: "Merrimack Valley", zipCodes: ["01810", "01812"], population: 36479, isCity: "no" },
  { name: "North Andover", slug: "north-andover", county: "Essex", region: "Merrimack Valley", zipCodes: ["01845"], population: 31188, isCity: "no" },
  { name: "Danvers", slug: "danvers", county: "Essex", region: "North Shore", zipCodes: ["01923"], population: 27549, isCity: "no" },
  { name: "Saugus", slug: "saugus", county: "Essex", region: "North Shore", zipCodes: ["01906"], population: 28215, isCity: "no" },
  { name: "Marblehead", slug: "marblehead", county: "Essex", region: "North Shore", zipCodes: ["01945"], population: 20509, isCity: "no" },
  { name: "Swampscott", slug: "swampscott", county: "Essex", region: "North Shore", zipCodes: ["01907"], population: 15298, isCity: "no" },
  { name: "Amesbury", slug: "amesbury", county: "Essex", region: "Merrimack Valley", zipCodes: ["01913"], population: 17474, isCity: "yes" },
  { name: "Newburyport", slug: "newburyport", county: "Essex", region: "North Shore", zipCodes: ["01950"], population: 18289, isCity: "yes" },
  { name: "Ipswich", slug: "ipswich", county: "Essex", region: "North Shore", zipCodes: ["01938"], population: 14094, isCity: "no" },
  { name: "Lynnfield", slug: "lynnfield", county: "Essex", region: "North Shore", zipCodes: ["01940"], population: 13238, isCity: "no" },
  { name: "Middleton", slug: "middleton", county: "Essex", region: "North Shore", zipCodes: ["01949"], population: 10166, isCity: "no" },
  { name: "Rockport", slug: "rockport", county: "Essex", region: "Cape Ann", zipCodes: ["01966"], population: 7413, isCity: "no" },
  { name: "Manchester-by-the-Sea", slug: "manchester-by-the-sea", county: "Essex", region: "Cape Ann", zipCodes: ["01944"], population: 5556, isCity: "no" },
  { name: "Essex", slug: "essex-town", county: "Essex", region: "Cape Ann", zipCodes: ["01929"], population: 3675, isCity: "no" },
  { name: "Georgetown", slug: "georgetown", county: "Essex", region: "Merrimack Valley", zipCodes: ["01833"], population: 8734, isCity: "no" },
  { name: "Groveland", slug: "groveland", county: "Essex", region: "Merrimack Valley", zipCodes: ["01834"], population: 6861, isCity: "no" },
  { name: "Merrimac", slug: "merrimac", county: "Essex", region: "Merrimack Valley", zipCodes: ["01860"], population: 6893, isCity: "no" },
  { name: "Newbury", slug: "newbury", county: "Essex", region: "North Shore", zipCodes: ["01951"], population: 7098, isCity: "no" },
  { name: "Rowley", slug: "rowley", county: "Essex", region: "North Shore", zipCodes: ["01969"], population: 6420, isCity: "no" },
  { name: "Salisbury", slug: "salisbury", county: "Essex", region: "Merrimack Valley", zipCodes: ["01952"], population: 9616, isCity: "no" },
  { name: "Topsfield", slug: "topsfield", county: "Essex", region: "North Shore", zipCodes: ["01983"], population: 6571, isCity: "no" },
  { name: "Wenham", slug: "wenham", county: "Essex", region: "North Shore", zipCodes: ["01984"], population: 5136, isCity: "no" },
  { name: "West Newbury", slug: "west-newbury", county: "Essex", region: "Merrimack Valley", zipCodes: ["01985"], population: 4674, isCity: "no" },
  { name: "Boxford", slug: "boxford", county: "Essex", region: "Merrimack Valley", zipCodes: ["01921"], population: 8693, isCity: "no" },
  { name: "Hamilton", slug: "hamilton", county: "Essex", region: "North Shore", zipCodes: ["01936"], population: 8050, isCity: "no" },
  { name: "Nahant", slug: "nahant", county: "Essex", region: "North Shore", zipCodes: ["01908"], population: 3512, isCity: "no" },

  // Norfolk County
  { name: "Quincy", slug: "quincy", county: "Norfolk", region: "South Shore", zipCodes: ["02169", "02170", "02171"], population: 101636, isCity: "yes" },
  { name: "Brookline", slug: "brookline", county: "Norfolk", region: "Greater Boston", zipCodes: ["02445", "02446", "02447"], population: 63191, isCity: "no" },
  { name: "Weymouth", slug: "weymouth", county: "Norfolk", region: "South Shore", zipCodes: ["02188", "02189", "02190", "02191"], population: 57746, isCity: "no" },
  { name: "Braintree", slug: "braintree", county: "Norfolk", region: "South Shore", zipCodes: ["02184", "02185"], population: 39207, isCity: "no" },
  { name: "Milton", slug: "milton", county: "Norfolk", region: "South Shore", zipCodes: ["02186", "02187"], population: 28600, isCity: "no" },
  { name: "Randolph", slug: "randolph", county: "Norfolk", region: "South Shore", zipCodes: ["02368"], population: 34984, isCity: "no" },
  { name: "Needham", slug: "needham", county: "Norfolk", region: "Greater Boston", zipCodes: ["02492", "02494"], population: 31388, isCity: "no" },
  { name: "Wellesley", slug: "wellesley", county: "Norfolk", region: "Greater Boston", zipCodes: ["02481", "02482"], population: 28747, isCity: "no" },
  { name: "Dedham", slug: "dedham", county: "Norfolk", region: "Greater Boston", zipCodes: ["02026", "02027"], population: 25330, isCity: "no" },
  { name: "Canton", slug: "canton", county: "Norfolk", region: "South Shore", zipCodes: ["02021"], population: 24370, isCity: "no" },
  { name: "Norwood", slug: "norwood", county: "Norfolk", region: "Greater Boston", zipCodes: ["02062"], population: 30451, isCity: "no" },
  { name: "Stoughton", slug: "stoughton", county: "Norfolk", region: "South Shore", zipCodes: ["02072"], population: 29215, isCity: "no" },
  { name: "Franklin", slug: "franklin", county: "Norfolk", region: "MetroWest", zipCodes: ["02038"], population: 34087, isCity: "no" },
  { name: "Walpole", slug: "walpole", county: "Norfolk", region: "South Shore", zipCodes: ["02071", "02081"], population: 25806, isCity: "no" },
  { name: "Sharon", slug: "sharon", county: "Norfolk", region: "South Shore", zipCodes: ["02067"], population: 18613, isCity: "no" },
  { name: "Medfield", slug: "medfield", county: "Norfolk", region: "MetroWest", zipCodes: ["02052"], population: 12841, isCity: "no" },
  { name: "Westwood", slug: "westwood", county: "Norfolk", region: "Greater Boston", zipCodes: ["02090"], population: 16215, isCity: "no" },
  { name: "Foxborough", slug: "foxborough", county: "Norfolk", region: "South Shore", zipCodes: ["02035"], population: 18618, isCity: "no" },
  { name: "Holbrook", slug: "holbrook", county: "Norfolk", region: "South Shore", zipCodes: ["02343"], population: 11161, isCity: "no" },
  { name: "Avon", slug: "avon", county: "Norfolk", region: "South Shore", zipCodes: ["02322"], population: 4633, isCity: "no" },
  { name: "Cohasset", slug: "cohasset", county: "Norfolk", region: "South Shore", zipCodes: ["02025"], population: 8380, isCity: "no" },
  { name: "Dover", slug: "dover", county: "Norfolk", region: "Greater Boston", zipCodes: ["02030"], population: 6215, isCity: "no" },
  { name: "Medway", slug: "medway", county: "Norfolk", region: "MetroWest", zipCodes: ["02053"], population: 13346, isCity: "no" },
  { name: "Millis", slug: "millis", county: "Norfolk", region: "MetroWest", zipCodes: ["02054"], population: 8400, isCity: "no" },
  { name: "Norfolk", slug: "norfolk-town", county: "Norfolk", region: "MetroWest", zipCodes: ["02056"], population: 11786, isCity: "no" },
  { name: "Plainville", slug: "plainville", county: "Norfolk", region: "South Shore", zipCodes: ["02762"], population: 9502, isCity: "no" },
  { name: "Wrentham", slug: "wrentham", county: "Norfolk", region: "South Shore", zipCodes: ["02093"], population: 12328, isCity: "no" },

  // Plymouth County
  { name: "Brockton", slug: "brockton", county: "Plymouth", region: "South Shore", zipCodes: ["02301", "02302", "02303", "02304", "02305"], population: 105643, isCity: "yes" },
  { name: "Plymouth", slug: "plymouth", county: "Plymouth", region: "South Shore", zipCodes: ["02360", "02361", "02362"], population: 61217, isCity: "no" },
  { name: "Marshfield", slug: "marshfield", county: "Plymouth", region: "South Shore", zipCodes: ["02050", "02059"], population: 26126, isCity: "no" },
  { name: "Pembroke", slug: "pembroke", county: "Plymouth", region: "South Shore", zipCodes: ["02359"], population: 18373, isCity: "no" },
  { name: "Duxbury", slug: "duxbury", county: "Plymouth", region: "South Shore", zipCodes: ["02331", "02332"], population: 16090, isCity: "no" },
  { name: "Hanover", slug: "hanover", county: "Plymouth", region: "South Shore", zipCodes: ["02339"], population: 15011, isCity: "no" },
  { name: "Hingham", slug: "hingham", county: "Plymouth", region: "South Shore", zipCodes: ["02043"], population: 24061, isCity: "no" },
  { name: "Scituate", slug: "scituate", county: "Plymouth", region: "South Shore", zipCodes: ["02066"], population: 18933, isCity: "no" },
  { name: "Norwell", slug: "norwell", county: "Plymouth", region: "South Shore", zipCodes: ["02061"], population: 11539, isCity: "no" },
  { name: "Rockland", slug: "rockland", county: "Plymouth", region: "South Shore", zipCodes: ["02370"], population: 18230, isCity: "no" },
  { name: "Abington", slug: "abington", county: "Plymouth", region: "South Shore", zipCodes: ["02351"], population: 16557, isCity: "no" },
  { name: "Whitman", slug: "whitman", county: "Plymouth", region: "South Shore", zipCodes: ["02382"], population: 15476, isCity: "no" },
  { name: "East Bridgewater", slug: "east-bridgewater", county: "Plymouth", region: "South Shore", zipCodes: ["02333"], population: 14798, isCity: "no" },
  { name: "West Bridgewater", slug: "west-bridgewater", county: "Plymouth", region: "South Shore", zipCodes: ["02379"], population: 7379, isCity: "no" },
  { name: "Bridgewater", slug: "bridgewater", county: "Plymouth", region: "South Shore", zipCodes: ["02324"], population: 28486, isCity: "no" },
  { name: "Middleborough", slug: "middleborough", county: "Plymouth", region: "South Shore", zipCodes: ["02346", "02349"], population: 25621, isCity: "no" },
  { name: "Wareham", slug: "wareham", county: "Plymouth", region: "South Coast", zipCodes: ["02571", "02538"], population: 23363, isCity: "no" },
  { name: "Carver", slug: "carver", county: "Plymouth", region: "South Shore", zipCodes: ["02330"], population: 11856, isCity: "no" },
  { name: "Halifax", slug: "halifax", county: "Plymouth", region: "South Shore", zipCodes: ["02338"], population: 8149, isCity: "no" },
  { name: "Hanson", slug: "hanson", county: "Plymouth", region: "South Shore", zipCodes: ["02341"], population: 11141, isCity: "no" },
  { name: "Hull", slug: "hull", county: "Plymouth", region: "South Shore", zipCodes: ["02045"], population: 10293, isCity: "no" },
  { name: "Kingston", slug: "kingston", county: "Plymouth", region: "South Shore", zipCodes: ["02364"], population: 14142, isCity: "no" },
  { name: "Lakeville", slug: "lakeville", county: "Plymouth", region: "South Shore", zipCodes: ["02347"], population: 12035, isCity: "no" },
  { name: "Marion", slug: "marion", county: "Plymouth", region: "South Coast", zipCodes: ["02738"], population: 5123, isCity: "no" },
  { name: "Mattapoisett", slug: "mattapoisett", county: "Plymouth", region: "South Coast", zipCodes: ["02739"], population: 6432, isCity: "no" },
  { name: "Plympton", slug: "plympton", county: "Plymouth", region: "South Shore", zipCodes: ["02367"], population: 3041, isCity: "no" },
  { name: "Rochester", slug: "rochester", county: "Plymouth", region: "South Coast", zipCodes: ["02770"], population: 5800, isCity: "no" },

  // Worcester County
  { name: "Worcester", slug: "worcester", county: "Worcester", region: "Central Massachusetts", zipCodes: ["01601", "01602", "01603", "01604", "01605", "01606", "01607", "01608", "01609", "01610", "01613", "01614", "01615", "01653", "01654", "01655"], population: 206518, isCity: "yes" },
  { name: "Springfield", slug: "springfield", county: "Hampden", region: "Pioneer Valley", zipCodes: ["01101", "01102", "01103", "01104", "01105", "01107", "01108", "01109", "01111", "01114", "01115", "01116", "01118", "01119", "01128", "01129", "01138", "01139", "01144", "01151", "01152"], population: 155929, isCity: "yes" },
  { name: "Fitchburg", slug: "fitchburg", county: "Worcester", region: "North Central", zipCodes: ["01420"], population: 40659, isCity: "yes" },
  { name: "Leominster", slug: "leominster", county: "Worcester", region: "North Central", zipCodes: ["01453"], population: 43782, isCity: "yes" },
  { name: "Shrewsbury", slug: "shrewsbury", county: "Worcester", region: "Central Massachusetts", zipCodes: ["01545"], population: 38526, isCity: "no" },
  { name: "Milford", slug: "milford", county: "Worcester", region: "Blackstone Valley", zipCodes: ["01757"], population: 30996, isCity: "no" },
  { name: "Westborough", slug: "westborough", county: "Worcester", region: "Central Massachusetts", zipCodes: ["01581"], population: 19117, isCity: "no" },
  { name: "Grafton", slug: "grafton", county: "Worcester", region: "Blackstone Valley", zipCodes: ["01519"], population: 19503, isCity: "no" },
  { name: "Northborough", slug: "northborough", county: "Worcester", region: "Central Massachusetts", zipCodes: ["01532"], population: 15264, isCity: "no" },
  { name: "Southborough", slug: "southborough", county: "Worcester", region: "MetroWest", zipCodes: ["01772"], population: 10450, isCity: "no" },
  { name: "Auburn", slug: "auburn", county: "Worcester", region: "Central Massachusetts", zipCodes: ["01501"], population: 16851, isCity: "no" },
  { name: "Webster", slug: "webster", county: "Worcester", region: "Blackstone Valley", zipCodes: ["01570"], population: 17224, isCity: "no" },
  { name: "Dudley", slug: "dudley", county: "Worcester", region: "Blackstone Valley", zipCodes: ["01571"], population: 12196, isCity: "no" },
  { name: "Oxford", slug: "oxford", county: "Worcester", region: "Blackstone Valley", zipCodes: ["01540"], population: 14044, isCity: "no" },
  { name: "Charlton", slug: "charlton", county: "Worcester", region: "Central Massachusetts", zipCodes: ["01507"], population: 14210, isCity: "no" },
  { name: "Sturbridge", slug: "sturbridge", county: "Worcester", region: "Central Massachusetts", zipCodes: ["01566"], population: 10010, isCity: "no" },
  { name: "Southbridge", slug: "southbridge", county: "Worcester", region: "Blackstone Valley", zipCodes: ["01550"], population: 17769, isCity: "no" },
  { name: "Spencer", slug: "spencer", county: "Worcester", region: "Central Massachusetts", zipCodes: ["01562"], population: 12196, isCity: "no" },
  { name: "Leicester", slug: "leicester", county: "Worcester", region: "Central Massachusetts", zipCodes: ["01524"], population: 11528, isCity: "no" },
  { name: "Holden", slug: "holden", county: "Worcester", region: "Central Massachusetts", zipCodes: ["01520", "01522"], population: 19596, isCity: "no" },
  { name: "Rutland", slug: "rutland", county: "Worcester", region: "Central Massachusetts", zipCodes: ["01543"], population: 9347, isCity: "no" },
  { name: "Paxton", slug: "paxton", county: "Worcester", region: "Central Massachusetts", zipCodes: ["01612"], population: 4973, isCity: "no" },
  { name: "Clinton", slug: "clinton", county: "Worcester", region: "Central Massachusetts", zipCodes: ["01510"], population: 14005, isCity: "no" },
  { name: "Berlin", slug: "berlin", county: "Worcester", region: "Central Massachusetts", zipCodes: ["01503"], population: 3131, isCity: "no" },
  { name: "Bolton", slug: "bolton", county: "Worcester", region: "Central Massachusetts", zipCodes: ["01740"], population: 5665, isCity: "no" },
  { name: "Boylston", slug: "boylston", county: "Worcester", region: "Central Massachusetts", zipCodes: ["01505"], population: 4683, isCity: "no" },
  { name: "Sterling", slug: "sterling", county: "Worcester", region: "Central Massachusetts", zipCodes: ["01564"], population: 8156, isCity: "no" },
  { name: "West Boylston", slug: "west-boylston", county: "Worcester", region: "Central Massachusetts", zipCodes: ["01583"], population: 8080, isCity: "no" },
  { name: "Lancaster", slug: "lancaster", county: "Worcester", region: "Central Massachusetts", zipCodes: ["01523"], population: 8055, isCity: "no" },
  { name: "Harvard", slug: "harvard", county: "Worcester", region: "Central Massachusetts", zipCodes: ["01451"], population: 6708, isCity: "no" },
  { name: "Lunenburg", slug: "lunenburg", county: "Worcester", region: "North Central", zipCodes: ["01462"], population: 11911, isCity: "no" },
  { name: "Ashburnham", slug: "ashburnham", county: "Worcester", region: "North Central", zipCodes: ["01430"], population: 6474, isCity: "no" },
  { name: "Gardner", slug: "gardner", county: "Worcester", region: "North Central", zipCodes: ["01440"], population: 21679, isCity: "yes" },
  { name: "Templeton", slug: "templeton", county: "Worcester", region: "North Central", zipCodes: ["01436", "01468"], population: 8155, isCity: "no" },
  { name: "Winchendon", slug: "winchendon", county: "Worcester", region: "North Central", zipCodes: ["01475"], population: 10924, isCity: "no" },
  { name: "Athol", slug: "athol", county: "Worcester", region: "North Central", zipCodes: ["01331"], population: 12059, isCity: "no" },
  { name: "Uxbridge", slug: "uxbridge", county: "Worcester", region: "Blackstone Valley", zipCodes: ["01569"], population: 14357, isCity: "no" },
  { name: "Douglas", slug: "douglas", county: "Worcester", region: "Blackstone Valley", zipCodes: ["01516"], population: 9094, isCity: "no" },
  { name: "Sutton", slug: "sutton", county: "Worcester", region: "Blackstone Valley", zipCodes: ["01590"], population: 9581, isCity: "no" },
  { name: "Northbridge", slug: "northbridge", county: "Worcester", region: "Blackstone Valley", zipCodes: ["01534", "01588"], population: 17058, isCity: "no" },
  { name: "Upton", slug: "upton", county: "Worcester", region: "Blackstone Valley", zipCodes: ["01568"], population: 8192, isCity: "no" },
  { name: "Mendon", slug: "mendon", county: "Worcester", region: "Blackstone Valley", zipCodes: ["01756"], population: 6378, isCity: "no" },
  { name: "Hopedale", slug: "hopedale", county: "Worcester", region: "Blackstone Valley", zipCodes: ["01747"], population: 6020, isCity: "no" },
  { name: "Blackstone", slug: "blackstone", county: "Worcester", region: "Blackstone Valley", zipCodes: ["01504"], population: 9313, isCity: "no" },
  { name: "Millville", slug: "millville", county: "Worcester", region: "Blackstone Valley", zipCodes: ["01529"], population: 3317, isCity: "no" },
  { name: "Millbury", slug: "millbury", county: "Worcester", region: "Blackstone Valley", zipCodes: ["01527"], population: 14281, isCity: "no" },

  // Hampden County
  { name: "Chicopee", slug: "chicopee", county: "Hampden", region: "Pioneer Valley", zipCodes: ["01013", "01014", "01020", "01021", "01022"], population: 55560, isCity: "yes" },
  { name: "Holyoke", slug: "holyoke", county: "Hampden", region: "Pioneer Valley", zipCodes: ["01040", "01041"], population: 38280, isCity: "yes" },
  { name: "Westfield", slug: "westfield", county: "Hampden", region: "Pioneer Valley", zipCodes: ["01085", "01086"], population: 41652, isCity: "yes" },
  { name: "Agawam", slug: "agawam", county: "Hampden", region: "Pioneer Valley", zipCodes: ["01001", "01030"], population: 28846, isCity: "no" },
  { name: "West Springfield", slug: "west-springfield", county: "Hampden", region: "Pioneer Valley", zipCodes: ["01089", "01090"], population: 28551, isCity: "no" },
  { name: "Ludlow", slug: "ludlow", county: "Hampden", region: "Pioneer Valley", zipCodes: ["01056"], population: 21604, isCity: "no" },
  { name: "East Longmeadow", slug: "east-longmeadow", county: "Hampden", region: "Pioneer Valley", zipCodes: ["01028"], population: 16512, isCity: "no" },
  { name: "Longmeadow", slug: "longmeadow", county: "Hampden", region: "Pioneer Valley", zipCodes: ["01106"], population: 15827, isCity: "no" },
  { name: "Wilbraham", slug: "wilbraham", county: "Hampden", region: "Pioneer Valley", zipCodes: ["01095"], population: 14868, isCity: "no" },
  { name: "Palmer", slug: "palmer", county: "Hampden", region: "Pioneer Valley", zipCodes: ["01069"], population: 12448, isCity: "no" },
  { name: "Monson", slug: "monson", county: "Hampden", region: "Pioneer Valley", zipCodes: ["01057"], population: 8785, isCity: "no" },
  { name: "Hampden", slug: "hampden-town", county: "Hampden", region: "Pioneer Valley", zipCodes: ["01036"], population: 5284, isCity: "no" },
  { name: "Brimfield", slug: "brimfield", county: "Hampden", region: "Pioneer Valley", zipCodes: ["01010"], population: 3779, isCity: "no" },
  { name: "Holland", slug: "holland", county: "Hampden", region: "Pioneer Valley", zipCodes: ["01521"], population: 2617, isCity: "no" },
  { name: "Wales", slug: "wales", county: "Hampden", region: "Pioneer Valley", zipCodes: ["01081"], population: 1922, isCity: "no" },
  { name: "Southwick", slug: "southwick", county: "Hampden", region: "Pioneer Valley", zipCodes: ["01077"], population: 9895, isCity: "no" },
  { name: "Granville", slug: "granville", county: "Hampden", region: "Pioneer Valley", zipCodes: ["01034"], population: 1679, isCity: "no" },
  { name: "Tolland", slug: "tolland", county: "Hampden", region: "Pioneer Valley", zipCodes: ["01034"], population: 527, isCity: "no" },
  { name: "Russell", slug: "russell", county: "Hampden", region: "Pioneer Valley", zipCodes: ["01071"], population: 1761, isCity: "no" },
  { name: "Montgomery", slug: "montgomery", county: "Hampden", region: "Pioneer Valley", zipCodes: ["01085"], population: 922, isCity: "no" },
  { name: "Chester", slug: "chester", county: "Hampden", region: "Pioneer Valley", zipCodes: ["01011"], population: 1498, isCity: "no" },
  { name: "Blandford", slug: "blandford", county: "Hampden", region: "Pioneer Valley", zipCodes: ["01008"], population: 1264, isCity: "no" },

  // Hampshire County
  { name: "Northampton", slug: "northampton", county: "Hampshire", region: "Pioneer Valley", zipCodes: ["01060", "01061", "01062", "01063"], population: 29571, isCity: "yes" },
  { name: "Amherst", slug: "amherst", county: "Hampshire", region: "Pioneer Valley", zipCodes: ["01002", "01003", "01004"], population: 39263, isCity: "no" },
  { name: "South Hadley", slug: "south-hadley", county: "Hampshire", region: "Pioneer Valley", zipCodes: ["01075"], population: 17514, isCity: "no" },
  { name: "Easthampton", slug: "easthampton", county: "Hampshire", region: "Pioneer Valley", zipCodes: ["01027"], population: 16053, isCity: "yes" },
  { name: "Hadley", slug: "hadley", county: "Hampshire", region: "Pioneer Valley", zipCodes: ["01035"], population: 5250, isCity: "no" },
  { name: "Granby", slug: "granby", county: "Hampshire", region: "Pioneer Valley", zipCodes: ["01033"], population: 6429, isCity: "no" },
  { name: "Belchertown", slug: "belchertown", county: "Hampshire", region: "Pioneer Valley", zipCodes: ["01007"], population: 15087, isCity: "no" },
  { name: "Ware", slug: "ware", county: "Hampshire", region: "Pioneer Valley", zipCodes: ["01082"], population: 9872, isCity: "no" },
  { name: "Williamsburg", slug: "williamsburg", county: "Hampshire", region: "Pioneer Valley", zipCodes: ["01096"], population: 2506, isCity: "no" },
  { name: "Hatfield", slug: "hatfield", county: "Hampshire", region: "Pioneer Valley", zipCodes: ["01038"], population: 3341, isCity: "no" },
  { name: "Pelham", slug: "pelham", county: "Hampshire", region: "Pioneer Valley", zipCodes: ["01002"], population: 1382, isCity: "no" },
  { name: "Southampton", slug: "southampton", county: "Hampshire", region: "Pioneer Valley", zipCodes: ["01073"], population: 6196, isCity: "no" },
  { name: "Huntington", slug: "huntington", county: "Hampshire", region: "Pioneer Valley", zipCodes: ["01050"], population: 2180, isCity: "no" },
  { name: "Chesterfield", slug: "chesterfield", county: "Hampshire", region: "Pioneer Valley", zipCodes: ["01012"], population: 1326, isCity: "no" },
  { name: "Cummington", slug: "cummington", county: "Hampshire", region: "Pioneer Valley", zipCodes: ["01026"], population: 872, isCity: "no" },
  { name: "Goshen", slug: "goshen", county: "Hampshire", region: "Pioneer Valley", zipCodes: ["01032"], population: 1085, isCity: "no" },
  { name: "Middlefield", slug: "middlefield", county: "Hampshire", region: "Pioneer Valley", zipCodes: ["01243"], population: 521, isCity: "no" },
  { name: "Plainfield", slug: "plainfield", county: "Hampshire", region: "Pioneer Valley", zipCodes: ["01070"], population: 701, isCity: "no" },
  { name: "Westhampton", slug: "westhampton", county: "Hampshire", region: "Pioneer Valley", zipCodes: ["01027"], population: 1723, isCity: "no" },
  { name: "Worthington", slug: "worthington", county: "Hampshire", region: "Pioneer Valley", zipCodes: ["01098"], population: 1216, isCity: "no" },

  // Bristol County
  { name: "New Bedford", slug: "new-bedford", county: "Bristol", region: "South Coast", zipCodes: ["02740", "02741", "02742", "02744", "02745", "02746"], population: 101079, isCity: "yes" },
  { name: "Fall River", slug: "fall-river", county: "Bristol", region: "South Coast", zipCodes: ["02720", "02721", "02722", "02723", "02724", "02725"], population: 93885, isCity: "yes" },
  { name: "Taunton", slug: "taunton", county: "Bristol", region: "South Coast", zipCodes: ["02780", "02783"], population: 59498, isCity: "yes" },
  { name: "Attleboro", slug: "attleboro", county: "Bristol", region: "South Coast", zipCodes: ["02703"], population: 46699, isCity: "yes" },
  { name: "Dartmouth", slug: "dartmouth", county: "Bristol", region: "South Coast", zipCodes: ["02714", "02747", "02748"], population: 34798, isCity: "no" },
  { name: "Fairhaven", slug: "fairhaven", county: "Bristol", region: "South Coast", zipCodes: ["02719"], population: 16441, isCity: "no" },
  { name: "Acushnet", slug: "acushnet", county: "Bristol", region: "South Coast", zipCodes: ["02743"], population: 10526, isCity: "no" },
  { name: "Westport", slug: "westport", county: "Bristol", region: "South Coast", zipCodes: ["02790", "02791"], population: 16051, isCity: "no" },
  { name: "Somerset", slug: "somerset", county: "Bristol", region: "South Coast", zipCodes: ["02725", "02726"], population: 18643, isCity: "no" },
  { name: "Swansea", slug: "swansea", county: "Bristol", region: "South Coast", zipCodes: ["02777"], population: 17019, isCity: "no" },
  { name: "Seekonk", slug: "seekonk", county: "Bristol", region: "South Coast", zipCodes: ["02771"], population: 16393, isCity: "no" },
  { name: "Rehoboth", slug: "rehoboth", county: "Bristol", region: "South Coast", zipCodes: ["02769"], population: 12884, isCity: "no" },
  { name: "Dighton", slug: "dighton", county: "Bristol", region: "South Coast", zipCodes: ["02715", "02764"], population: 8184, isCity: "no" },
  { name: "Berkley", slug: "berkley", county: "Bristol", region: "South Coast", zipCodes: ["02779"], population: 6729, isCity: "no" },
  { name: "Freetown", slug: "freetown", county: "Bristol", region: "South Coast", zipCodes: ["02702", "02717"], population: 9514, isCity: "no" },
  { name: "Mansfield", slug: "mansfield", county: "Bristol", region: "South Coast", zipCodes: ["02048"], population: 24380, isCity: "no" },
  { name: "North Attleborough", slug: "north-attleborough", county: "Bristol", region: "South Coast", zipCodes: ["02760", "02761"], population: 29281, isCity: "no" },
  { name: "Norton", slug: "norton", county: "Bristol", region: "South Coast", zipCodes: ["02766"], population: 19808, isCity: "no" },
  { name: "Easton", slug: "easton", county: "Bristol", region: "South Coast", zipCodes: ["02334", "02356", "02357"], population: 25095, isCity: "no" },
  { name: "Raynham", slug: "raynham", county: "Bristol", region: "South Coast", zipCodes: ["02767", "02768"], population: 15013, isCity: "no" },

  // Barnstable County (Cape Cod)
  { name: "Barnstable", slug: "barnstable", county: "Barnstable", region: "Cape Cod", zipCodes: ["02601", "02630", "02631", "02632", "02635", "02637", "02647", "02648", "02668"], population: 47821, isCity: "yes" },
  { name: "Falmouth", slug: "falmouth", county: "Barnstable", region: "Cape Cod", zipCodes: ["02536", "02540", "02541", "02543", "02574"], population: 31531, isCity: "no" },
  { name: "Yarmouth", slug: "yarmouth", county: "Barnstable", region: "Cape Cod", zipCodes: ["02664", "02673", "02675"], population: 23696, isCity: "no" },
  { name: "Sandwich", slug: "sandwich", county: "Barnstable", region: "Cape Cod", zipCodes: ["02537", "02563"], population: 20136, isCity: "no" },
  { name: "Mashpee", slug: "mashpee", county: "Barnstable", region: "Cape Cod", zipCodes: ["02649"], population: 14681, isCity: "no" },
  { name: "Dennis", slug: "dennis", county: "Barnstable", region: "Cape Cod", zipCodes: ["02638", "02639", "02641", "02660", "02670"], population: 13864, isCity: "no" },
  { name: "Bourne", slug: "bourne", county: "Barnstable", region: "Cape Cod", zipCodes: ["02532", "02534", "02542", "02553", "02556", "02559", "02562"], population: 19819, isCity: "no" },
  { name: "Brewster", slug: "brewster", county: "Barnstable", region: "Cape Cod", zipCodes: ["02631"], population: 9711, isCity: "no" },
  { name: "Chatham", slug: "chatham", county: "Barnstable", region: "Cape Cod", zipCodes: ["02633", "02650", "02659"], population: 6022, isCity: "no" },
  { name: "Eastham", slug: "eastham", county: "Barnstable", region: "Cape Cod", zipCodes: ["02642", "02651"], population: 4932, isCity: "no" },
  { name: "Harwich", slug: "harwich", county: "Barnstable", region: "Cape Cod", zipCodes: ["02645", "02646", "02661", "02671"], population: 12237, isCity: "no" },
  { name: "Orleans", slug: "orleans", county: "Barnstable", region: "Cape Cod", zipCodes: ["02653"], population: 5726, isCity: "no" },
  { name: "Provincetown", slug: "provincetown", county: "Barnstable", region: "Cape Cod", zipCodes: ["02657"], population: 2941, isCity: "no" },
  { name: "Truro", slug: "truro", county: "Barnstable", region: "Cape Cod", zipCodes: ["02666", "02652"], population: 2005, isCity: "no" },
  { name: "Wellfleet", slug: "wellfleet", county: "Barnstable", region: "Cape Cod", zipCodes: ["02663", "02667"], population: 2749, isCity: "no" },

  // Berkshire County
  { name: "Pittsfield", slug: "pittsfield", county: "Berkshire", region: "Berkshires", zipCodes: ["01201", "01202", "01203"], population: 42514, isCity: "yes" },
  { name: "North Adams", slug: "north-adams", county: "Berkshire", region: "Berkshires", zipCodes: ["01247"], population: 12961, isCity: "yes" },
  { name: "Adams", slug: "adams", county: "Berkshire", region: "Berkshires", zipCodes: ["01220"], population: 8069, isCity: "no" },
  { name: "Williamstown", slug: "williamstown", county: "Berkshire", region: "Berkshires", zipCodes: ["01267"], population: 7513, isCity: "no" },
  { name: "Great Barrington", slug: "great-barrington", county: "Berkshire", region: "Berkshires", zipCodes: ["01230"], population: 6940, isCity: "no" },
  { name: "Lee", slug: "lee", county: "Berkshire", region: "Berkshires", zipCodes: ["01238"], population: 5788, isCity: "no" },
  { name: "Lenox", slug: "lenox", county: "Berkshire", region: "Berkshires", zipCodes: ["01240"], population: 4964, isCity: "no" },
  { name: "Dalton", slug: "dalton", county: "Berkshire", region: "Berkshires", zipCodes: ["01226"], population: 6388, isCity: "no" },
  { name: "Stockbridge", slug: "stockbridge", county: "Berkshire", region: "Berkshires", zipCodes: ["01262"], population: 1947, isCity: "no" },
  { name: "Sheffield", slug: "sheffield", county: "Berkshire", region: "Berkshires", zipCodes: ["01257"], population: 3257, isCity: "no" },
  { name: "Lanesborough", slug: "lanesborough", county: "Berkshire", region: "Berkshires", zipCodes: ["01237"], population: 2918, isCity: "no" },
  { name: "Cheshire", slug: "cheshire", county: "Berkshire", region: "Berkshires", zipCodes: ["01225"], population: 3165, isCity: "no" },
  { name: "Becket", slug: "becket", county: "Berkshire", region: "Berkshires", zipCodes: ["01223"], population: 1962, isCity: "no" },
  { name: "Egremont", slug: "egremont", county: "Berkshire", region: "Berkshires", zipCodes: ["01230", "01258"], population: 1286, isCity: "no" },
  { name: "West Stockbridge", slug: "west-stockbridge", county: "Berkshire", region: "Berkshires", zipCodes: ["01266"], population: 1337, isCity: "no" },
  { name: "Clarksburg", slug: "clarksburg", county: "Berkshire", region: "Berkshires", zipCodes: ["01247"], population: 1702, isCity: "no" },
  { name: "Florida", slug: "florida-ma", county: "Berkshire", region: "Berkshires", zipCodes: ["01247"], population: 664, isCity: "no" },
  { name: "Hancock", slug: "hancock", county: "Berkshire", region: "Berkshires", zipCodes: ["01237"], population: 741, isCity: "no" },
  { name: "Hinsdale", slug: "hinsdale", county: "Berkshire", region: "Berkshires", zipCodes: ["01235"], population: 2066, isCity: "no" },
  { name: "Monterey", slug: "monterey", county: "Berkshire", region: "Berkshires", zipCodes: ["01245"], population: 934, isCity: "no" },
  { name: "Mount Washington", slug: "mount-washington", county: "Berkshire", region: "Berkshires", zipCodes: ["01258"], population: 167, isCity: "no" },
  { name: "New Ashford", slug: "new-ashford", county: "Berkshire", region: "Berkshires", zipCodes: ["01237"], population: 247, isCity: "no" },
  { name: "New Marlborough", slug: "new-marlborough", county: "Berkshire", region: "Berkshires", zipCodes: ["01230"], population: 1509, isCity: "no" },
  { name: "Otis", slug: "otis", county: "Berkshire", region: "Berkshires", zipCodes: ["01253"], population: 1612, isCity: "no" },
  { name: "Peru", slug: "peru", county: "Berkshire", region: "Berkshires", zipCodes: ["01235"], population: 865, isCity: "no" },
  { name: "Richmond", slug: "richmond", county: "Berkshire", region: "Berkshires", zipCodes: ["01254"], population: 1475, isCity: "no" },
  { name: "Sandisfield", slug: "sandisfield", county: "Berkshire", region: "Berkshires", zipCodes: ["01255"], population: 953, isCity: "no" },
  { name: "Savoy", slug: "savoy", county: "Berkshire", region: "Berkshires", zipCodes: ["01256"], population: 675, isCity: "no" },
  { name: "Tyringham", slug: "tyringham", county: "Berkshire", region: "Berkshires", zipCodes: ["01264"], population: 319, isCity: "no" },
  { name: "Washington", slug: "washington-ma", county: "Berkshire", region: "Berkshires", zipCodes: ["01223"], population: 538, isCity: "no" },
  { name: "Windsor", slug: "windsor", county: "Berkshire", region: "Berkshires", zipCodes: ["01270"], population: 879, isCity: "no" },

  // Franklin County
  { name: "Greenfield", slug: "greenfield", county: "Franklin", region: "Pioneer Valley", zipCodes: ["01301", "01302"], population: 17456, isCity: "yes" },
  { name: "Montague", slug: "montague", county: "Franklin", region: "Pioneer Valley", zipCodes: ["01349", "01351", "01376"], population: 8437, isCity: "no" },
  { name: "Orange", slug: "orange", county: "Franklin", region: "Pioneer Valley", zipCodes: ["01364"], population: 7839, isCity: "no" },
  { name: "Deerfield", slug: "deerfield", county: "Franklin", region: "Pioneer Valley", zipCodes: ["01342", "01373"], population: 5125, isCity: "no" },
  { name: "Shelburne", slug: "shelburne", county: "Franklin", region: "Pioneer Valley", zipCodes: ["01370"], population: 1893, isCity: "no" },
  { name: "Bernardston", slug: "bernardston", county: "Franklin", region: "Pioneer Valley", zipCodes: ["01337"], population: 2153, isCity: "no" },
  { name: "Buckland", slug: "buckland", county: "Franklin", region: "Pioneer Valley", zipCodes: ["01338"], population: 1902, isCity: "no" },
  { name: "Charlemont", slug: "charlemont", county: "Franklin", region: "Pioneer Valley", zipCodes: ["01339"], population: 1263, isCity: "no" },
  { name: "Colrain", slug: "colrain", county: "Franklin", region: "Pioneer Valley", zipCodes: ["01340"], population: 1671, isCity: "no" },
  { name: "Conway", slug: "conway", county: "Franklin", region: "Pioneer Valley", zipCodes: ["01341"], population: 1897, isCity: "no" },
  { name: "Erving", slug: "erving", county: "Franklin", region: "Pioneer Valley", zipCodes: ["01344"], population: 1800, isCity: "no" },
  { name: "Gill", slug: "gill", county: "Franklin", region: "Pioneer Valley", zipCodes: ["01354", "01376"], population: 1500, isCity: "no" },
  { name: "Hawley", slug: "hawley", county: "Franklin", region: "Pioneer Valley", zipCodes: ["01339"], population: 337, isCity: "no" },
  { name: "Heath", slug: "heath", county: "Franklin", region: "Pioneer Valley", zipCodes: ["01346"], population: 706, isCity: "no" },
  { name: "Leverett", slug: "leverett", county: "Franklin", region: "Pioneer Valley", zipCodes: ["01054"], population: 1871, isCity: "no" },
  { name: "Leyden", slug: "leyden", county: "Franklin", region: "Pioneer Valley", zipCodes: ["01337"], population: 711, isCity: "no" },
  { name: "Monroe", slug: "monroe", county: "Franklin", region: "Pioneer Valley", zipCodes: ["01350"], population: 93, isCity: "no" },
  { name: "New Salem", slug: "new-salem", county: "Franklin", region: "Pioneer Valley", zipCodes: ["01355"], population: 1034, isCity: "no" },
  { name: "Northfield", slug: "northfield", county: "Franklin", region: "Pioneer Valley", zipCodes: ["01360"], population: 2951, isCity: "no" },
  { name: "Rowe", slug: "rowe", county: "Franklin", region: "Pioneer Valley", zipCodes: ["01367"], population: 393, isCity: "no" },
  { name: "Shutesbury", slug: "shutesbury", county: "Franklin", region: "Pioneer Valley", zipCodes: ["01072"], population: 1717, isCity: "no" },
  { name: "Sunderland", slug: "sunderland", county: "Franklin", region: "Pioneer Valley", zipCodes: ["01375"], population: 3684, isCity: "no" },
  { name: "Warwick", slug: "warwick", county: "Franklin", region: "Pioneer Valley", zipCodes: ["01378"], population: 780, isCity: "no" },
  { name: "Wendell", slug: "wendell", county: "Franklin", region: "Pioneer Valley", zipCodes: ["01379", "01380"], population: 986, isCity: "no" },
  { name: "Whately", slug: "whately", county: "Franklin", region: "Pioneer Valley", zipCodes: ["01093"], population: 1573, isCity: "no" },

  // Dukes County (Martha's Vineyard)
  { name: "Edgartown", slug: "edgartown", county: "Dukes", region: "Martha's Vineyard", zipCodes: ["02539"], population: 4067, isCity: "no" },
  { name: "Oak Bluffs", slug: "oak-bluffs", county: "Dukes", region: "Martha's Vineyard", zipCodes: ["02557"], population: 5156, isCity: "no" },
  { name: "Tisbury", slug: "tisbury", county: "Dukes", region: "Martha's Vineyard", zipCodes: ["02568"], population: 4304, isCity: "no" },
  { name: "West Tisbury", slug: "west-tisbury", county: "Dukes", region: "Martha's Vineyard", zipCodes: ["02575"], population: 3295, isCity: "no" },
  { name: "Chilmark", slug: "chilmark", county: "Dukes", region: "Martha's Vineyard", zipCodes: ["02535"], population: 1020, isCity: "no" },
  { name: "Aquinnah", slug: "aquinnah", county: "Dukes", region: "Martha's Vineyard", zipCodes: ["02535"], population: 311, isCity: "no" },
  { name: "Gosnold", slug: "gosnold", county: "Dukes", region: "Elizabeth Islands", zipCodes: ["02713"], population: 75, isCity: "no" },

  // Nantucket County
  { name: "Nantucket", slug: "nantucket", county: "Nantucket", region: "Nantucket", zipCodes: ["02554", "02564", "02584"], population: 14255, isCity: "no" },
];

// Care types available
export const careTypes = [
  "personal_care",
  "companionship", 
  "homemaking",
  "dementia_care",
  "respite_care",
  "live_in_care"
] as const;

export type CareType = typeof careTypes[number];

// Care type display names and descriptions
export const careTypeInfo: Record<CareType, { name: string; description: string; slug: string }> = {
  personal_care: {
    name: "Personal Care",
    description: "Assistance with daily living activities including bathing, dressing, grooming, and mobility support.",
    slug: "personal-care"
  },
  companionship: {
    name: "Companionship Care",
    description: "Social interaction, conversation, accompaniment to appointments, and emotional support.",
    slug: "companionship"
  },
  homemaking: {
    name: "Homemaking Services",
    description: "Light housekeeping, meal preparation, laundry, and home organization.",
    slug: "homemaking"
  },
  dementia_care: {
    name: "Dementia & Alzheimer's Care",
    description: "Specialized care for individuals with memory conditions including supervision and cognitive engagement.",
    slug: "dementia-care"
  },
  respite_care: {
    name: "Respite Care",
    description: "Temporary relief for family caregivers, providing professional care during breaks.",
    slug: "respite-care"
  },
  live_in_care: {
    name: "Live-In Care",
    description: "24-hour care with a dedicated caregiver living in the home for continuous support.",
    slug: "live-in-care"
  }
};

// Service types for each care category
export const serviceTypes = [
  // Personal Care Services
  { name: "Bathing Assistance", slug: "bathing-assistance", category: "personal_care", sortOrder: 1 },
  { name: "Dressing Assistance", slug: "dressing-assistance", category: "personal_care", sortOrder: 2 },
  { name: "Grooming & Hygiene", slug: "grooming-hygiene", category: "personal_care", sortOrder: 3 },
  { name: "Mobility Support", slug: "mobility-support", category: "personal_care", sortOrder: 4 },
  { name: "Toileting Assistance", slug: "toileting-assistance", category: "personal_care", sortOrder: 5 },
  { name: "Transfer Assistance", slug: "transfer-assistance", category: "personal_care", sortOrder: 6 },
  { name: "Medication Reminders", slug: "medication-reminders", category: "personal_care", sortOrder: 7 },
  
  // Companionship Services
  { name: "Social Engagement", slug: "social-engagement", category: "companionship", sortOrder: 1 },
  { name: "Conversation & Company", slug: "conversation-company", category: "companionship", sortOrder: 2 },
  { name: "Accompaniment to Appointments", slug: "appointment-accompaniment", category: "companionship", sortOrder: 3 },
  { name: "Errands & Shopping", slug: "errands-shopping", category: "companionship", sortOrder: 4 },
  { name: "Hobby Participation", slug: "hobby-participation", category: "companionship", sortOrder: 5 },
  { name: "Reading & Entertainment", slug: "reading-entertainment", category: "companionship", sortOrder: 6 },
  
  // Homemaking Services
  { name: "Light Housekeeping", slug: "light-housekeeping", category: "homemaking", sortOrder: 1 },
  { name: "Meal Preparation", slug: "meal-preparation", category: "homemaking", sortOrder: 2 },
  { name: "Laundry & Linens", slug: "laundry-linens", category: "homemaking", sortOrder: 3 },
  { name: "Grocery Shopping", slug: "grocery-shopping", category: "homemaking", sortOrder: 4 },
  { name: "Home Organization", slug: "home-organization", category: "homemaking", sortOrder: 5 },
  { name: "Pet Care Assistance", slug: "pet-care", category: "homemaking", sortOrder: 6 },
  
  // Dementia Care Services
  { name: "Memory Care Support", slug: "memory-care-support", category: "dementia_care", sortOrder: 1 },
  { name: "Cognitive Stimulation", slug: "cognitive-stimulation", category: "dementia_care", sortOrder: 2 },
  { name: "Wandering Prevention", slug: "wandering-prevention", category: "dementia_care", sortOrder: 3 },
  { name: "Behavioral Support", slug: "behavioral-support", category: "dementia_care", sortOrder: 4 },
  { name: "Routine Maintenance", slug: "routine-maintenance", category: "dementia_care", sortOrder: 5 },
  
  // Respite Care Services
  { name: "Temporary Relief Care", slug: "temporary-relief", category: "respite_care", sortOrder: 1 },
  { name: "Vacation Coverage", slug: "vacation-coverage", category: "respite_care", sortOrder: 2 },
  { name: "Emergency Coverage", slug: "emergency-coverage", category: "respite_care", sortOrder: 3 },
  
  // Live-In Care Services
  { name: "24-Hour Supervision", slug: "24-hour-supervision", category: "live_in_care", sortOrder: 1 },
  { name: "Overnight Care", slug: "overnight-care", category: "live_in_care", sortOrder: 2 },
  { name: "Full-Time Companionship", slug: "full-time-companionship", category: "live_in_care", sortOrder: 3 },
];
