name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies (root)
        run: npm ci

      # If client/server have their own package.json, uncomment these:
      # - name: Install client deps
      #   run: npm ci
      #   working-directory: client
      # - name: Install server deps
      #   run: npm ci
      #   working-directory: server

      - name: Lint (optional)
        run: npm run lint --if-present

      - name: Run tests (optional)
        run: npm test --if-present

      - name: Build
        run: npm run build

