name: Deploy (PM2 reload)

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Trust host
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Rsync code
        run: |
          rsync -az --delete \
            --exclude '.git' --exclude 'node_modules' --exclude '.env' --exclude 'client/.env' \
            ${SSH_PORT:+-e "ssh -p $SSH_PORT"} \
            ./ $SSH_USER@$SSH_HOST:/var/www/html/privateinhomecare/
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_PORT: ${{ secrets.SSH_PORT }}

      - name: Reload PM2 (ecosystem)
        run: |
          ssh ${SSH_PORT:+-p "$SSH_PORT"} $SSH_USER@$SSH_HOST <<'EOSSH'
          set -e
          cd /var/www/html/privateinhomecare
          npm ci && npm install dotenv && npm run build
          pm2 startOrReload ecosystem.config.cjs --env production
          pm2 save
          EOSSH
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_PORT: ${{ secrets.SSH_PORT }}
